### PR TITLE
Stabilise MoveToWorld

### LINKED ISSUE #3649: MoveToWorld crashes when called twice at the same tick
Client version:   1.11.2
Server OS:        Linux
Commit id:        9fa8477b73ce878c631ba875ec10746b4143ba75

### Expected behavior
MoveToWorld should not crash the server.

### Actual behavior
If MoveToWorld is repeated many times, it crashes the server.

```
[14:43:44]   D:    | Cuberite has encountered an error and needs to close
[14:43:44] Details | SIGSEGV: Segmentation fault
[14:43:44] Cuberite local build build id: Unknown
[14:43:44] from commit id: approx: 9fa8477b73ce878c631ba875ec10746b4143ba75 built at: approx: 2017-03-10 01:45:11 -0600
./Cuberite(_Z15PrintStackTracev+0x1c)[0xa120ac]
./Cuberite[0x9efa89]
/lib/x86_64-linux-gnu/libc.so.6(+0x350e0)[0x7fd7c72400e0]
./Cuberite(_ZNSt4listIP7cEntitySaIS1_EE5beginEv+0x14)[0x8db874]
./Cuberite(_ZNSt4listIP7cEntitySaIS1_EE6removeERKS1_+0x20)[0x8dd130]
./Cuberite(_ZN6cChunk12RemoveEntityEP7cEntity+0x44)[0x8d7ac4]
./Cuberite[0xd87f95]
./Cuberite[14:43:44] Kicking player a for "Server is restarting. Please wait..."
[0xd87b82]
./Cuberite(_ZNKSt8functionIFvR6cWorldEEclES1_+0x58)[0x9dbb58]
./Cuberite(_ZN6cWorld15TickQueuedTasksEv+0x2ac)[0x9cfc7c]                                                                                                     [130/1961]
./Cuberite(_ZN6cWorld4TickENSt6chrono8durationIlSt5ratioILl1ELl1000EEEES4_+0x5c6)[0x9c0fb6]
./Cuberite(_ZN6cWorld11cTickThread7ExecuteEv+0xa5)[0x9c0945]
./Cuberite(_ZN9cIsThread9DoExecuteEv+0x39)[0xa04f59]
./Cuberite(_ZNKSt7_Mem_fnIM9cIsThreadFvvEEclIJEvEEvPS0_DpOT_+0x72)[0xa06642]
./Cuberite(_ZNSt12_Bind_simpleIFSt7_Mem_fnIM9cIsThreadFvvEEPS1_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE+0x42)[0xa065a2]
./Cuberite(_ZNSt12_Bind_simpleIFSt7_Mem_fnIM9cIsThreadFvvEEPS1_EEclEv+0x15)[0xa06555]
./Cuberite(_ZNSt6thread5_ImplISt12_Bind_simpleIFSt7_Mem_fnIM9cIsThreadFvvEEPS3_EEE6_M_runEv+0x1c)[0xa0652c]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb6970)[0x7fd7c7a9f970]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8064)[0x7fd7c75be064]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fd7c72f362d]
[14:43:44]   D:    | Cuberite has encountered an error and needs to close
[14:43:44] Details | SIGABRT: Server self-terminated due to an internal fault
[14:43:44] Cuberite local build build id: Unknown
[14:43:44] from commit id: approx: 9fa8477b73ce878c631ba875ec10746b4143ba75 built at: approx: 2017-03-10 01:45:11 -0600
./Cuberite(_Z15PrintStackTracev+0x1c)[0xa120ac]
./Cuberite[0x9efaed]
/lib/x86_64-linux-gnu/libc.so.6(+0x350e0)[0x7fd7c72400e0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7fd7c7240067]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7fd7c7241448]
./Cuberite[0x9efa8e]
/lib/x86_64-linux-gnu/libc.so.6(+0x350e0)[0x7fd7c72400e0]
./Cuberite(_ZNSt4listIP7cEntitySaIS1_EE5beginEv+0x14)[0x8db874]
./Cuberite(_ZNSt4listIP7cEntitySaIS1_EE6removeERKS1_+0x20)[0x8dd130]
./Cuberite(_ZN6cChunk12RemoveEntityEP7cEntity+0x44)[0x8d7ac4]
./Cuberite[0xd87f95]
./Cuberite[0xd87b82]
./Cuberite(_ZNKSt8functionIFvR6cWorldEEclES1_+0x58)[0x9dbb58]
./Cuberite(_ZN6cWorld15TickQueuedTasksEv+0x2ac)[0x9cfc7c]
./Cuberite(_ZN6cWorld4TickENSt6chrono8durationIlSt5ratioILl1ELl1000EEEES4_+0x5c6)[0x9c0fb6]
./Cuberite(_ZN6cWorld11cTickThread7ExecuteEv+0xa5)[0x9c0945]
./Cuberite(_ZN9cIsThread9DoExecuteEv+0x39)[0xa04f59]
./Cuberite(_ZNKSt7_Mem_fnIM9cIsThreadFvvEEclIJEvEEvPS0_DpOT_+0x72)[0xa06642]
./Cuberite(_ZNSt12_Bind_simpleIFSt7_Mem_fnIM9cIsThreadFvvEEPS1_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE+0x42)[0xa065a2]
./Cuberite(_ZNSt12_Bind_simpleIFSt7_Mem_fnIM9cIsThreadFvvEEPS1_EEclEv+0x15)[0xa06555]
./Cuberite(_ZNSt6thread5_ImplISt12_Bind_simpleIFSt7_Mem_fnIM9cIsThreadFvvEEPS3_EEE6_M_runEv+0x1c)[0xa0652c]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb6970)[0x7fd7c7a9f970]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8064)[0x7fd7c75be064]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fd7c72f362d]
Aborted
```

### Steps to reproduce the behavior
Include this code in a plugin:
```
for i=1,10 do
	Player:MoveToWorld("world_nether")
end
```

### LINKED ISSUE #3976: Segfault: Command /portal
Client version:   1.12.1
Server OS:        Windows/Linux
Commit id:        fa5bf7d5cd2e4abb81c2934d1736251e8692458f

### Expected behavior
Using command `/portal` to switch world should work

### Actual behavior
Server crashes:
```
#0  0x0000000000000000 in ?? ()
#1  0x0000000000834ad3 in cPlayer::FreezeInternal (this=0x7fffb0037920, a_Location=...,
    a_ManuallyFrozen=<error reading variable: access outside bounds of object referenced via synthetic pointer>)
    at /home/lukas/cpp/cuberite/src/Entities/Player.cpp:2900
#2  cPlayer::DoMoveToWorld(cWorld*, bool, Vector3<double>)::$_0::operator()(cWorld&) const (this=0x7fffe94bb580,
    a_OldWorld=...) at /home/lukas/cpp/cuberite/src/Entities/Player.cpp:2018
#3  std::_Function_handler<void (cWorld&), cPlayer::DoMoveToWorld(cWorld*, bool, Vector3<double>)::$_0>::_M_invoke(std::_Any_data const&, cWorld&) (__functor=..., __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:1731
#4  0x00000000005f77f4 in std::function<void (cWorld&)>::operator()(cWorld&) const (__args=...,
    this=<optimized out>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:2127
#5  cWorld::TickQueuedTasks (this=<optimized out>) at /home/lukas/cpp/cuberite/src/World.cpp:1213
#6  0x00000000005ecbc1 in cWorld::Tick (this=<optimized out>, a_Dt=..., a_LastTickDurationMSec=...)
    at /home/lukas/cpp/cuberite/src/World.cpp:1023
#7  0x00000000005ec82f in cWorld::cTickThread::Execute (this=<optimized out>)
    at /home/lukas/cpp/cuberite/src/World.cpp:103
#8  0x00007ffff7608e6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff7122494 in start_thread (arg=0x7fffecff5700) at pthread_create.c:333
#10 0x00007ffff6e64aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

### Steps to reproduce the behavior
Run this pycraft-file [run_cmd_portal_world.py](https://github.com/Seadragon91/pyCraft/blob/ddos_commands/run_cmd_portal_world.py)

### PR DESCRIPTION
**Pull request by peterbell10**
Fixes #3649 and fixes #3976.  I've run the scripts from the issues with much bigger loops to confirm they're fixed.

This uses the method I mentioned in #3649 but with the struct renamed `sWorldChangeInfo`. `DoMoveToWorld` now performs the move immediately and should also work correctly when the entity is still waiting to be added to the world because it uses `cWorld::RemoveEntity` and `cWorld::RemovePlayer` which check their respective adding queues.

### CODE REVIEW

**Comment by worktycho** [comment]
This approach is fundamentally different from the previous approach which used the queue task function to execute a delayed spawn in a tick on the other worlds threads, it will need careful reviewing to ensure that it does not cause new potential deadlocks in plugins.

**Comment by peterbell10** [comment]
I'm not sure what you mean @worktycho, `DoMoveToWorld` is always called from within the queued task on the tick thread.  In fact this PR has `MoveToWorld` doing less work outside of that task than before.

**Comment by worktycho** [comment]
@peterbell10 As I understand it DoMoveToWorld references both worlds in a single thread, where the previous strategy was to have the removal executed on the old worlds tick thread, and the spawn on the new worlds tick thread.

File: src/Entities/Entity.cpp [hunk 1]
```diff
@@ -1559,68 +1536,81 @@ bool cEntity::DetectPortal()
...
-	if (this->IsMob())
-	{
-		cMonster * Monster = static_cast<cMonster*>(this);
-		Monster->SetTarget(nullptr);
-		Monster->StopEveryoneFromTargetingMe();
-	}
 
-	// Queue add to new world and removal from the old one
-	cWorld * OldWorld = GetWorld();
-	SetWorld(a_World);  // Chunks may be streamed before cWorld::AddPlayer() sets the world to the new value
```
Comment (lkolbly) [inline src/Entities/Entity.cpp]: Does SetWorld need to still be called for cEntity? (or, is it and I just missed it)

(at any rate, old plugins might expect the entity's world to be the new world immediately after calling MoveToWorld)

**Comment by peterbell10** [comment]
If you mean the call to `BroadcastSpawnEntity` then `cPlayer::DoMoveToWorld` was already calling it from the old worlds tick thread.  The call in `cEntity` seemed to be missing altogether, not coordinated with the new world.

File: src/Entities/Entity.cpp (hunk 1 above)
Comment (peterbell10) [reply src/Entities/Entity.cpp]: It is set in `cWorld::AddEntity`.  Setting immediately from `MoveToWorld` could be up for discussion though.

Comment (lkolbly) [reply src/Entities/Entity.cpp]: This is ostensibly the PR that first introduced that particular call to SetWorld:
https://github.com/cuberite/cuberite/pull/1061

This PR later added the comment when it was moved into the queue system:
https://github.com/cuberite/cuberite/pull/2986

Comment (peterbell10) [reply src/Entities/Entity.cpp]: Note that at the time of #1061 `cWorld::AddEntity` didn't actually call SetWorld immediately.

File: src/Entities/Entity.cpp [hunk 2]
```diff
@@ -1559,68 +1536,81 @@ bool cEntity::DetectPortal()
...
+	if (cRoot::Get()->GetPluginManager()->CallHookEntityChangingWorld(*this, *a_World))
+	{
+		// A Plugin isn't allowing the entity to change world
+		return false;
+	}
 
+	if (!IsWorldChangeScheduled())
+	{
+		// Schedule a new world change.
+		m_WorldChangeInfo = cpp14::make_unique<sWorldChangeInfo>();
```
Comment (madmaxoft) [inline src/Entities/Entity.cpp]: This is thread-unsafe. One thread may set the `m_WorldChangeInfo` to a valid value while another thread is between the `if` above and this line.

File: src/Entities/Entity.cpp [hunk 3]
```diff
@@ -1559,68 +1536,81 @@ bool cEntity::DetectPortal()
...
+		GetWorld()->QueueTask(
+			[this](cWorld &)
+			{
+				DoMoveToWorld(*m_WorldChangeInfo);
+				m_WorldChangeInfo.reset();
```
Comment (madmaxoft) [inline src/Entities/Entity.cpp]: Again unsafe, another thread may schedule a move while DoMoveToWorld is executing, and that change will get lost.

**Comment by peterbell10** [comment]
I think the thread safety issues with `m_WorldChangeInfo` could be fixed with an atomic version of `unique_ptr`.  However, I think all the world change stuff should be called under the chunk map cs anyway (which would mean the task is still wrong).

**Comment by madmaxoft** [comment]
`MoveToWorld` can be called by the plugins from virtually any thread (including webadmin), so thread safety there is still a concern.

**Comment by peterbell10** [comment]
Wouldn't a plugin have to go through a DoWith type function first though?

**Comment by madmaxoft** [comment]
That's true. In that case, if you always expect a CS to be locked in the method, why not add an ASSERT for it? It would make debugging much easier :)

**Comment by peterbell10** [comment]
Hrm, it seems that a plugin can get a `cPlayer` without the CS from command handlers.  This potentially breaks a lot of assumptions in the entity code.

**Comment by peterbell10** [comment]
Is there a reason why `CallHookEntityChangedWorld` was never called in [`cPlayer::DoMoveToWorld`](https://github.com/cuberite/cuberite/blob/b12f4ef7d58cfe4d815feb2db1f88f223c7f2a61/src/Entities/Player.cpp#L1982-L2063)?

File: src/Entities/Entity.cpp (hunk 1 above)
Comment (lkolbly) [reply src/Entities/Entity.cpp]: It may not be an issue anymore, then.

**Comment by peterbell10** [comment]
I find it a bit odd that players are different from every other entity but as long as it's not missing I guess it's okay then.

File: src/Entities/Entity.cpp (hunk 2 above)
Comment (peterbell10) [reply src/Entities/Entity.cpp]: Is the new atomic version okay?

Comment (lkolbly) [reply src/Entities/Entity.cpp]: I think conceivably https://github.com/cuberite/cuberite/pull/4004/files/#diff-f312969b3897e838a1085ffb60b7c4dfR1612 could be called between https://github.com/cuberite/cuberite/pull/4004/files/#diff-f312969b3897e838a1085ffb60b7c4dfR1604 and the if statement, which would cause a WorldChangeInfo to be scheduled twice in a row. I don't think that'd actually cause any problems, though, since most of the failsafes are in DoMoveToWorld.

Comment (peterbell10) [reply src/Entities/Entity.cpp]: Both exchanges are atomic and the comparison is done on the exchange result and not from an additional load of `m_WorldChangeInfo` so I don't think that's an issue.

File: src/OSSupport/AtomicUniquePtr.h [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+		{
+			// Only release ownership from the caller if the exchange occurred
+			a_Desired.release();
+		}
+		return DidExchange;
+	}
+
+	T * exchange(std::unique_ptr<T> a_Ptr, std::memory_order a_Order = std::memory_order_seq_cst) NOEXCEPT
+	{
+		return m_Ptr.exchange(a_Ptr.release(), a_Order);
```
Comment (madmaxoft) [inline src/OSSupport/AtomicUniquePtr.h]: Is this safe? If the exchange doesn't happen, `a_Ptr` stays released, I think. I'm not too educated in the memory ordering and these operations, though.

Comment (peterbell10) [reply src/OSSupport/AtomicUniquePtr.h]: >If the exchange doesn't happen
Not sure what you mean. it's an unconditional exchange so it should always happen.

Comment (madmaxoft) [reply src/OSSupport/AtomicUniquePtr.h]: Right, sorry, I was thinking about compare_and_exchange

**Comment by bearbin** [comment]
@peterbell10, @madmaxoft, is this PR going to be ready to merge soon?

File: src/Entities/Entity.cpp [hunk 5]
```diff
@@ -1559,68 +1536,87 @@ bool cEntity::DetectPortal()
...
+		// Moving to same world, don't need to remove from world
+		return;
 	}
 
 	// Stop ticking, in preperation for detaching from this world.
 	SetIsTicking(false);
 
-	// Tell others we are gone
-	GetWorld()->BroadcastDestroyEntity(*this);
+	a_WorldChangeInfo.m_NewWorld->BroadcastSpawnEntity(*this);
```
Comment (peterbell10) [inline src/Entities/Entity.cpp]: This line makes me uncomfortable.  It's locking the new world while the lock for the current is already held and thus a potential deadlock.

I think the cleanest way to fix this is to move the Broadcast call into `cWorld::Tick` when `m_EntitiesToAdd` is processed.  Anybody have thoughts on this?

**Comment by mathiascode** [comment]
Tested this with #4484 and #4487, haven't noticed any issues so far. Also haven't seen any issues with invisible players in any form.

File: src/Entities/Entity.cpp [hunk 6]
```diff
@@ -158,19 +157,28 @@ bool cEntity::Initialize(OwnedEntity a_Self, cWorld & a_EntityWorld)
...
 	cPluginManager::Get()->CallHookSpawnedEntity(a_EntityWorld, *this);
 
+	return true;
+}
+
+
+
+
+
+void cEntity::OnAddToWorld(cWorld & a_World)
```
Comment (mathiascode) [inline src/Entities/Entity.cpp]: Update m_LastSentPosition here, so entities spawn at the right location client-side.
