### PR TITLE
NBT: Dynamic list-max-count protection.

### LINKED ISSUE #4696: NBT parsing failed when many furnaces are placed and server is restarted
Client version: 1.12.2
Server OS: Linux

### Actual behavior
Server regenerates chunk, when server is restarted

### Steps to reproduce the behavior
I attached a zip file with the [world](https://github.com/cuberite/cuberite/files/4547452/world.zip) that causes the error:
```
Loading chunk [-2, 1] for world world from file r.-1.0.mca failed: NBT parsing failed. Offloading old chunk data to file world/region/badchunks/ch.-2.1.2020-04-28-19-22-23.dat and regenerating chunk
```
Use worldedit to place many furnaces. Restart the server and the error appears.

### PR DESCRIPTION
**Pull request by madmaxoft**
Loosened the check agains invalid / malicious NBT list size, from a constant maximum to a maximum of `BytesLeft / 4` items.

Fixes #4696

### CODE REVIEW

File: src/WorldStorage/FastNBT.cpp [hunk 1]
```diff
@@ -257,7 +250,7 @@ eNBTParseError cParsedNBT::ReadList(eTagType a_ChildrenType)
 	NEEDBYTES(4, eNBTParseError::npListMissingLength);
 	int Count = GetBEInt(m_Data + m_Pos);
 	m_Pos += 4;
-	if ((Count < 0) || (Count > MAX_LIST_ITEMS))
+	if ((Count < 0) || (Count > static_cast<int>((m_Length - m_Pos) / 4)))
```
Comment (peterbell10) [inline src/WorldStorage/FastNBT.cpp:253]: Why 4? Should this depend on `a_ChildrenType` or is 4 a lower bound?

Comment (madmaxoft) [reply src/WorldStorage/FastNBT.cpp:253]: No specific reason. I wanted to keep it simple to read. But you're right, it's bound to fail randomly in the future, I'll rewrite it to take the children size into account.

File: src/WorldStorage/FastNBT.cpp [hunk 2]
```diff
@@ -445,6 +439,28 @@ int cParsedNBT::FindTagByPath(int a_Tag, const AString & a_Path) const
...
+		case TAG_Int:       return 4;
+		case TAG_Long:      return 8;
+		case TAG_Float:     return 4;
+		case TAG_Double:    return 8;
+		case TAG_String:    return 2;  // 2 bytes for the string length
+		case TAG_ByteArray: return 4;  // 4 bytes for the count
+		case TAG_List:      return 5;  // 1 byte list type + 4 bytes count
+		case TAG_Compound:  return 1;  // Single TAG_End byte
+		case TAG_IntArray:  return 4;  // 4 bytes for the count
+	}
```
Comment (peterbell10) [inline src/WorldStorage/FastNBT.cpp:457]: Add `UNREACHABLE` after the switch to silence clang warnings.

Comment (madmaxoft) [reply src/WorldStorage/FastNBT.cpp:457]: Actually the warning was worth it, there was one type missing; verifying a new commit now.

**Comment by tigerw** [comment]
Am I correct in saying that the code now essentially does an "ARRAYCOUNT" on the remaining length (?) of the file, with the type being a_ChildrenType, and fails if the Count specified on-disk exceeded what could possibly be held in the space available?

**Comment by madmaxoft** [comment]
Yes, basically.
