### PR TITLE
Fix fence gates

### LINKED ISSUE #3679: pressure plate not working with fence gate
Client version:   1.11.2
Server OS:        Ubuntu 16.04 LTS
Commit id:        7960d142ca3e28e0e4550faf131398899dca90dc

### Expected behavior
Adjacent pressure plate should trigger opening of the fence gate.

### Actual behavior
Fence gate has no reaction to pressure plate activation.

### Steps to reproduce the behavior
See here: https://i.imgur.com/TTgHxC6.gifv
(or [here](https://imgur.com/a/PEzlI) if that doesn't work)

### PR DESCRIPTION
**Pull request by Bond-009**
This commit fixes an issue where a pressureplate would only open oak fence gates
Fixes #3679

### CODE REVIEW

File: src/Simulator/IncrementalRedstoneSimulator/IncrementalRedstoneSimulator.cpp [hunk 1]
```diff
@@ -49,8 +49,13 @@ std::unique_ptr<cRedstoneHandler> cIncrementalRedstoneSimulator::CreateComponent
 		case E_BLOCK_STONE_PRESSURE_PLATE:
 		case E_BLOCK_WOODEN_PRESSURE_PLATE: return cpp14::make_unique<cPressurePlateHandler>(a_World);
 
+		case E_BLOCK_ACACIA_FENCE_GATE:
+		case E_BLOCK_BIRCH_FENCE_GATE:
+		case E_BLOCK_DARK_OAK_FENCE_GATE:
 		case E_BLOCK_FENCE_GATE:
+		case E_BLOCK_JUNGLE_FENCE_GATE:
```
Comment (madmaxoft) [inline src/Simulator/IncrementalRedstoneSimulator/IncrementalRedstoneSimulator.cpp]: Alpha-sort please, `JUNGLE` goes after `IRON`

**Comment by madmaxoft** [comment]
Looks good, merge after the style-fix.

**Comment by Bond-009** [comment]
@madmaxoft Fixed it
