### PR TITLE
Chorus fruit teleport

### LINKED ISSUE #5043: Chorus fruit and ender pearls should teleport the player off of rideable mobs
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: a0afd132330ab538848d5ac263c021c1247fd688

### Expected behavior
Throwing an ender pearl or eating chorus fruit should teleport a player off a rideable mob like a horse or a pig.

### Actual behavior
This doesn't happen, the player stays mounted.

### Steps to reproduce the behavior
Throw an ender pearl while riding a horse.

### PR DESCRIPTION
**Pull request by KingCol13**
Eating chorus fruit attempts a teleport.
Reference: https://minecraft.fandom.com/wiki/Enderman#Teleportation

Fixes #5043, #5044.

Wasn't too sure where to put `FindTeleportDestination` so feedback on that or anything else would be very welcome.

### CODE REVIEW

File: src/Mobs/Enderman.cpp [hunk 1]
```diff
@@ -5,9 +5,60 @@
 #include "Enderman.h"
 #include "../Entities/Player.h"
 #include "../LineBlockTracer.h"
+#include "../BlockInfo.h"
 
+bool FindTeleportDestination(cWorld *a_World, Vector3i a_Centre, const int a_HalfCubeWidth, const int a_HeightRequired, const unsigned int a_NumTries, Vector3i &a_Destination)
```
Comment (12xx12) [inline src/Mobs/Enderman.cpp:10]: This is a great Idea. I think this could be a static function of cEntity or cPawn

File: src/Mobs/Enderman.cpp [hunk 2]
```diff
@@ -5,9 +5,60 @@
...
+{
+	/*
+	Algorithm:
+	Choose random destination.
+	Seek downwards, regardless of distance until the block is made of movement-blocking material: https://minecraft.fandom.com/wiki/Materials
+	Succeeds if no liquid or solid blocks prevents from standing at destination.
+	*/
+	auto & Random = GetRandomProvider();
+
+	for (unsigned int i=0; i<a_NumTries; i++)
```
Comment (12xx12) [inline src/Mobs/Enderman.cpp:20]:
```suggestion
	for (unsigned int i = 0; i < a_NumTries; i++)
```
Please use space between operators

File: src/Mobs/Enderman.cpp (hunk 1 above)
Comment (12xx12) [inline src/Mobs/Enderman.cpp:10]: This could also use a `cBoundingBox` for example to define asymmetric areas. For whatever reason somewhat would use that. Maybe even reveal this to the API

File: src/Mobs/Enderman.cpp [hunk 3]
```diff
@@ -5,9 +5,60 @@
...
+		// Seek downwards from initial destination until we find a solid block or go into the void
+		BLOCKTYPE DestBlock = a_World->GetBlock({DestX, DestY, DestZ});
+		while ((DestY >= 0) && !cBlockInfo::IsSolid(DestBlock))
+		{
+			DestBlock = a_World->GetBlock({DestX, DestY, DestZ});
+			DestY--;
+		}
+
+		// Couldn't find a solid block so move to next attempt
+		if (DestY<0)
```
Comment (12xx12) [inline src/Mobs/Enderman.cpp:35]:
```suggestion
		if (DestY < 0)
```

File: src/Items/ItemChorusFruit.h [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+		cItemHandler::EatItem(a_Player, a_Item);
+
+		if (!a_Player->IsGameModeCreative())
+		{
+			a_Player->GetInventory().RemoveOneEquippedItem();
+		}
+
+		// Attempt to find a teleport destination
+		Vector3i Destination;
+		cWorld *World = a_Player->GetWorld();
```
Comment (12xx12) [inline src/Items/ItemChorusFruit.h:34]:
```suggestion
		cWorld * World = a_Player->GetWorld();
```

File: src/Mobs/Enderman.cpp [hunk 5]
```diff
@@ -5,9 +5,60 @@
...
+		{
+			continue;
+		}
 
+		// Succeed if blocks above destination are empty
+		bool Success = true;
+		for (int j=1; j <= a_HeightRequired; j++)
```
Comment (12xx12) [inline src/Mobs/Enderman.cpp:42]:
```suggestion
		for (int j = 1; j <= a_HeightRequired; j++)
```

**Review by 12xx12 — CHANGES_REQUESTED** [review]
There we go - another feature 😄 Thanks

Just some small style stuff and suggestions

File: src/Mobs/Enderman.cpp (hunk 1 above)
Comment (KingCol13) [reply src/Mobs/Enderman.cpp:10]: Yep that seems more logical, thanks!

Comment (KingCol13) [reply src/Mobs/Enderman.cpp]: Alrighty I sorted out a cBoundingBox interface and might have successfully exported it to the API but that's all magic to me so I'm not sure.

**Comment by 12xx12** [comment]
This looks about right. The API function needs to be documented in `Server/Plugins/APIDump/APIDesc.lua`. Just follow the other already existing functions and alpha sort please

**Review by 12xx12 — APPROVED** [review]

**Review by bearbin — APPROVED** [review]

**Comment by PureTryOut** [comment]
Oh another feature, awesome! Slowly but surely Cuberite becomes actually usable for survival servers!
