### PR TITLE
cBlockRail: Fix assertion failure

### LINKED ISSUE #4074: Assertion failure in cBlockRail::FindMeta
Client version:   1.12.2
Server OS:        Windows
Commit id:       5badb9bccae803009bde182bf69ee0d02a36b22c

### Actual behavior
Assertion failure in `cBlockRail::FindMeta`
https://github.com/cuberite/cuberite/blob/5badb9bccae803009bde182bf69ee0d02a36b22c/src/Blocks/BlockRail.h#L202

### Steps to reproduce the behavior
Place two rails, one at +x, +y from the other.

### PR DESCRIPTION
**Pull request by peterbell10**
Fixes #4074

### CODE REVIEW

File: src/Blocks/BlockRail.h [hunk 1]
```diff
@@ -147,7 +147,7 @@ class cBlockRailHandler :
 		Neighbors[2] = (IsUnstable(a_ChunkInterface, a_BlockPos - Vector3i(0, 0, 1)) || !IsNotConnected(a_ChunkInterface, a_BlockPos, BLOCK_FACE_NORTH, E_PURE_DOWN));
 		Neighbors[3] = (IsUnstable(a_ChunkInterface, a_BlockPos + Vector3i(0, 0, 1)) || !IsNotConnected(a_ChunkInterface, a_BlockPos, BLOCK_FACE_SOUTH, E_PURE_DOWN));
 		Neighbors[4] = (IsUnstable(a_ChunkInterface, a_BlockPos + Vector3i(1, 1, 0)) || !IsNotConnected(a_ChunkInterface, a_BlockPos + Vector3i(0, 1, 0), BLOCK_FACE_EAST, E_PURE_NONE));
-		Neighbors[5] = (IsUnstable(a_ChunkInterface, a_BlockPos - Vector3i(1, 1, 0)) || !IsNotConnected(a_ChunkInterface, a_BlockPos + Vector3i(0, 1, 0), BLOCK_FACE_WEST, E_PURE_NONE));
+		Neighbors[5] = (IsUnstable(a_ChunkInterface, a_BlockPos + Vector3i(-1, 1, 0)) || !IsNotConnected(a_ChunkInterface, a_BlockPos + Vector3i(0, 1, 0), BLOCK_FACE_WEST, E_PURE_NONE));
```
Comment (lkolbly) [inline src/Blocks/BlockRail.h]: Per your comment https://github.com/cuberite/cuberite/pull/4050/files/1eb3f5574a41669672c884080f0eaf7256fdffec#r142244668, it might be reasonable to change the signs of 1 and 2 while this PR is open.

Comment (peterbell10) [reply src/Blocks/BlockRail.h]: Fair enough, done.
