### PR TITLE
Changed mob age from char to int

### LINKED ISSUE #2398: Change cMonster age from char to int
Current code represents the mob age as a char; this is clearly wrong, the age should be a full int, incremented at each server tick.
Ref.: http://minecraft.gamepedia.com/Chunk_format#Breedable, "Age" is a TAG_Int

### PR DESCRIPTION
**Pull request by SphinxC0re**
Fixes #2398

### CODE REVIEW

**Comment by madmaxoft** [comment]
You need to fix the NBT reading and the protocol, too

**Comment by SphinxC0re** [comment]
Where is the reading part located?

**Comment by SphinxC0re** [comment]
Is this okay now?

**Comment by madmaxoft** [comment]
You didn't test-play after the changes, did you? I think you broke the protocol. The values there are single bytes, they only specify whether the mob is a baby or not, rather than the full age.
http://wiki.vg/Entities#Ageable

**Comment by SphinxC0re** [comment]
Okay, now I'm confused. Is it a char, an int or a byte? The issue is about changing the mob age from char to int

**Comment by madmaxoft** [comment]
Yes, the age itself should be an int. But in the client protocol, only a byte flag is sent, whether the mob is a baby or not, so it should stay a char.
`a_Pkt.WriteBEInt8(Horse.IsBaby() ? -1 : 0);`

**Comment by madmaxoft** [comment]
We need to get this fixed. Worlds generated by Vanilla assert in Cuberite because Cuberite tries to read the age as a byte, while it is indeed an int in the NBT.

**Comment by bibo38** [comment]
@SphinxC0re Any updates on this?
In short terms:

- NBT stores this as an int
- The protocol only uses a byte, because the client only needs to know, that it is a baby

**Comment by SphinxC0re** [comment]
I halted the work on this for a while. But it shouldn't be too hard to fix this

**Comment by SphinxC0re** [comment]
This should be okay to merge now

File: src/WorldStorage/WSSAnvil.cpp [hunk 1]
```diff
@@ -2344,8 +2344,8 @@ void cWSSAnvil::LoadHorseFromNBT(cEntityList & a_Entities, const cParsedNBT & a_
 	int AgeableIdx  = a_NBT.FindChildByName(a_TagIdx, "Age");
 	if (AgeableIdx > 0)
 	{
-		Byte Age = a_NBT.GetByte(AgeableIdx);
-		Monster->SetAge(static_cast<char>(Age));
+		int Age = a_NBT.GetInt(AgeableIdx);
```
Comment (madmaxoft) [inline src/WorldStorage/WSSAnvil.cpp]: This will now assert on maps created by the previous code, because it used to store the age as a char, but now it's reading an int. You need to detect the item's datatype and load accordingly.

Comment (SphinxC0re) [inline src/WorldStorage/WSSAnvil.cpp]: How do I do that?

Comment (madmaxoft) [inline src/WorldStorage/WSSAnvil.cpp]:
```cpp
int Age;
switch (a_NBT.GetType(AgeIdx))
{
  case TAG_Byte: Age = a_NBT.GetByte(AgeIdx); break;
  case TAG_Int:  Age = a_NBT.GetInt (AgeIdx); break;
  default: Age = 0; break;
}
```

**Comment by SphinxC0re** [comment]
Is this okay now?

**Comment by SphinxC0re** [comment]
@cuberite/core-team
