### PR TITLE
Check for nil in cWorld:SpawnSplitExperienceOrbs binding

### LINKED ISSUE #4352: API: Crash on call to cWorld:SpawnSplitExperienceOrbs
Server OS:        Windows
Commit id:        (9dc1343bda0592f2d27bb216eb21fdec97f73945)

### Expected behavior
Server should not crash

### Actual behavior
Server crashes

### Steps to reproduce the behavior
1) Add this code to a plugin inside a command handler
2) Call the command
`cRoot:Get():GetDefaultWorld():SpawnSplitExperienceOrbs(nil, 1)`

### PR DESCRIPTION
**Pull request by masp**
Adds explicit nil check for 'position' parameter to prevent crashes if invalid.

Fixes #4352

### CODE REVIEW

File: src/Bindings/ManualBindings_World.cpp [hunk 1]
```diff
@@ -890,14 +890,19 @@ static int tolua_cWorld_SpawnSplitExperienceOrbs(lua_State* tolua_S)
...
 	int Reward;
 	L.GetStackValues(1, self, Position, Reward);
 	if (self == nullptr)
 	{
 		tolua_error(tolua_S, "Invalid 'self' in function 'SpawnSplitExperienceOrbs'", nullptr);
 		return 0;
 	}
+	if (Position == nullptr)
+	{
+		tolua_error(tolua_S, "Error in function 'SpawnSplitExperienceOrbs' arg #2. Value must not be nil.", nullptr);
```
Comment (madmaxoft) [inline src/Bindings/ManualBindings_World.cpp]: The message might be misleading, `Position == nullptr` due to other causes as well - bad parameter type. A better message would be `Value must be a valid Vector3`, or even better `Expected Vector3, got XYZ instead`.

Comment (masp) [reply src/Bindings/ManualBindings_World.cpp]: Oh, I thought that the `CheckParamUserType(2, "Vector3<double>")` at the top of the function would check for that kind of type mismatch, and that only `nil` was slipping through because it's a valid `Vector3<double>`.

Comment (madmaxoft) [reply src/Bindings/ManualBindings_World.cpp]: You're right, I've missed that. Sorry.
