### PR TITLE
Fix client disconnect assert

### LINKED ISSUE #4577: Crash when leaving the game
Client version: 1.12.2
Server OS: Linux (debian bullseye/clang 9.0.1-10)
Cuberite Commit id: 31ace87d

The server crashed immediately after leaving. It appeared that somehow the Player was destroyed before the ClientHandle. The issue was reproducible for a while, even when changing some parts of the code. However after clearing my working directory and trying to compile from fresh the issue disappeared. I guess this could be some compilation artifact but I don't know how that would interfere with the lifetime of cPlayer.

### Server log
```
[7359a5658c0d6291|16:56:34] Client bearbin @ ::ffff:127.0.0.1 disconnected
[d43d95798065f534|16:56:34] Client bearbin @ ::ffff:127.0.0.1 (0x7fd23c000d90) has been queued for destruction, destroying now.
[d43d95798065f534|16:56:34] Destroy: destroying client 0x7fd23c000d90, "bearbin" @ ::ffff:127.0.0.1
[d43d95798065f534|16:56:34] Player bearbin has left the game
[d43d95798065f534|16:56:34] Deleting cPlayer "bearbin" at 0x7fd204002210, ID 42
[d43d95798065f534|16:56:34] Player 0x7fd204002210 deleted
Player not in waiting list!
[d43d95798065f534|16:56:34] Removing player bearbin from world "world"
[d43d95798065f534|16:56:34] Assertion failed: m_PlayerPtr, file /home/bearbin/cuberite/cuberite/src/ClientHandle.cpp, line 191
./Cuberite(_Z15PrintStackTracev+0x1c)[0xb71bfc]
```

### LINKED ISSUE #4578: Assert when stopping a server with players
Client version: 1.12.2
Server OS: Windows
Cuberite Commit id: aa9a16b0c6f1838a6c1e61ce6ab83fa8e4ea35bf

Connect the client to the server, then execute a `stop` command in the server console.

### Expected behavior
Server shuts off.

### Actual behavior
Server raises an assert:
```
Cuberite.exe!_wassert(const wchar_t * expression=0x00007ff6d0f76d6c, const wchar_t * file_name=0x00007ff6d0f77ad0, unsigned int line_number=1841) Line 405	C++
Cuberite.exe!cChunk::RemoveEntity(cEntity & a_Entity={...}) Line 1841	C++
Cuberite.exe!cChunkMap::RemoveEntity(cEntity & a_Entity={...}) Line 1079	C++
Cuberite.exe!cWorld::RemovePlayer(cPlayer & a_Player={...}) Line 2495	C++
Cuberite.exe!cClientHandle::Destroy() Line 188	C++
Cuberite.exe!cClientHandle::Tick(float a_Dt=55.0000000) Line 2105	C++
Cuberite.exe!cWorld::TickClients(float a_Dt=55.0000000) Line 1276	C++
Cuberite.exe!cWorld::Tick(std::chrono::duration<__int64,std::ratio<1,1000> > a_Dt={...}, std::chrono::duration<__int64,std::ratio<1,1000> > a_LastTickDurationMSec={...}) Line 1045	C++
```
The offending line:
```cpp
ASSERT(!a_Entity.IsTicking());
```

### Server log:
```
stop
[b8604cfab3c9249e|18:52:49] Kicking player xoft for "Server shutdown"
[b8604cfab3c9249e|18:52:49] Sending a DC: "Server shutdown"
[db0638fac7691f4a|18:52:49] Client xoft @ ::ffff:127.0.0.1 disconnected
[30877286c4961f59|18:52:49] Client xoft @ ::ffff:127.0.0.1 (0xdd6d8c4490) has been queued for destruction, destroying now.
[30877286c4961f59|18:52:49] cClientHandle::Destroy: destroying client 0xdd6d8c4490, "xoft" @ ::ffff:127.0.0.1
[30877286c4961f59|18:52:49] Player xoft has left the game
[30877286c4961f59|18:52:49] Deleting cPlayer "xoft" at 0xdd6d8c60f0, ID 11
[30877286c4961f59|18:52:49] Player 0xdd6d8c60f0 deleted
[30877286c4961f59|18:52:49] Assertion failed: !a_Entity.IsTicking(), file C:\Programy\Cuberite.4\src\Chunk.cpp, line 1841
```
I assume the recent refactoring of clients disconnecting (#4533) may be at fault here.

### PR DESCRIPTION
**Pull request by peterbell10**
Fixes #4577, fixes #4578

### CODE REVIEW

File: src/ClientHandle.cpp [hunk 1]
```diff
@@ -197,6 +195,8 @@ void cClientHandle::Destroy(void)
 		}
 	}
 	player->RemoveClientHandle();
+	SetState(csDestroyed);  // Tick thread is allowed to call destructor async at any time after this
+	m_Self.reset();
```
Comment (peterbell10) [inline src/ClientHandle.cpp]: Race condition, tick thread could delete the client while this function is still running, so accessing `m_PlayerPtr` was invalid.

File: src/ClientHandle.cpp [hunk 2]
```diff
@@ -3350,7 +3350,7 @@ void cClientHandle::SetSelf(cClientHandlePtr a_Self)
 bool cClientHandle::SetState(eState a_NewState)
 {
 	cCSLock Lock(m_CSState);
-	if (a_NewState < m_State)
+	if (a_NewState <= m_State)
```
Comment (peterbell10) [inline src/ClientHandle.cpp]: `SetState(csDestroying)` should only succeed once, so need to return false on `a_NewState == m_State`.

File: src/World.cpp [hunk 3]
```diff
@@ -2543,9 +2543,13 @@ std::unique_ptr<cPlayer> cWorld::RemovePlayer(cPlayer & a_Player)
 #ifdef _DEBUG
 bool cWorld::IsPlayerReferencedInWorldOrChunk(cPlayer & a_Player)
 {
-	if (m_ChunkMap->RemoveEntity(a_Player) != nullptr)
```
Comment (peterbell10) [inline src/World.cpp]: The existence check was removing the player object from the world...
