### PR TITLE
Fix generator repeatability

### LINKED ISSUE #4384: Chunk generator creates different data on different platforms / build-types
While implementing #4382 it by chance became obvious that our default Nether generator generates different data in Debug and Release builds on Linux. We need to find out why and fix it, the assumption has always been that the generator is platform- and build-type-independent.

As the first step, a new test needs to be made to check the generators, how many of them are affected. Then, fix all those that fail the test.

### PR DESCRIPTION
**Pull request by madmaxoft**
This hot-fixes the Nether generator producing differrent data on Linux Release builds, and adds a check for the default Overworld and Nether generators whether they produce the same output on all platforms.

Fixes #4384.

### CODE REVIEW

**Comment by madmaxoft** [comment]
Huh, I first added the tests and then the fix, but rebased to put the two commits in reverse order. Now Github shows them in the original order, while they are in the right order in the code. That's becoming weird.

File: tests/Generating/BasicGeneratorTest.cpp [hunk 1]
```diff
@@ -217,7 +218,94 @@ static void testGenerateNether()
...
+
+
+/** Checks that the specified generator generates chunk that match the specified checksums. */
+static void checkChunkChecksums(
+	cChunkGenerator & aGenerator,
+	const std::vector<CoordsWithChecksum> & aCoordsWithChecksum,
+	const AString & aDimension
+)
+{
+	LOG("Testing the repeatability of the %s generator", aDimension.c_str());
```
Comment (peterbell10) [inline tests/Generating/BasicGeneratorTest.cpp]:
```suggestion
	LOG("Testing the repeatability of the %s generator", aDimension);
```

File: tests/Generating/BasicGeneratorTest.cpp [hunk 2]
```diff
@@ -217,7 +218,94 @@ static void testGenerateNether()
...
+	for (const auto & coords: aCoordsWithChecksum)
+	{
+		cChunkDesc chd(coords.mCoords);
+		aGenerator.Generate(coords.mCoords.m_ChunkX, coords.mCoords.m_ChunkZ, chd);
+		auto checksum = chunkSHA1(chd);
+		TEST_EQUAL_MSG(checksum, coords.mChecksum,
+			Printf("%s chunk %s SHA1: expected %s, got %s", aDimension.c_str(), coords.mCoords.ToString().c_str(), coords.mChecksum.c_str(), checksum.c_str())
```
Comment (peterbell10) [inline tests/Generating/BasicGeneratorTest.cpp]:
```suggestion
			Printf("%s chunk %s SHA1: expected %s, got %s", aDimension, coords.mCoords.ToString(), coords.mChecksum, checksum)
```

File: tests/Generating/BasicGeneratorTest.cpp (hunk 1 above)
Comment (madmaxoft) [reply tests/Generating/BasicGeneratorTest.cpp]: I don't think a `std::string` is allowed to be passed through `...` varargs, I seem to remember this being an undefined behavior.

Comment (peterbell10) [reply tests/Generating/BasicGeneratorTest.cpp]: It doesn't use c-style varargs any more
https://github.com/cuberite/cuberite/blob/d8d1e6e1d2f668cb7b34eae7484e59e2310e847a/src/LoggerSimple.h#L21

Comment (madmaxoft) [reply tests/Generating/BasicGeneratorTest.cpp]: Okay, template magic... :P
