### PR TITLE
Fixed and improved restarting

### LINKED ISSUE #2094: Server crash on restart
Raspberry Pi 2, Arch Linux

```
./MCServer(_ZN5cRoot5StartESt10unique_ptrI28cSettingsRepositoryInterfaceSt14default_deleteIS1_EE+0x244)[0x1ab208]
./MCServer(_Z13universalMainSt10unique_ptrI28cSettingsRepositoryInterfaceSt14default_deleteIS0_EE+0x38)[0x1dc9d4]
./MCServer(main+0x1d4)[0x11e150]
/usr/lib/libc.so.6(__libc_start_main+0x114)[0x76c92d3c]
[13:05:00]   D:    | MCServer has encountered an error and needs to close
[13:05:00] Details | SIGABRT: Server self-terminated due to an internal fault
./MCServer(_Z15PrintStackTracev+0x14)[0x1ee77c]
./MCServer(_Z14NonCtrlHandleri+0xb4)[0x1dc5f0]
/usr/lib/libc.so.6(__default_sa_restorer+0x0)[0x76ca8a90]
/usr/lib/libc.so.6(gsignal+0x34)[0x76ca7864]
/usr/lib/libc.so.6(abort+0x12c)[0x76ca8c08]
./MCServer(_Z14NonCtrlHandleri+0x8c)[0x1dc5c8]
/usr/lib/libc.so.6(__default_sa_restorer+0x0)[0x76ca8a90]
./MCServer(_ZN28cOverridesSettingsRepository12GetValueSetBERKSsS1_b+0x18)[0x190ec0]
./MCServer(_ZN5cRoot5StartESt10unique_ptrI28cSettingsRepositoryInterfaceSt14default_deleteIS1_EE+0x244)[0x1ab208]
./MCServer(_Z13universalMainSt10unique_ptrI28cSettingsRepositoryInterfaceSt14default_deleteIS0_EE+0x38)[0x1dc9d4]
./MCServer(main+0x1d4)[0x11e150]
/usr/lib/libc.so.6(__libc_start_main+0x114)[0x76c92d3c]

```
Linux alarmpi 3.18.13-1-ARCH #1 SMP PREEMPT Sun May 10 18:44:09 MDT 2015 armv7l GNU/Linux

Firmware version:
```
[artur@alarmpi MCServer]$ pacman -Q raspberrypi-firmware
raspberrypi-firmware 20150518-1
```

Last log:
```
     [13:01:54] --- Started Log ---

     [13:01:54] Creating new server instance...
     [13:01:54] Reading server config...
     [13:01:54] Starting server...
info [13:01:54] Compatible clients: 1.7.x, 1.8.x
info [13:01:54] Compatible protocol versions 4, 5, 47
Warn [13:01:54] WebServer: The server is running in unsecured HTTP mode.
info [13:01:54] Put a valid HTTPS certificate in file 'webadmin/httpscert.crt' and its corresponding private key to 'webadmin/httpskey.pem' (without any password) to enable HTTPS support
     [13:01:54] Loaded 407 crafting recipes
     [13:01:54] Loaded 20 furnace recipes and 56 fuels
     [13:01:54] -- Loading Plugins --
     [13:01:54] -- No Plugins Loaded --
     [13:02:01] Preparing spawn (world): 18.50% (74/400; 71.57 chunks / sec)
     [13:02:02] Preparing spawn (world): 60.25% (241/400; 153.63 chunks / sec)
     [13:02:03] Startup complete, took 9573ms!
     [13:02:03] Executing console command: "load Core"
     [13:02:03] Initialised Core v.15
     [13:02:03] Plugin loaded
info [13:02:09] Player artur9010 has joined the game
     [13:03:14] Changing to clear weather in world: world by: artur9010
     [13:04:58] Shutting down server...
info [13:04:58] Player artur9010 has left the game
     [13:04:59] Waiting for the world storage to finish saving
     [13:05:00] World storage thread finished
     [13:05:00] Waiting for the world storage to finish saving
     [13:05:00] World storage thread finished
     [13:05:00] Disabled Core!
     [13:05:00] Cleaning up...
     [13:05:00] Shutdown successful!
     [13:05:00] Creating new server instance...
     [13:05:00] Reading server config...
     [13:05:00] Starting server...
Err  [13:05:00]   D:    | MCServer has encountered an error and needs to close
Err  [13:05:00] Details | SIGSEGV: Segmentation fault
Err  [13:05:00]   D:    | MCServer has encountered an error and needs to close
Err  [13:05:00] Details | SIGABRT: Server self-terminated due to an internal fault
```

MCServer built using http://forum.mc-server.org/showthread.php?tid=1937

### LINKED ISSUE #2232: Segfault in cMojangAPI
I wanted to login into my server, didn't work and then I stopped it to restart. This crash appears.

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4c59700 (LWP 6165)]
0x00007ffff74b4414 in pthread_mutex_lock ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
  Id   Target Id         Frame 
* 4    Thread 0x7ffff4c59700 (LWP 6165) "MCServer" 0x00007ffff74b4414 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
  2    Thread 0x7ffff6b51700 (LWP 6163) "MCServer" 0x00007ffff6c46859 in syscall () from /lib/x86_64-linux-gnu/libc.so.6
  1    Thread 0x7ffff7fc5780 (LWP 6162) "MCServer" 0x00007ffff74b366b in pthread_join () from /lib/x86_64-linux-gnu/libpthread.so.0

Thread 4 (Thread 0x7ffff4c59700 (LWP 6165)):
#0  0x00007ffff74b4414 in pthread_mutex_lock ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00000000005b966a in cCSLock::cCSLock(cCriticalSection&) ()
#2  0x00000000006a0bf8 in cMojangAPI::AddPlayerProfile(std::string const&, std::string const&, Json::Value const&) ()
#3  0x000000000069b012 in cAuthenticator::AuthWithYggdrasil(std::string&, std::string const&, std::string&, Json::Value&) ()
#4  0x000000000069a5c9 in cAuthenticator::Execute() ()
#5  0x00007ffff71e5e40 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff74b2182 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007ffff6c4c47d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7ffff6b51700 (LWP 6163)):
#0  0x00007ffff6c46859 in syscall () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000000000950148 in epoll_dispatch ()
#2  0x0000000000945724 in event_base_loop ()
#3  0x00007ffff71e5e40 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff74b2182 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007ffff6c4c47d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7ffff7fc5780 (LWP 6162)):
#0  0x00007ffff74b366b in pthread_join ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff71e5d87 in std::thread::join() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000005ba95e in cIsThread::Wait() ()
#3  0x0000000000578cda in cRoot::Start(std::unique_ptr<cSettingsRepositoryInterface, std::default_delete<cSettingsRepositoryInterface> >) ()
#4  0x00000000005ab00d in universalMain(std::unique_ptr<cSettingsRepositoryInterface, std::default_delete<cSettingsRepositoryInterface> >) ()
#5  0x00000000005ada84 in main ()
```

### PR DESCRIPTION
**Pull request by tigerw**
Restarts are now an actual, close-as-possible to application exit+reopen.

Fixes #2232
Fixes #2094

### CODE REVIEW

File: src/OSSupport/NetworkSingleton.cpp [hunk 1]
```diff
@@ -18,8 +18,27 @@
 
 
 
-cNetworkSingleton::cNetworkSingleton(void):
-	m_HasTerminated(false)
+cNetworkSingleton::~cNetworkSingleton()
+{
+	// Check that Terminate has been called already:
+	ASSERT(m_HasTerminated);
```
Comment (SphinxC0re) [inline src/OSSupport/NetworkSingleton.cpp]: It hasn't been called since there is no instance of cNetworkSingleton yet

File: src/OSSupport/NetworkSingleton.cpp [hunk 2]
```diff
@@ -18,8 +18,27 @@
...
+}
```
Comment (SphinxC0re) [inline src/OSSupport/NetworkSingleton.cpp]: What about the missing constructor here? This will throw a warning of non-initialized variables

File: src/main.cpp [hunk 3]
```diff
@@ -241,10 +234,13 @@ void universalMain(std::unique_ptr<cSettingsRepositoryInterface> overridesRepo)
 	}
 	#endif
 
-	g_ServerTerminated = true;
-
 	// Shutdown all of LibEvent:
 	cNetworkSingleton::Get().Terminate();
+
+	if (cRoot::m_TerminateEventRaised)
```
Comment (worktycho) [inline src/main.cpp]: Under what conditions does this if execute?

File: src/OSSupport/NetworkSingleton.cpp (hunk 2 above)
Comment (SphinxC0re) [inline src/OSSupport/NetworkSingleton.cpp]: Are you relying on LibEvent here?

**Comment by SphinxC0re** [comment]
The server is still saying that it's *shutting down*? Shouldn't it say that it restarts?

File: src/Root.cpp [hunk 4]
```diff
@@ -127,156 +124,190 @@ void cRoot::Start(std::unique_ptr<cSettingsRepositoryInterface> overridesRepo)
...
+				}
+			}
+		};
 
+		// Can't kill the input thread since it breaks cin (getline doesn't block / receive input on restart)
+		// Apparently no way to unblock getline
+		// Only thing I can think of for now
+		if (WriteConsoleInput(GetStdHandle(STD_INPUT_HANDLE), &Record, 1, &Length) == 0)
+		{
+			LOGWARN("Couldn't notify the input thread; the server will hang before shutdown!");
```
Comment (SphinxC0re) [inline src/Root.cpp]: This shouldn't bother the user. Use LOGD();

File: src/Root.cpp [hunk 5]
```diff
@@ -127,156 +124,190 @@ void cRoot::Start(std::unique_ptr<cSettingsRepositoryInterface> overridesRepo)
...
+			m_InputThread.detach();
+		}
+		else
+		{
+			m_InputThread.join();
+		}
+	#else
+		if (pthread_kill(m_InputThread.native_handle(), SIGKILL) != 0)
+		{
+			LOGWARN("Couldn't notify the input thread; the server will hang before shutdown!");
```
Comment (SphinxC0re) [inline src/Root.cpp]: Same here

File: src/Root.cpp [hunk 6]
```diff
@@ -127,156 +124,190 @@ void cRoot::Start(std::unique_ptr<cSettingsRepositoryInterface> overridesRepo)
...
+			m_TerminateEventRaised = true;
+			m_InputThread.detach();
+		}
+	#endif
+
+	LOG("Shutdown successful!");
```
Comment (SphinxC0re) [inline src/Root.cpp]: *Restarting initiated...* ??

File: src/OSSupport/NetworkSingleton.cpp (hunk 2 above)
Comment (SphinxC0re) [inline src/OSSupport/NetworkSingleton.cpp]: You are.. deleting these comments tomorrow....

File: src/Root.cpp [hunk 7]
```diff
@@ -127,156 +124,190 @@ void cRoot::Start(std::unique_ptr<cSettingsRepositoryInterface> overridesRepo)
...
 
-		LOGD("Loading settings...");
-		m_RankManager.reset(new cRankManager());
-		m_RankManager->Initialize(*m_MojangAPI);
-		m_CraftingRecipes = new cCraftingRecipes;
-		m_FurnaceRecipe   = new cFurnaceRecipe();
+	LOGD("Loading settings...");
+	m_RankManager.reset(new cRankManager());
+	m_RankManager->Initialize(*m_MojangAPI);
+	m_CraftingRecipes = new cCraftingRecipes;
```
Comment (SphinxC0re) [inline src/Root.cpp]:
```cpp
m_CraftingRecipes = new cCraftingRecipes();
```

**Comment by madmaxoft** [comment]
I think we're going about this the wrong way.

The way it should work:
1. Main app instantiates a `cRoot` object
2. Main app calls `cRoot::Start()`
3. `cRoot` creates whatever thread it needs for running, and returns from `Start()`
4. Main app takes care of the "input thread" - it reads from stdin or has a GUI frontend that reads input from an edit box, whatever
5. Main app receives a `stop` or `restart` command
6. Main app terminates the `cRoot` instance by calling `cRoot::Stop()`
7. If restarting, the main app start over from 1

This way we could even integrate the server into multiple frontends (such as a windows GUI or an Android app). Think of it as "Cuberite-as-a-library".

**Comment by tigerw** [comment]
Woah, those are a lot of changes...

What way does the main app have to unblock std::getline when a /stop is generated from somewhere other than the console?

**Comment by madmaxoft** [comment]
The point is that the app won't need to use `std::getline()`, it could use any platform-specific way of getting user input, with a platform-specific way of aborting the input once the server wants a restart.

The cRoot object could take a callback parameter which would get called when the root object is requested to terminate from inside (a plugin, for example).

**Comment by tigerw** [comment]
I think what you want is a refactoring of the startup portion of the server, whilst currently I'm focused on fixing the problem of crash on /restart and broken /stop. The exact details of signalling the input aren't too relevant since they'll form a necessary part of whatever is implemented.

Would you prefer an immediate fix such as this merged whilst a refactor postponed as something longer term? I don't have much time to restart this pull request :)

**Comment by madmaxoft** [comment]
Alright, let's get this PR in shape for a merge and refactor later. You still have the others' comments to respond to.

File: src/Root.cpp (hunk 4 above)
Comment (tigerw) [inline src/Root.cpp]: I think this is of sufficient importance to notify the user, since it isn't supposed to happen and could cause confusion since the server won't exit as expected.

Comment (madmaxoft) [inline src/Root.cpp]: I agree that this is important and should be warn-logged

File: src/Root.cpp (hunk 6 above)
Comment (NiLSPACE) [inline src/Root.cpp]: But the server isn't restarting here right?

Comment (SphinxC0re) [inline src/Root.cpp]: It's about the *if* :wink:

**Comment by tigerw** [comment]
Tada?
