### PR TITLE
Damage fishing rod after use

### LINKED ISSUE #4118: Fishing rod does not lose durability
Client version:   1.12.2
Server OS:        Windows
Commit id:        f0b05e78f70fa883bfdc74568bd7bf914025306c

### Expected behavior
Use fishing damages the rod.

### Actual behavior
The rod does not lose durability.

### Steps to reproduce the behavior
As described.

### PR DESCRIPTION
**Pull request by Bond-009**
Fixes #4118

* Damage fishing rod after use
* Give xp to the player for catching something
* Fixed junk drops

### CODE REVIEW

**Comment by bearbin** [comment]
Looks good. Are you also going to implement the LOTS enchantment?

File: src/Items/ItemFishingRod.h [hunk 1]
```diff
@@ -104,22 +104,27 @@ class cItemFishingRodHandler :
...
 				if (ItemCategory <= 4)  // Treasures 5%
 				{
-					int Treasure = Random.RandInt(5);
-					switch (Treasure)
+					switch (Random.RandInt(5))  // Each piece of treasure has an equal chance of 1 / 6
 					{
 						case 0:
 						{
-							Drops.Add(cItem(E_ITEM_BOW));  // TODO: Enchantments
+							cItem Bow = cItem(E_ITEM_BOW, 1, Random.RandInt<short>(50));
```
Comment (peterbell10) [inline src/Items/ItemFishingRod.h]: Why are you constructing the items like this?

File: src/Items/ItemFishingRod.h [hunk 2]
```diff
@@ -143,55 +148,57 @@ class cItemFishingRodHandler :
 				}
 				else if (ItemCategory <= 14)  // Junk 10%
 				{
-					int Junk = Random.RandInt(70);
-					if (Junk <= 1)
+					int Junk = Random.RandInt(82);
+					if (Junk < 10)  // 10 / 83 chance of spawning a bowl
```
Comment (peterbell10) [inline src/Items/ItemFishingRod.h]: This seems ideal for a [`std::discrete_distribution`](http://en.cppreference.com/w/cpp/numeric/random/discrete_distribution).

File: src/Items/ItemFishingRod.h (hunk 1 above)
Comment (Bond-009) [reply src/Items/ItemFishingRod.h]: Is there another/better way to do this?

Comment (peterbell10) [reply src/Items/ItemFishingRod.h]: What's wrong with the normal way?
```cpp
cItem Bow(E_ITEM_BOW, 1, Random.RandInt<short>(50));
```

File: src/Items/ItemFishingRod.h [hunk 3]
```diff
@@ -100,26 +100,37 @@ class cItemFishingRodHandler :
 			}
 			else if (FloaterInfo.CanPickup())
 			{
+				uint LotSLevel = a_Player->GetEquippedItem().m_Enchantments.GetLevel(cEnchantments::enchLuckOfTheSea);
```
Comment (bearbin) [inline src/Items/ItemFishingRod.h]: This breaks the build on windows. It would be better to use a UInt32

Comment (Bond-009) [reply src/Items/ItemFishingRod.h]: Done

File: src/Items/ItemFishingRod.h [hunk 4]
```diff
@@ -100,26 +100,37 @@ class cItemFishingRodHandler :
 			}
 			else if (FloaterInfo.CanPickup())
 			{
+				UInt32 LotSLevel = a_Player->GetEquippedItem().m_Enchantments.GetLevel(cEnchantments::enchLuckOfTheSea);
+
+				// Chances for getting an item from the category for each level of Luck of the Sea (0 - 3)
+				const int TreasureChances[] = {50, 71, 92, 113};  // 5% | 7.1% | 9.2% | 11.3%
+				const int JunkChances[] = {100, 81, 61, 42};  // 10% | 8.1% | 6.1% | 4.2%
```
Comment (peterbell10) [inline src/Items/ItemFishingRod.h]: Potential buffer overrun if a player cheats in a fishing rod with LotS X.

Comment (Bond-009) [reply src/Items/ItemFishingRod.h]: Does the chance for treasure increase when X > 3?

Comment (peterbell10) [reply src/Items/ItemFishingRod.h]: I can't find anything on the wiki.  I'm sure it would be okay to just treat anything >3 the same as level 3 though.

File: src/Items/ItemFishingRod.h [hunk 5]
```diff
@@ -97,29 +97,45 @@ class cItemFishingRodHandler :
 						return true;
 					}
 				);
+				a_Player->UseEquippedItem(5);
 			}
 			else if (FloaterInfo.CanPickup())
 			{
+				UInt32 LotSLevel = a_Player->GetEquippedItem().m_Enchantments.GetLevel(cEnchantments::enchLuckOfTheSea);
```
Comment (bearbin) [inline src/Items/ItemFishingRod.h]: A call to std::min would be more appropriate here.

File: src/Items/ItemFishingRod.h [hunk 6]
```diff
@@ -89,29 +89,41 @@ class cItemFishingRodHandler :
 						return true;
 					}
 				);
+				a_Player->UseEquippedItem(5);
 			}
 			else if (FloaterInfo.CanPickup())
 			{
+				UInt32 LotSLevel = std::min(a_Player->GetEquippedItem().m_Enchantments.GetLevel(cEnchantments::enchLuckOfTheSea), 3);
```
Comment (peterbell10) [inline src/Items/ItemFishingRod.h]: you need to use the unsigned literal `3u` because the lhs of `std::min` is unsigned.
