### PR TITLE
Fix enderchest placement rotation

### LINKED ISSUE #4810: [Bug] Ender chest is first displayed the right way and the flipped by 180 degrees
Client version: 1-8-2
Server OS: Windows
Cuberite Commit id: 46398f4671012a0d913bd7bc0c70ffdc2645f2ac

### Expected behavior
Anderchest is placed facing the player

### Actual behavior
enderchest is placed facing the player but immediatly flipped by 180 degrees to face away from him

### Steps to reproduce the behavior
place ander chest

### PR DESCRIPTION
**Pull request by ion232**
The enderchest didn't have the same type of cYawRotator that a normal chest has. I have tested that this works and the fix produces the correct behaviour.

Fixes #4810

### CODE REVIEW

File: src/Blocks/BlockEnderchest.h [hunk 1]
```diff
@@ -8,9 +8,9 @@
 
 
 class cBlockEnderchestHandler :
-	public cYawRotator<cBlockEntityHandler>
+	public cYawRotator<cContainerEntityHandler<cBlockEntityHandler>, 0x07, 0x03, 0x04, 0x02, 0x05>
```
Comment (peterbell10) [inline src/Blocks/BlockEnderchest.h:11]: As weird as this may sound, Enderchests aren't "Container Entities" because the ender chest inventory is stored in the player and not the chest. The `cYawRotator` fix on its own should be enough.

**Comment by tigerw** [comment]
merge?

**Comment by bearbin** [comment]
@tigerw Once cContainerEntityHandler is removed.
