### PR TITLE
Clamp teleportation position

### LINKED ISSUE #4077: Server crashes if player is far outside the world
Client version:   1.12.2
Server OS:        Linux
Commit id:        ef091fe24b55d48202fd7d376c2e779e3c93a13e

### Expected behavior
Server doesn't crash if a player is located at large coordinates.

### Actual behavior
Server segfaults.
```
[01:05:16] Player Wither_Skeleton has left the game
[01:05:16]   D:    | Cuberite has encountered an error and needs to close
[01:05:16] Details | SIGSEGV: Segmentation fault
[01:05:16] Cuberite Jenkins clang x64 Release (master) build id: #911
[01:05:16] from commit id: ef091fe24b55d48202fd7d376c2e779e3c93a13e built at: Tue 21 Nov 21:55:08 UTC 2017
./Cuberite(_Z15PrintStackTracev+0x19)[0x60fcd9]
./Cuberite[0x5f8935]
/home/serv/server/lib/libc.so.6(+0x352f0)[0x7f0d0264f2f0]
[0x7f0ca400d2e8]
[01:05:16]   D:    | Cuberite has encountered an error and needs to close
[01:05:16] Details | SIGABRT: Server self-terminated due to an internal fault
[01:05:16] Cuberite Jenkins clang x64 Release (master) build id: #911
[01:05:16] from commit id: ef091fe24b55d48202fd7d376c2e779e3c93a13e built at: Tue 21 Nov 21:55:08 UTC 2017
./Cuberite(_Z15PrintStackTracev+0x19)[0x60fcd9]
./Cuberite[0x5f8935]
/home/serv/server/lib/libc.so.6(+0x352f0)[0x7f0d0264f2f0]
/home/serv/server/lib/libc.so.6(gsignal+0x37)[0x7f0d0264f267]
/home/serv/server/lib/libc.so.6(abort+0x16a)[0x7f0d02650eca]
./Cuberite[0x5f893a]
/home/serv/server/lib/libc.so.6(+0x352f0)[0x7f0d0264f2f0]
[0x7f0ca400d2e8]
```

Debug:
```
[45dd7a717fad5b1b|01:11:02] Assertion failed: (a_ChunkX > -0x08000000) && (a_ChunkX < 0x08000000), file /home/jenkins/workspace/cuberite/master/linux-x64/debug/cuberite/src/WorldStorage/WorldStorage.cpp, line 143
./Cuberite(_Z15PrintStackTracev+0x1c)[0xabb6fc]
./Cuberite(_ZN13cWorldStorage14QueueLoadChunkEiiP19cChunkCoordCallback+0x67)[0xdfa227]
./Cuberite(_ZN9cChunkMap8GetChunkEii+0x112)[0x96fea2]
./Cuberite(_ZN9cChunkMap14AddChunkClientEiiP13cClientHandle+0x39)[0x9756b9]
./Cuberite(_ZN6cWorld14AddChunkClientEiiP13cClientHandle+0x3b)[0xa7c0ab]
./Cuberite(_ZN13cClientHandle11StreamChunkEiiN12cChunkSender14eChunkPriorityE+0xd0)[0x993000]
./Cuberite(_ZN13cClientHandle15StreamNextChunkEv+0x8d4)[0x992e54]
./Cuberite(_ZN13cClientHandle10ServerTickEf+0xc8)[0x999ef8]
./Cuberite(_ZN7cServer11TickClientsEf+0x2c1)[0xa3db31]
./Cuberite(_ZN7cServer4TickEf+0x46)[0xa3b596]
./Cuberite(_ZN7cServer11cTickThread7ExecuteEv+0x96)[0xa3b4c6]
./Cuberite(_ZN9cIsThread9DoExecuteEv+0x39)[0xab13d9]
./Cuberite(_ZNKSt7_Mem_fnIM9cIsThreadFvvEEclIJEvEEvPS0_DpOT_+0x72)[0xab2ac2]
./Cuberite(_ZNSt12_Bind_simpleIFSt7_Mem_fnIM9cIsThreadFvvEEPS1_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE+0x42)[0xab2a22]
./Cuberite(_ZNSt12_Bind_simpleIFSt7_Mem_fnIM9cIsThreadFvvEEPS1_EEclEv+0x15)[0xab29d5]
./Cuberite(_ZNSt6thread5_ImplISt12_Bind_simpleIFSt7_Mem_fnIM9cIsThreadFvvEEPS3_EEE6_M_runEv+0x1c)[0xab29ac]
/home/serv/server/lib/libstdc++.so.6(+0xb8ed0)[0x7f908a890ed0]
/home/serv/server/lib/libpthread.so.0(+0x76aa)[0x7f908a3aa6aa]
/home/serv/server/lib/libc.so.6(clone+0x6d)[0x7f908a0dfeed]
Cuberite: /home/jenkins/workspace/cuberite/master/linux-x64/debug/cuberite/src/WorldStorage/WorldStorage.cpp:143: void cWorldStorage::QueueLoadChunk(int, int, cChunkCoordCallback *): Assertion `0' failed.
```

### Steps to reproduce the behavior
Type `/tp 99999999999999999999 99999999999999999999 99999999999999999999` in chat

### PR DESCRIPTION
**Pull request by stone3311**
A large position value would lead to a rounding error in the noise generator which uses float instead of double. A position greater than 0x08000000 * 16 would also lead to a failed assertion in `cWorldStorage::QueueLoadChunk`. The clamping could be done in `cEntity:SetPosition` for extra safety, but that might impact performance. This fixes #4077

### CODE REVIEW

**Comment by bearbin** [comment]
My feeling here would be that simply rejecting a teleport request would be better than clamping the coordinates. I think adding a check in SetPosition as well would be a good idea - just clamping a float is not really the most intensive operation.

File: src/Entities/Player.cpp [hunk 1]
```diff
@@ -1604,12 +1604,18 @@ unsigned int cPlayer::AwardAchievement(const eStatistic a_Ach)
 
 void cPlayer::TeleportToCoords(double a_PosX, double a_PosY, double a_PosZ)
 {
+	// Clamp the positions to exactly representable single-precision floating point values
+	// This is necessary to avoid rounding errors in the noise generator and overflows in the chunk loader
+	const double ClampedPosX = Clamp(a_PosX, -167770000.0, 167770000.0);
+	const double ClampedPosY = Clamp(a_PosY, -167770000.0, 167770000.0);
+	const double ClampedPosZ = Clamp(a_PosZ, -167770000.0, 167770000.0);
```
Comment (bibo38) [inline src/Entities/Player.cpp]: I want at least a constant for these numbers.
If you could represent them with [std::numeric_limits](http://en.cppreference.com/w/cpp/types/numeric_limits), it would be even better :smile: .

P.S.: Maybe also just update the `a_Pos(X|Y|Z)` variables to prevent anyone mixing the clamped and non clamped versions.

File: src/Entities/Player.cpp [hunk 2]
```diff
@@ -1604,12 +1604,18 @@ unsigned int cPlayer::AwardAchievement(const eStatistic a_Ach)
 
 void cPlayer::TeleportToCoords(double a_PosX, double a_PosY, double a_PosZ)
 {
+	// Clamp the positions to exactly representable single-precision floating point values
+	// This is necessary to avoid rounding errors in the noise generator and overflows in the chunk loader
+	const double ClampedPosX = Clamp(a_PosX, -167770000.0, 167770000.0);
+	const double ClampedPosY = Clamp(a_PosY, -167770000.0, 167770000.0);
```
Comment (bibo38) [inline src/Entities/Player.cpp]: This doesn't make that much sense.
You could for example teleport  to y = `-167770000` and then the falling mechanics should get us into bad numbers.
Clamp it to 0 - `MAX_HEIGHT` makes a lot more sense.
