### PR TITLE
Fix instant mining of blocks not being recognised, tweak anti-cheat

### LINKED ISSUE #4757: No item drops with eff V pickaxe
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: 99d96337da2852b3163108334eba84e1ba806cb7

### Expected behavior
Item drops when I break block with eff V diamond pickaxe.

### Actual behavior
Of the blocks I've tested, it seems like sandstone is affected, I should do more testing. The block is destroyed, but no item is produced to be picked up.

### Steps to reproduce the behavior
Mine block

### PR DESCRIPTION
**Pull request by KingCol13**
This fixes #4757, and some of my notes are found there.

The anti-cheat system was in need of some TLC and it seemed semi-empirical so I updated it with the calculation taken from the wiki: https://minecraft.gamepedia.com/Breaking#Speed.

Takes into account player tool, enchantments, status effects and world position when working out if a block is instantly mined (and hence we would not receive a finished digging packet).

### CODE REVIEW

**Comment by KingCol13** [comment]
#2299, #4562 and maybe #2121 are duplicates.

File: src/Entities/Player.cpp [hunk 1]
```diff
@@ -3133,61 +3133,110 @@ bool cPlayer::IsInsideWater()
...
+				MiningSpeed += (EfficiencyModifier * EfficiencyModifier) + 1;
+			}
 		}
 	}
+	else  // If we can't harvest the block then no bonuses
+	{
+		MiningSpeed = 1;
+	}
 
+	// Hase increases speed by 20% per level
```
Comment (peterbell10) [inline src/Entities/Player.cpp:3158]:
```suggestion
	// Haste increases speed by 20% per level
```

File: src/Entities/Player.h [hunk 2]
```diff
@@ -590,11 +590,18 @@ class cPlayer:
...
 	void RemoveClientHandle(void);
 
-	/** Returns the relative block hardness for the block a_Block.
-	The bigger it is the faster the player can break the block.
-	Returns zero if the block is instant breakable.
-	Otherwise it returns the dig speed (float GetDigSpeed(BLOCKTYPE a_Block)) divided by the block hardness (cBlockInfo::GetHardness(BLOCKTYPE a_Block)) divided by 30 if the player can harvest the block and divided by 100 if he can't. */
-	float GetPlayerRelativeBlockHardness(BLOCKTYPE a_Block);
+	/** Returns the progress mined per tick for the block a_Block as a fraction
+	(1 would be completely mined)
+	Returns 0 if it can be instantly mined.
```
Comment (peterbell10) [inline src/Entities/Player.h:595]: Wouldn't returning 1 make more sense?

**Review by peterbell10 — APPROVED** [review]
Tested and it worked well. Couple minor comments.

File: src/Entities/Player.h (hunk 2 above)
Comment (KingCol13) [reply src/Entities/Player.h:595]: It really would, if I had a reason for that inconsistency I've since forgotten, thanks!

File: src/ClientHandle.cpp [hunk 3]
```diff
@@ -1335,10 +1335,10 @@ void cClientHandle::HandleBlockDigFinished(int a_BlockX, int a_BlockY, int a_Blo
...
 	}
 
-	if (!m_Player->IsGameModeCreative() && !cBlockInfo::IsOneHitDig(a_OldBlock))
+	if (!m_Player->IsGameModeCreative() && !m_Player->CanInstantlyMine(a_OldBlock))
 	{
-		// Fix for very fast tools.
-		m_BreakProgress += m_Player->GetPlayerRelativeBlockHardness(a_OldBlock);
+		m_BreakProgress += m_Player->GetMiningProgressPerTick(a_OldBlock);
+		// Check for very fast tools. Maybe instead of FASTBREAK_PERCENTAGE we should check we are within x multiplied by the progress per tick
 		if (m_BreakProgress < FASTBREAK_PERCENTAGE)
```
Comment (KingCol13) [inline src/ClientHandle.cpp:1342]: Any opinions on this? I think checking for x ticks missed feels more natural. Then it is coupled to how fast their mining tool is instead of just an arbitrary leeway

Comment (peterbell10) [reply src/ClientHandle.cpp:1342]: That sounds like a good idea. You'll need to update `FASTBREAK_PERCENTAGE` either way:
https://github.com/cuberite/cuberite/blob/c158569af3f8303c1c2472490cfd2f5a1f599d35/src/Root.cpp#L138-L139

Comment (KingCol13) [reply src/ClientHandle.cpp:1342]: Ah it's off completely, I'm not sure I want to turn it on because some of our block hardness values and CanHarvest etc seem to be wrong and this would cause people to be randomly kicked.

**Comment by KingCol13** [comment]
I think this is ready to merge. @bearbin are you happy with this?

**Review by bearbin — APPROVED** [review]
