### PR TITLE
Fix cPawn push logic

### LINKED ISSUE #2886: Minecarts are too fast, uncontrollable/go crazy
Right now, minecarts will speed up way too fast, even when there absolutely is no energy source used tp sufficiently propelling them forward. All sorts of redstone track parts are ignored by it, and it has strong tendency to fly off the tracks, doing health damage to the player riding it.

### PR DESCRIPTION
**Pull request by marvinkopf**
This adds a boolean IsAttachedTo method to cEntity and cPawn uses it to perform a check before a cPawn instance pushes another entity. fixes #2886

### CODE REVIEW

**Comment by SphinxC0re** [comment]
Does this apply to all entities or just to Minecarts? If it only applies to Minecarts, you should consider moving the code into the Minecart entity handler

**Comment by marvinkopf** [comment]
This applies to boats & minecarts. 

But it's a bug in the Item method in cPawn and got nothing to do with the boat or minecarts class. I changed the title to make a bit more clear.

**Comment by SphinxC0re** [comment]
Yeah since not every entity needs it, that would be good

**Comment by madmaxoft** [comment]
No, keep the attachment methods together in `cEntity`. I like this change, but it still needs a few minor style tweaks.

File: src/Entities/Entity.cpp [hunk 1]
```diff
@@ -1864,6 +1864,20 @@ bool cEntity::IsA(const char * a_ClassName) const
 
 
 
+bool cEntity::IsAttachedTo(const cEntity *a_Entity) const
```
Comment (madmaxoft) [inline src/Entities/Entity.cpp]: Space after `*` as well.

File: src/Entities/Entity.cpp [hunk 2]
```diff
@@ -1864,6 +1864,20 @@ bool cEntity::IsA(const char * a_ClassName) const
...
+{
+	if ((m_Attachee != NULL) &&
```
Comment (madmaxoft) [inline src/Entities/Entity.cpp]: Move the condition to a separate line; don't use `NULL`, use `nullptr` instead.

File: src/Entities/Pawn.cpp [hunk 3]
```diff
@@ -73,6 +73,11 @@ void cPawn::Tick(std::chrono::milliseconds a_Dt, cChunk & a_Chunk)
 				return false;
 			}
 
+			if (a_Entity->IsAttachedTo(m_Pusher))
```
Comment (madmaxoft) [inline src/Entities/Pawn.cpp]: Add a comment about what's going on.

**Comment by marvinkopf** [comment]
Moved the if condition into one single line, wasn't really that long after all.

**Comment by LogicParrot** [comment]
LGTM. @madmaxoft , any more comments?

**Comment by SphinxC0re** [comment]
Rebase and squash the commits onto the current master
