### PR TITLE
Fix TabAutoComplete

### LINKED ISSUE #2747: Chat auto complete -spaced commands duplicating first command when tabbing.
Issue:

When you press tab to auto-complete a multi-spaced command you will get initial command duplicated.

To duplicate this issue:
Cuberite server using Essentials plugin

open chat do "/time "  <-with space
press tab a couple of times and you will start getting "/time /time /time /time"

### PR DESCRIPTION
**Pull request by marvinkopf**
For tab on `/command s` the server now returns `subcommand` instead of `/command subcommand`.

Fixes #2747

### CODE REVIEW

**Comment by SphinxC0re** [comment]
No objections so far. @cuberite/core-team

**Comment by SphinxC0re** [comment]
Oh, btw, shouldn't this loop be refactorable to
```cpp
for(auto command : m_commands)
{
...
}
```
?

**Comment by madmaxoft** [comment]
I'd prefer a solution that was clearer to read. Right now it's a character soup, very difficult to parse for humans.
Add comments as to what it's doing, add temporary variables for the values if it makes it easier to understand the code.

**Comment by marvinkopf** [comment]
Should have been continue if they are not equal. 

The client expects suggestions for the position he is currently at. When the client asks for suggestions for "/time q" the server must skip all commands that consist of more than 2 words just as "/time query daytime". Or in other words, the position of the last space (separator) in the strings must be equal.

**Comment by madmaxoft** [comment]
That's exactly the kind of documentation that's needed there. By all means add the example into the comment to make it absolutely clear (but use `/time set day` command instead :)
Make the comment same-indent-level on all lines.

File: src/Bindings/PluginManager.cpp [hunk 1]
```diff
@@ -1894,7 +1894,27 @@ void cPluginManager::TabCompleteCommand(const AString & a_Text, AStringVector &
...
 			continue;
 		}
-		a_Results.push_back(itr->first);
+
+		/*  Client expects to only get back the last part of a space separated command.
+			Find the position of the beginning of the last part:
+			Position of last space + 1 for space separated commands
+			string::npos + 1 = 0 for commands that are not separated
+
+			Then skipp all commands that have too many subcommands.
```
Comment (LogicParrot) [inline src/Bindings/PluginManager.cpp]: Typo: Should be "skip".

**Comment by LogicParrot** [comment]
```
	/* Client expects to only get back the last part of a space separated command.
	Find the position of the beginning of the last part:
	Position of last space + 1 for space separated commands
	string::npos + 1 = 0 for commands that are not separated

	Then skip all commands that have too many subcommands.
	When the client asks for suggestions for "/time s"
	the server must skip all commands that consist of more than 2 words just as
	"/time set day". Or in other words, the position of the last space (separator)
	in the strings must be equal or string::npos for both. */
```

**Comment by SphinxC0re** [comment]
I would like to see this loop refactored as part of our c++11 conversion

**Comment by LogicParrot** [comment]
I'll include that in a "refactor-spree" PR seperately later, along with lots of similar loop changes in monster code.

**Comment by LogicParrot** [comment]
@marvinkopf thanks :)
