### PR TITLE
End crystal placement

### LINKED ISSUE #5039: End crystals can't be placed
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: a0afd132330ab538848d5ac263c021c1247fd688

### Expected behavior
End crystals should be placeable on bedrock and obsidian

### Actual behavior
End crystals can never be placed on any block

### Steps to reproduce the behavior
1. Spawn an end crystal in creative or create it in survival mode
2. Place an obsidian block and try to put the crystal on top of it

### PR DESCRIPTION
**Pull request by dImrich**
Fixes #5039

### CODE REVIEW

File: src/Items/ItemEndCrystal.h [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+		if (ChunkInterface.GetBlock(a_BlockPos + Vector3i(0, 1, 0)) != 0 ||
+			ChunkInterface.GetBlock(a_BlockPos + Vector3i(0, 2, 0)) != 0)
+		{
+			return false;
+		}
+
+		auto a_BlockType = ChunkInterface.GetBlock(a_BlockPos);
+
+		// When placed on obsidian or bedrock
+		if (a_BlockType == E_BLOCK_OBSIDIAN || a_BlockType == E_BLOCK_BEDROCK)
```
Comment (bearbin) [inline src/Items/ItemEndCrystal.h:49]: Please use the early-return pattern here, like you did earlier with the other checks.

File: src/Items/ItemEndCrystal.h [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+				[&CanBePlaced](cEntity & a_Entity) -> bool
+				{
+					if (a_Entity.IsEnderCrystal())
+					{
+						CanBePlaced = false;
+					}
+
+					return false;
+				}
+			);
```
Comment (bearbin) [inline src/Items/ItemEndCrystal.h:64]: You can use the return value of ForEachEntityInBox here rather than passing in a test variable (also taking advantage of early-termination in the case that an end crystal is found).

```suggestion
			// Check there are no end crystals in bounding box as in vanilla server
			bool CanBePlaced = !a_ChunkMap->ForEachEntityInBox(cBoundingBox(a_BlockPos,Vector3d(a_BlockPos.x + 1.0, a_BlockPos.y + 2.0, a_BlockPos.z + 1.0)),
				[](cEntity & a_Entity) -> bool
				{
					return a_Entity.IsEnderCrystal();
				}
			);
```

**Review by bearbin — CHANGES_REQUESTED** [review]
Looks good in terms of functionality, just a few style points that could be fixed.

File: src/Items/ItemEndCrystal.h [hunk 3]
```diff
@@ -45,32 +45,34 @@ class cItemEndCrystalHandler : public cItemHandler
...
+				return a_Entity.IsEnderCrystal();
+			}
+		);
 
-				if (!a_Player->IsGameModeCreative())
-				{
-					// Remove one ender crystal from player's inventory
-					a_Player->GetInventory().RemoveOneEquippedItem();
-				}
+		if (CanBePlaced)
```
Comment (bearbin) [inline src/Items/ItemEndCrystal.h:62]: Could have returned early here as well, but not essential, as indentation is not too excessive.

**Review by bearbin — APPROVED** [review]

File: src/Items/ItemEndCrystal.h [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+		{
+			return false;
+		}
+
+		auto * a_ChunkMap = a_World->GetChunkMap();
+
+		cChunkInterface ChunkInterface(a_ChunkMap);
+
+		// Don't place if two blocks above placement block aren't air
+		if (ChunkInterface.GetBlock(a_BlockPos + Vector3i(0, 1, 0)) != 0 ||
```
Comment (mathiascode) [inline src/Items/ItemEndCrystal.h:40]: You could use the E_BLOCK_AIR constant here.

File: src/Items/ItemEndCrystal.h [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+		auto a_BlockType = ChunkInterface.GetBlock(a_BlockPos);
+
+		// Dont't place if placement block is not obsidian or bedrock
+		if (a_BlockType != E_BLOCK_OBSIDIAN && a_BlockType != E_BLOCK_BEDROCK)
+		{
+			return false;
+		}
+
+		// Checks if there are end crystals in bounding box
+		bool CanBePlaced = !a_ChunkMap->ForEachEntityInBox(cBoundingBox(a_BlockPos,Vector3d(a_BlockPos.x + 1.0, a_BlockPos.y + 2.0, a_BlockPos.z + 1.0)),
```
Comment (bearbin) [inline src/Items/ItemEndCrystal.h:55]:
```suggestion
		bool CanBePlaced = a_ChunkMap->ForEachEntityInBox(cBoundingBox(a_BlockPos,Vector3d(a_BlockPos.x + 1.0, a_BlockPos.y + 2.0, a_BlockPos.z + 1.0)),
```

**Review by bearbin — CHANGES_REQUESTED** [review]
Oops, this was the wrong way around...

**Review by bearbin — APPROVED** [review]

File: src/Items/ItemEndCrystal.h [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+
+
+
+
+class cItemEndCrystalHandler :
+	public cItemHandler
+{
+	using Super = cItemHandler;
+
+  public:
```
Comment (bearbin) [inline src/Items/ItemEndCrystal.h:17]: @tigerw style fail, this shouldn't be indented.

**Comment by bearbin** [comment]
Merging, the remaining builders appear to have gotten stuck, and most of the builds passed.

@dImrich Thanks for this PR, please do continue your work on the project as it's appreciated.

**Comment by dImrich** [comment]
Thanks @tigerw @bearbin.

@bearbin You’re welcome. It was the least I could do.
