### PR TITLE
Death messages for tamed pets and ocelots are now tamable.

### LINKED ISSUE #4952: Ocelots behaving strange
Minecraft Version 1.12.2
Cuberite Commit id: 072f2d74e2a8781ad06aad235520231ec4ada763

- [x] ocelots can't be tamed
- [ ] ocelots don't convert to cats
- [ ] right clicking them feeds them sometimes but always seems to take a fish out of the players inventory but only on the clients side - client server not synced
- [x] breading works

### LINKED ISSUE #5038: Pets should show death message if named with a name tag
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: a0afd132330ab538848d5ac263c021c1247fd688

### Expected behavior
Pets with a custom name given by a name tag should spawn a death message in the chat with that name

### Actual behavior
No chat message is send when a pet with a name tag dies

### Steps to reproduce the behavior
1. Spawn a cat or dog
2. Tame it
3. Spawn a name tag and give it some name
4. Give the name tag to the pet
5. Kill the pet (:cry:)

### PR DESCRIPTION
**Pull request by TheHyper45**
Fixes #5038
Fixes #4952

### CODE REVIEW

File: src/Mobs/Monster.cpp [hunk 1]
```diff
@@ -605,6 +605,15 @@ void cMonster::KilledBy(TakeDamageInfo & a_TDI)
...
 		m_World->BroadcastSoundEffect(m_SoundDeath, GetPosition(), 1.0f, 0.8f);
 	}
+
+	if (IsTame())
+	{
+		if ((m_MobType == mtWolf) || (m_MobType == mtOcelot) || (m_MobType == mtCat) || (m_MobType == mtParrot))
+		{
+			BroadcastDeathMessage(a_TDI);
+		}
+	}
```
Comment (bearbin) [inline src/Mobs/Monster.cpp:615]: This appears to give a death message whenever a tame animal is killed, rather than just when they have a custom name. Is this intentional?

File: CONTRIBUTORS [hunk 2]
```diff
@@ -85,3 +85,4 @@ worktycho
 Xenoxis
 xoft (Mattes Dolak/madmaxoft on GH)
 Yeeeeezus (Donated AlchemistVillage prefabs)
+TheHyper45
```
Comment (bearbin) [inline CONTRIBUTORS:88]: This should be alpha-sorted.

**Comment by DarkoGNU** [comment]
Where can the reason of clang-tidy test failing be found?

File: src/Entities/Entity.cpp [hunk 3]
```diff
@@ -2285,3 +2285,98 @@ void cEntity::BroadcastLeashedMobs()
...
+
+	AString Name = "";
+	if (IsPlayer())
+	{
+		cPlayer * Player = static_cast<cPlayer *>(this);
+		Name = Player->GetName();
+	}
+	else
+	{
+		cMonster * Monster = static_cast<cMonster *>(this);
```
Comment (bearbin) [inline src/Entities/Entity.cpp:2305]: We shouldn't be doing an unsafe cast here - what if somebody calls this with a non-mob entity?

**Review by bearbin — CHANGES_REQUESTED** [review]

File: src/Mobs/Monster.cpp (hunk 1 above)
Comment (TheHyper45) [reply src/Mobs/Monster.cpp:615]: Yes, according to the vanilla Minecraft.

**Comment by bearbin** [comment]
> Where can the reason of clang-tidy test failing be found?

If you Ctrl-F for `error` then you'll be able to find it. But it appears that TheHyper45 already found it :)

File: src/Mobs/Monster.cpp (hunk 1 above)
Comment (bearbin) [reply src/Mobs/Monster.cpp:615]: OK, that's fine then.

File: src/Entities/Entity.cpp (hunk 3 above)
Comment (TheHyper45) [reply src/Entities/Entity.cpp:2305]: This is changed by adding a check to the IsMob method and qutting if the entity is neither a mob nor a player.

File: CONTRIBUTORS (hunk 2 above)
Comment (TheHyper45) [reply CONTRIBUTORS]: This has been fixed.

**Comment by bearbin** [comment]
Clang build is failing, once that is fixed LGTM.

**Review by bearbin — APPROVED** [review]

File: src/Entities/Entity.cpp [hunk 4]
```diff
@@ -2285,3 +2285,103 @@ void cEntity::BroadcastLeashedMobs()
...
+			// Tamed ocelots are really cats in vanilla.
+			if (Monster->IsTame() && (Monster->GetClass() == AString("cOcelot")))
+			{
+				Name = "Cat";
+			}
+			else
+			{
+				Name = Monster->GetClass();
+				Name.erase(Name.begin());  // Erase the 'c' of the class (e.g. "cWitch" -> "Witch")
+			}
```
Comment (12xx12) [inline src/Entities/Entity.cpp:2321]:
```suggestion
	Name = NamespaceSerializer::From(Monster.GetMobType());
```

you need to `#include "WorldStorage/NamespaceSerializer.h`

**Review by 12xx12 — CHANGES_REQUESTED** [review]

File: src/Entities/Entity.cpp (hunk 4 above)
Comment (12xx12) [reply src/Entities/Entity.cpp:2321]: Oh - wait... this will give you the namespaced name. Not the prettified name.

Comment (bearbin) [reply src/Entities/Entity.cpp:2321]: Maybe a TODO to refactor this logic somewhere reusable later on is an alternative solution?

Comment (12xx12) [reply src/Entities/Entity.cpp:2321]: My suggestion would be:

NamespaceSerializer::Prettify() that crates a human-friendly version from the namespaced string:

So `snow_golem` becomes `Snow Golem`

Comment (12xx12) [reply src/Entities/Entity.cpp:2321]: But we can do this later.
@TheHyper45 - your call

Comment (TheHyper45) [reply src/Entities/Entity.cpp:2321]: OK, Let's do it later.

Comment (TheHyper45) [reply src/Entities/Entity.cpp:2321]: OK, I wrote the NamespaceSerializer::Prettify() method but I think I should put it in another pull request.

**Review by 12xx12 — APPROVED** [review]
We can merge this now and you open another PR where you change my suggestion and add the Prettify function
