### PR TITLE
zlib -> libdeflate

### LINKED ISSUE #3605: API: cStringCompression.UncompressStringZLIB with incorrect params crashes the server
Server OS:        Windows
Commit id:        83fa6cb

### Actual behavior
Calling the function with incorrect params crashes the server.

### Steps to reproduce the behavior
Add this code to a plugin and run it:
`cStringCompression.UncompressStringZLIB('upyBepByLnDKZYmmUk', 999999999999)`

### PR DESCRIPTION
**Pull request by tigerw**
+ Use libdeflate
+ Use std::byte
* Fixes #3605

|  | Level | In size/bytes | Calls/second⁻¹ | Out size/bytes | Speed/MiB/s |
|-|-|-|-|-|-|
| zlib | 6 | 64807 | 625.95 | 4815 | 38 |
| **libdeflate** | 6 | 64801 | 1482.10 | 4869 | **91** |

### CODE REVIEW

**Comment by 12xx12** [comment]
Is this compatible with zLib to load maps from vanilla Minecraft?

**Comment by 12xx12** [comment]
I like the NVIDIA style improvement numbers 🙃

**Comment by tigerw** [comment]
Yes, it will be compatible. NVIDIA style? I am not familiar, tell me more

**Comment by 12xx12** [comment]
I'm just making fun of their promises RTX 20... vs RTX 30... promises :D

File: src/StringCompression.cpp [hunk 1]
```diff
@@ -1,242 +1,243 @@
...
+		if (
+			Result::Static Buffer;
+			Algorithm(m_Handle, Input.data(), Input.size(), Buffer.data(), UncompressedSize, nullptr) == libdeflate_result::LIBDEFLATE_SUCCESS
+		)
+		{
+			return { Buffer, UncompressedSize };
+		}
+	}
+	else if (
+		auto Dynamic = std::make_unique<Result::Dynamic::element_type[]>(UncompressedSize);
```
Comment (tigerw) [inline src/StringCompression.cpp:235]: make_unique_for_overwrite

File: src/Bindings/ManualBindings.cpp [hunk 2]
```diff
@@ -239,21 +244,19 @@ static int tolua_CompressStringGZIP(lua_State * tolua_S)
...
 	// Get the params:
-	AString ToCompress;
+	ContiguousByteBuffer ToCompress;
 	S.GetStackValues(1, ToCompress);
 
 	// Compress the string:
-	AString res;
-	CompressStringGZIP(ToCompress.data(), ToCompress.size(), res);
-	S.Push(res);
+	S.Push(Compression::Compressor().CompressGZip(ToCompress).GetView());
```
Comment (tigerw) [inline src/Bindings/ManualBindings.cpp:251]: may throw

File: Tools/ProtoProxy/Connection.cpp [hunk 3]
```diff
@@ -798,10 +798,10 @@ bool cConnection::HandleClientHandshake(void)
 	Packet.WriteVarUTF8String(ServerHost);
 	Packet.WriteBEUInt16(m_Server.GetConnectPort());
 	Packet.WriteVarInt32(NextState);
-	AString Pkt;
+	ContiguousByteBuffer Pkt;
 	Packet.ReadAll(Pkt);
 	cByteBuffer ToServer(512);
-	ToServer.WriteVarUTF8String(Pkt);
+	ToServer.Write(Pkt.data(), Pkt.size());
```
Comment (tigerw) [inline Tools/ProtoProxy/Connection.cpp:804]: different behavior

File: src/ClientHandle.cpp [hunk 4]
```diff
@@ -2114,7 +2114,15 @@ void cClientHandle::Tick(float a_Dt)
...
 
-	ProcessProtocolInOut();
+	try
+	{
+		ProcessProtocolInOut();
+	}
+	catch (const std::exception & Oops)
+	{
+		Kick(Oops.what());
+		return;
```
Comment (tigerw) [inline src/ClientHandle.cpp:2124]: explain why this return is here

File: src/Bindings/ManualBindings.cpp (hunk 2 above)
Comment (tigerw) [reply src/Bindings/ManualBindings.cpp:251]: actually only if memory allocation fails. That should probably fall under a general strategy of memory failures in the API surface/internal code, instead of handling this one specific instance.

**Comment by tigerw** [comment]
Done!

**Review by bearbin — COMMENTED** [review]
At first glance, this generally looks good, save for replacing normal error returns with nasty exceptions, why? I will need to take a more detailed review of this in due course though.

File: src/WorldStorage/SchematicFileSerializer.cpp [hunk 5]
```diff
@@ -7,7 +7,6 @@
```
[the remark this answers is not in the document]
Comment (tigerw) [reply src/WorldStorage/SchematicFileSerializer.cpp:7]: The result buffer returned by the compression routines takes up the return value, so they report failure via exceptions. This also means GZipFile reports failure similarly. Since SchematicFileSerializer makes use of both I wanted to avoid mixing two styles of failure handling code.

File: src/WorldStorage/SchematicFileSerializer.h [hunk 6]
```diff
@@ -26,29 +27,23 @@ class cSchematicFileSerializer
...
 
-	/** Loads an area from a string containing the .schematic file data. Returns true if successful. */
-	static bool LoadFromSchematicString(cBlockArea & a_BlockArea, const AString & a_SchematicData);
+	/** Loads an area from a string containing the .schematic file data. */
+	static void LoadFromSchematicString(cBlockArea & a_BlockArea, ContiguousByteBufferView a_SchematicData);
 
-	/** Saves the area into a .schematic file. Returns true if successful. */
-	static bool SaveToSchematicFile(const cBlockArea & a_BlockArea, const AString & a_FileName);
+	/** Saves the area into a .schematic file. */
+	static void SaveToSchematicFile(const cBlockArea & a_BlockArea, const std::string & a_FileName);
```
[the remark this answers is not in the document]
Comment (tigerw) [reply src/WorldStorage/SchematicFileSerializer.h:37]: This is now caught by ManualBindings_BlockArea, with the added benefit of logging a stack trace and what went wrong.

**Comment by tigerw** [comment]
Thanks, I've addressed some comments

**Comment by tigerw** [comment]
ping

**Comment by bearbin** [comment]
Well, I don't like the exceptions, but this can go in.
