### PR TITLE
Corrected check for level of subcommand and fixed multiple levels not working

### LINKED ISSUE #3759: Subcommands that contains subcommands
I am not sure if something like that make sense.

Example:
Command and sub commands:
`/cmd` - no handler
`/cmd s1` - has a handler
`/cmd s2` - has a handler

Would it make sense if a sub command itself can have another sub command that has a handler?:
`/cmd s1 x` - has a handler

I tested this and the handler for `x` is not reachable, the handler from `s1` will be called instead.

### PR DESCRIPTION
**Pull request by Seadragon91**
Fixes cuberite/WorldEdit#110
Fixes #3759

Now the server will print for command `/brush a`:
`The /brush command doesn't support verb a`
instead of the error that something was gone wrong.

### CODE REVIEW

File: Server/Plugins/InfoReg.lua [hunk 1]
```diff
@@ -59,7 +59,7 @@ local function MultiCommandHandler(a_Split, a_Player, a_CmdString, a_CmdInfo, a_
 	-- A verb was specified, look it up in the subcommands table:
 	local Subcommand = a_CmdInfo.Subcommands[Verb]
 	if (Subcommand == nil) then
-		if (a_Level > 1) then
+		if (a_Level >= 1) then
```
Comment (Seadragon91) [inline Server/Plugins/InfoReg.lua]: I think `a_Level + 1` makes more sense, is better to understand. Also above is used `a_Level + 1`.

**Comment by Seadragon91** [comment]
Fixed multiple level of sub commands not working.
