### PR TITLE
Lilypads can be on top of (frosted) ice

### LINKED ISSUE #4117: lilypad should be able to place on top of ice, but not other blocks
Client version:   1.12.2
Server OS:        Windows
Commit id:        f0b05e78f70fa883bfdc74568bd7bf914025306c

### Expected behavior
Hold lilypad, right click on the top of an ice block, place lilypad on the ice.
Right click on an invalid place, nothing happens

### Actual behavior
Hold lilypad, right click on the top of an ice block, place the lilypad on the ice, then lilypad becomes a pickup instantly.
Right click on an invalid place, place the lilypad, then it becomes a pickup.

### Steps to reproduce the behavior
As described above.

### PR DESCRIPTION
**Pull request by Bond-009**
Fixes #4117

### CODE REVIEW

File: src/Blocks/BlockLilypad.h [hunk 1]
```diff
@@ -35,8 +35,8 @@ class cBlockLilypadHandler :
 		NIBBLETYPE UnderMeta;
 		a_Chunk.GetBlockTypeMeta(a_RelX, a_RelY - 1, a_RelZ, UnderType, UnderMeta);
 		return (
-			((UnderType == E_BLOCK_STATIONARY_WATER) || (UnderType == E_BLOCK_WATER)) &&  // Water is below...
-			(UnderMeta == 0)                                                              // ... and it's a source
+			(((UnderType == E_BLOCK_STATIONARY_WATER) || (UnderType == E_BLOCK_WATER)) && (UnderMeta == 0))  // A water source is below
+			|| (UnderType == E_BLOCK_ICE) || (UnderType == E_BLOCK_FROSTED_ICE)                              // Or (frosted) ice
```
Comment (peterbell10) [inline src/Blocks/BlockLilypad.h]: Style: `||` should be on the previous line.
