### PR TITLE
Revised the explosion-related Lua API and docs.

### LINKED ISSUE #2746: API example seems to be wrong or not updated
The example on http://api-docs.cuberite.org/Writing-a-MCServer-plugin.html with "Final example and conclusion" creating a command that explodes a player doesn't seem to be OK. The function [DoExplosionAt](http://luaapi.cuberite.org/cWorld.html) requires an extra parameter (`userdata` when using the source `esPlugin` as done in the example) that is not set in the example.

### PR DESCRIPTION
**Pull request by madmaxoft**
Unified the various sources of `esXXX` type information.
Fixed wrong datatypes passed into the explosion hooks.
Centralized the explosion-related LuaAPI documentation.
Fixed example Lua plugin calling explosions.
Removed unneeded `cLuaState::Push(void *)`.

Fixes #2746.

### CODE REVIEW

File: src/Bindings/PluginLua.cpp [hunk 1]
```diff
@@ -667,16 +667,15 @@ bool cPluginLua::OnExploded(cWorld & a_World, double a_ExplosionSize, bool a_Can
 	{
 		switch (a_Source)
```
Comment (worktycho) [inline src/Bindings/PluginLua.cpp]: What about esMax?

File: src/Bindings/PluginLua.cpp [hunk 2]
```diff
@@ -703,16 +702,15 @@ bool cPluginLua::OnExploding(cWorld & a_World, double & a_ExplosionSize, bool &
...
+			case esPlugin:        m_LuaState.Call(static_cast<int>(**itr), &a_World, a_ExplosionSize, a_CanCauseFire, a_X, a_Y, a_Z, a_Source,                                                         cLuaState::Return, res, a_CanCauseFire, a_ExplosionSize); break;
+			case esPrimedTNT:     m_LuaState.Call(static_cast<int>(**itr), &a_World, a_ExplosionSize, a_CanCauseFire, a_X, a_Y, a_Z, a_Source, reinterpret_cast<cTNTEntity *>          (a_SourceData), cLuaState::Return, res, a_CanCauseFire, a_ExplosionSize); break;
+			case esWitherBirth:   m_LuaState.Call(static_cast<int>(**itr), &a_World, a_ExplosionSize, a_CanCauseFire, a_X, a_Y, a_Z, a_Source, reinterpret_cast<cMonster *>            (a_SourceData), cLuaState::Return, res, a_CanCauseFire, a_ExplosionSize); break;
+			case esWitherSkull:   m_LuaState.Call(static_cast<int>(**itr), &a_World, a_ExplosionSize, a_CanCauseFire, a_X, a_Y, a_Z, a_Source, reinterpret_cast<cWitherSkullEntity *>  (a_SourceData), cLuaState::Return, res, a_CanCauseFire, a_ExplosionSize); break;
```
Comment (worktycho) [inline src/Bindings/PluginLua.cpp]: Again, you need to handle esMax

**Comment by madmaxoft** [comment]
Done.
