### PR TITLE
Fixed minecraft with chest destruction crash

### LINKED ISSUE #3262: Minecart crashes
Client version:   1.9.4 Optifine
[terminal_output.txt](https://github.com/cuberite/cuberite/files/359705/terminal_output.txt)

```
[15:19:02] Player <MyUserName> has joined the game
[15:24:05]   D:    | Cuberite has encountered an error and needs to close
[15:24:05] Details | SIGSEGV: Segmentation fault
[15:24:05] Cuberite local build build id: Unknown
[15:24:05] from commit id: approx: 443b657b7d887ef443bc0de5472519f782b1cbd2 built at: approx: 2016-07-10 12:44:09 +0200
./Cuberite(_Z15PrintStackTracev+0x27)[0x636b67]
./Cuberite[0x6237e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x35250)[0x7fb88c855250]
./Cuberite(_ZN7cWindow14OwnerDestroyedEv+0x1)[0x8b4831]
./Cuberite(_ZN18cMinecartWithChest9DestroyedEv+0x2b)[0x86f84b]
./Cuberite(_ZN6cChunkD1Ev+0xf9)[0x56a3f9]
./Cuberite(_ZN9cChunkMap18UnloadUnusedChunksEv+0xbb)[0x574ceb]
./Cuberite(_ZN6cWorld4TickENSt6chrono8durationIlSt5ratioILl1ELl1000EEEES4_+0x346)[0x618356]
./Cuberite(_ZN6cWorld11cTickThread7ExecuteEv+0x81)[0x618571]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb9030)[0x7fb88d1c2030]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76aa)[0x7fb88d4926aa]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fb88c92713d]
[15:24:05]   D:    | Cuberite has encountered an error and needs to close
[15:24:05] Details | SIGABRT: Server self-terminated due to an internal fault
[15:24:05] Cuberite local build build id: Unknown
[15:24:05] from commit id: approx: 443b657b7d887ef443bc0de5472519f782b1cbd2 built at: approx: 2016-07-10 12:44:09 +0200
./Cuberite(_Z15PrintStackTracev+0x27)[0x636b67]
./Cuberite[0x6237e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x35250)[0x7fb88c855250]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7fb88c8551c7]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7fb88c856e2a]
./Cuberite[0x6237ea]
/lib/x86_64-linux-gnu/libc.so.6(+0x35250)[0x7fb88c855250]
./Cuberite(_ZN7cWindow14OwnerDestroyedEv+0x1)[0x8b4831]
./Cuberite(_ZN18cMinecartWithChest9DestroyedEv+0x2b)[0x86f84b]
./Cuberite(_ZN6cChunkD1Ev+0xf9)[0x56a3f9]
./Cuberite(_ZN9cChunkMap18UnloadUnusedChunksEv+0xbb)[0x574ceb]
./Cuberite(_ZN6cWorld4TickENSt6chrono8durationIlSt5ratioILl1ELl1000EEEES4_+0x346)[0x618356]
./Cuberite(_ZN6cWorld11cTickThread7ExecuteEv+0x81)[0x618571]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb9030)[0x7fb88d1c2030]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76aa)[0x7fb88d4926aa]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fb88c92713d]
```

Server OS:        Ubuntu 15.10
Commit id:        443b657b7d887ef443bc0de5472519f782b1cbd2
### Expected behavior

Normal gameplay
### Actual behavior

Normal gameplay until segfault on server
### Steps to reproduce the behavior

run the server

### PR DESCRIPTION
**Pull request by LogicParrot**
Closes #3262

### CODE REVIEW

**Comment by LogicParrot** [comment]
I opened the PR too soon, oops.

**Comment by bearbin** [comment]
Is this good to merge? If it fixes the issue, OK from me.

**Comment by LogicParrot** [comment]
@Seadragon91 reported there's a second crash after this fix. I'm investigating this.

**Comment by LogicParrot** [comment]
I managed to both reproduce and fix the second crash.

**Comment by Seadragon91** [comment]
Thanks @LogicParrot :)

**Comment by Seadragon91** [comment]
Tested it and it still crashes the server.
1) Place a minecart with chest
2) Place items in it
3) Destroy it -> crash

**Comment by Seadragon91** [comment]
Backtrace from debug build
```
(gdb) bt
#0  0x00000000008e8ac5 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<int const, unsigned int> > >::construct<std::pair<int const, unsigned int>, std::pair<int const, unsigned int> const&> (this=0x7fffe093e3c8, __p=0x7fffe0bba430, __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/ext/new_allocator.h:120
#1  0x00000000008e8a8d in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<int const, unsigned int> > > >::construct<std::pair<int const, unsigned int>, std::pair<int const, unsigned int> const&> (__a=..., __p=0x7fffe0bba430, __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/alloc_traits.h:455
#2  0x00000000008e8933 in std::_Rb_tree<int, std::pair<int const, unsigned int>, std::_Select1st<std::pair<int const, unsigned int> >, std::less<int>, std::allocator<std::pair<int const, unsigned int> > >::_M_construct_node<std::pair<int const, unsigned int> const&> (
    this=0x7fffe093e3c8, __node=0x7fffe0bba410, __args=...) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_tree.h:539
#3  0x00000000008e8895 in std::_Rb_tree<int, std::pair<int const, unsigned int>, std::_Select1st<std::pair<int const, unsigned int> >, std::less<int>, std::allocator<std::pair<int const, unsigned int> > >::_M_create_node<std::pair<int const, unsigned int> const&> (
    this=0x7fffe093e3c8, __args=...) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_tree.h:556
#4  0x00000000008e8823 in std::_Rb_tree<int, std::pair<int const, unsigned int>, std::_Select1st<std::pair<int const, unsigned int> >, std::less<int>, std::allocator<std::pair<int const, unsigned int> > >::_Alloc_node::operator()<std::pair<int const, unsigned int> const&> (this=0x7fffecff4660, __arg=...) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_tree.h:469
#5  0x00000000008e8774 in std::_Rb_tree<int, std::pair<int const, unsigned int>, std::_Select1st<std::pair<int const, unsigned int> >, std::less<int>, std::allocator<std::pair<int const, unsigned int> > >::_M_clone_node<std::_Rb_tree<int, std::pair<int const, unsigned int>, std::_Select1st<std::pair<int const, unsigned int> >, std::less<int>, std::allocator<std::pair<int const, unsigned int> > >::_Alloc_node> (this=0x7fffe093e3c8, __x=0x40c48348c0b60f01, __node_gen=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_tree.h:579
#6  0x00000000008e85c0 in std::_Rb_tree<int, std::pair<int const, unsigned int>, std::_Select1st<std::pair<int const, unsigned int> >, std::less<int>, std::allocator<std::pair<int const, unsigned int> > >::_M_copy<std::_Rb_tree<int, std::pair<int const, unsigned int>, std::_Select1st<std::pair<int const, unsigned int> >, std::less<int>, std::allocator<std::pair<int const, unsigned int> > >::_Alloc_node> (this=0x7fffe093e3c8, __x=0x40c48348c0b60f01, __p=0x7fffe0902720, __node_gen=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_tree.h:1570
#7  0x00000000008e85fc in std::_Rb_tree<int, std::pair<int const, unsigned int>, std::_Select1st<std::pair<int const, unsigned int> >, std::less<int>, std::allocator<std::pair<int const, unsigned int> > >::_M_copy<std::_Rb_tree<int, std::pair<int const, unsigned int>, std::_Select1st<std::pair<int const, unsigned int> >, std::less<int>, std::allocator<std::pair<int const, unsigned int> > >::_Alloc_node> (this=0x7fffe093e3c8, __x=0x8a5384 <cByteBuffer::ReadBuf(void*, unsigned long)+324>, __p=0x7fffe093e3d0, __node_gen=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_tree.h:1576
#8  0x00000000008e83c0 in std::_Rb_tree<int, std::pair<int const, unsigned int>, std::_Select1st<std::pair<int const, unsigned int> >, std::less<int>, std::allocator<std::pair<int const, unsigned int> > >::_M_copy (this=0x7fffe093e3c8,
    __x=0x8a5384 <cByteBuffer::ReadBuf(void*, unsigned long)+324>, __p=0x7fffe093e3d0) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_tree.h:793
#9  0x00000000008e81c6 in std::_Rb_tree<int, std::pair<int const, unsigned int>, std::_Select1st<std::pair<int const, unsigned int> >, std::less<int>, std::allocator<std::pair<int const, unsigned int> > >::_Rb_tree (this=0x7fffe093e3c8, __x=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_tree.h:829
#10 0x00000000008e811d in std::map<int, unsigned int, std::less<int>, std::allocator<std::pair<int const, unsigned int> > >::map (this=0x7fffe093e3c8, __x=std::map with 3 elements<error reading variable: Cannot access memory at address 0x1c>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_map.h:186
#11 0x00000000008e806d in cEnchantments::cEnchantments (this=0x7fffe093e3c8) at /home/lukas/cpp/cuberite/src/./Mobs/../Enchantments.h:40
#12 0x00000000008e5a92 in cItem::cItem (this=0x7fffe093e3c0) at /home/lukas/cpp/cuberite/src/./Items/../Item.h:35
#13 0x0000000000d151de in cPickup::cPickup (this=0x7fffe093e250, a_PosX=-34.5, a_PosY=64.549999999999997, a_PosZ=87.400000000000006, a_Item=..., IsPlayerCreated=false, a_SpeedX=0.200000003, a_SpeedY=1.79999995, a_SpeedZ=0.159999996)
    at /home/lukas/cpp/cuberite/src/Entities/Pickup.cpp:92
#14 0x00000000009a2d53 in cWorld::SpawnItemPickups (this=0x7ffff53f6010, a_Pickups=..., a_BlockX=-34.5, a_BlockY=64.549999999999997, a_BlockZ=87.400000000000006, a_FlyAwaySpeed=0.040000000000000001, IsPlayerCreated=false) at /home/lukas/cpp/cuberite/src/World.cpp:2171
#15 0x0000000000d0ecf1 in cMinecartWithChest::Destroyed()::$_0::operator()(cWorld&) const (this=0x7fffe082ae48, World=...) at /home/lukas/cpp/cuberite/src/Entities/Minecart.cpp:1220
#16 0x0000000000d0eb22 in std::_Function_handler<void (cWorld&), cMinecartWithChest::Destroyed()::$_0>::_M_invoke(std::_Any_data const&, cWorld&) (__functor=..., __args=...) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1740
#17 0x00000000009ab058 in std::function<void (cWorld&)>::operator()(cWorld&) const (this=0x7fffe082ae48, __args=...) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:2136
#18 0x000000000099f92d in cWorld::TickQueuedTasks (this=0x7ffff53f6010) at /home/lukas/cpp/cuberite/src/World.cpp:1238
#19 0x0000000000990ee9 in cWorld::Tick (this=0x7ffff53f6010, a_Dt=..., a_LastTickDurationMSec=...) at /home/lukas/cpp/cuberite/src/World.cpp:1054
#20 0x0000000000990863 in cWorld::cTickThread::Execute (this=0x7ffff5b70ac0) at /home/lukas/cpp/cuberite/src/World.cpp:111
#21 0x00000000009d0fe7 in cIsThread::DoExecute (this=0x7ffff5b70ac0) at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#22 0x00000000009d194d in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (__f=@0x2e95150: (void (cIsThread::*)(cIsThread * const)) 0x9d0fb0 <cIsThread::DoExecute()>,
    __t=<unknown type in /home/lukas/minecraft/servers/Server/Cuberite_debug, CU 0x48bce4, DIE 0x48ee62>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:235
#23 0x00000000009d18c2 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x2e95150: (void (cIsThread::*)(cIsThread * const)) 0x9d0fb0 <cIsThread::DoExecute()>,
    __args=<unknown type in /home/lukas/minecraft/servers/Server/Cuberite_debug, CU 0x48bce4, DIE 0x48be0d>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:259
#24 0x00000000009d1840 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x2e95150, __args=<unknown type in /home/lukas/minecraft/servers/Server/Cuberite_debug, CU 0x48bce4, DIE 0x49254a>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:613
#25 0x00000000009d17e2 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x2e95148) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1399
#26 0x00000000009d1795 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (this=0x2e95148) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1389
#27 0x00000000009d1559 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x2e95140) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/thread:196
#28 0x00007ffff71e398f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#29 0x00007ffff74b2464 in start_thread (arg=0x7fffecff5700) at pthread_create.c:333
#30 0x00007ffff6c5a30d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

```

**Comment by LogicParrot** [comment]
@Seadragon91 Yes, that is the problem. Fixed in #3336.

File: src/Entities/Minecart.cpp [hunk 1]
```diff
@@ -1206,10 +1206,19 @@ void cMinecartWithChest::OpenNewWindow()
...
+	{
+		GetWindow()->OwnerDestroyed();
+	}
 	cItems Pickups;
 	m_Contents.CopyToItems(Pickups);
-	GetWorld()->SpawnItemPickups(Pickups, GetPosX(), GetPosY() + 1, GetPosZ(), 4);
+
+
+	// This makes the command not execute if the world is in the midst of destruction :)
+	GetWorld()->ScheduleTask(1, [this, &Pickups](cWorld & World)
```
Comment (tigerw) [inline src/Entities/Minecart.cpp]: Some day, some time, we should all step back and wonder what on Earth went wrong with our design to necessitate this...

:/

Comment (LogicParrot) [inline src/Entities/Minecart.cpp]: That's just a "temporary" hotfix :package:

Comment (LogicParrot) [inline src/Entities/Minecart.cpp]: Seriously though, I just hate crashes. Crashfix first, do it right later.

Comment (tigerw) [inline src/Entities/Minecart.cpp]: You are right. Reliability is number 1 priority. But I just can't help but feel that the logic around how this works (esp. cases like shutting down - who accesses what in which destructor for example) is very fuzzy, and that's causing the bugs/crashes.

File: src/Entities/Minecart.cpp [hunk 2]
```diff
@@ -1206,10 +1206,19 @@ void cMinecartWithChest::OpenNewWindow()
 
 void cMinecartWithChest::Destroyed()
 {
-	GetWindow()->OwnerDestroyed();
+	if (GetWindow() != nullptr)
+	{
+		GetWindow()->OwnerDestroyed();
```
Comment (madmaxoft) [inline src/Entities/Minecart.cpp]: This code is not good. If the internal storage for the Window is changed by another thread in between these calls, it will still fail.

You should grab a temp copy:
```cpp
auto window = GetWindow();
if (window != nullptr)
{
  window->OwnerDestroyed();
}
```

Comment (tigerw) [inline src/Entities/Minecart.cpp]: Well, with #3115, that'll never happen :DD

File: src/Entities/Minecart.cpp (hunk 1 above)
Comment (LogicParrot) [inline src/Entities/Minecart.cpp]: I agree.
