### PR TITLE
Fixed race conditions in cClientHandle's State.

### LINKED ISSUE #1895: Server thinks a player is still connected after the connection was dropped/lost
From time to time it occurs that players have a bad connection and it is severed from or by the server. But the server still thinks that player is connected, indefinitely. If there are any checks to see if the client is still responding in time or if it's even there, they don't always work.

That player cannot re-connect and keep playing.
Kicking the player manually isn't possible, either:

```
[12:07:36] Executing console command: "kick Sledgie65"
[12:07:36] LUA: 2 - Plugins/Core/functions.lua:26: attempt to index a nil value players
```

### LINKED ISSUE #2529: Deadlock between LibEvent and world tick thread when player is removed
When a player disconnects, there is a possibility of a deadlock. The LibEvent code is executing a `cClientHandle::SocketClosed` callback which is trying to remove the player from the world, while holding the LibEvent's internal mutex. This requires the world's `cWorld::m_CSClients` mutex for pushing the client to the list of removed clients.
At the same time, the world tick thread holds the `cWorld::m_CSClient` mutex in `cWorld::TickClients` and is trying to send some data to the client, requesting the LibEvent's internal mutex.

Stack traces for the relevant threads:
World tick thread:

```
Cuberite_debug.exe!evthread_win32_lock(unsigned int mode, void * lock_) Line 78
Cuberite_debug.exe!evthreadimpl_lock_lock_(unsigned int mode, void * lock) Line 422
Cuberite_debug.exe!evbuffer_add(evbuffer * buf, const void * data_in, unsigned int datlen) Line 1725
Cuberite_debug.exe!bufferevent_write(bufferevent * bufev, const void * data, unsigned int size) Line 433
Cuberite_debug.exe!cTCPLinkImpl::Send(const void * a_Data, unsigned int a_Length) Line 132
Cuberite_debug.exe!cClientHandle::Tick(float a_Dt) Line 1887
Cuberite_debug.exe!cWorld::TickClients(float a_Dt) Line 1090
Cuberite_debug.exe!cWorld::Tick(std::chrono::duration<__int64,std::ratio<1,1000> > a_Dt, std::chrono::duration<__int64,std::ratio<1,1000> > a_LastTickDurationMSec) Line 888
Cuberite_debug.exe!cWorld::cTickThread::Execute() Line 111
Cuberite_debug.exe!cIsThread::DoExecute() Line 74
```

LibEvent thread:

```
Cuberite_debug.exe!cCSLock::Lock() Line 114
Cuberite_debug.exe!cCSLock::cCSLock(cCriticalSection & a_CS) Line 90
Cuberite_debug.exe!cWorld::RemovePlayer(cPlayer * a_Player, bool a_RemoveFromChunk) Line 2746
Cuberite_debug.exe!cClientHandle::SocketClosed() Line 3001
Cuberite_debug.exe!cClientHandle::OnRemoteClosed() Line 3048
Cuberite_debug.exe!cTCPLinkImpl::EventCallback(bufferevent * a_BufferEvent, short a_What, void * a_Self) Line 265
Cuberite_debug.exe!bufferevent_run_eventcb_(bufferevent * bufev, short what, int options) Line 279
Cuberite_debug.exe!bufferevent_readcb(int fd, short event, void * arg) Line 196
Cuberite_debug.exe!event_persist_closure(event_base * base, event * ev) Line 1533
Cuberite_debug.exe!event_process_active_single_queue(event_base * base, evcallback_list * activeq, int max_to_process, const timeval * endtime) Line 1592
Cuberite_debug.exe!event_process_active(event_base * base) Line 1692
Cuberite_debug.exe!event_base_loop(event_base * base, int flags) Line 1914
Cuberite_debug.exe!cNetworkSingleton::RunEventLoop(cNetworkSingleton * a_Self) Line 156
```

### LINKED ISSUE #2588: Segmentation fault
My server is crashed.

Here is the server folder with:
- core dump
- git
- cuberite

There are all details form my problem and error.
https://onedrive.live.com/redir?resid=67AF8B9B315A5516!36027&authkey=!AN_zhEynt-g4SV4&ithint=file%2ctar

### LINKED ISSUE #2608: Segfault / can't connect because "I am online right now"
If I join and abort it instantly, I can either connect and can't abort, or I can abort and everything is fine. that's what I thought. if I try to connect another time, if showed me I'm already online (that's number two). I thought one time error, tried to kick me and then just closed the server for a moment. kick did not work.
1. experienced once as I was trying to reproduce the original bug. segfault (i have no core dump, sorry) 
2. this one is more difficult. I can't connect because someone with my username is already online (not me). I can't kick this zombie player, he does nothing, the only thing I can do is closing the server and restarting. 

reproducing: it's more or less easy, a high ping is good for reproduction because otherwise you can't have a chance of clicking the abort button. just connect to the server, hit the abort button and repeat that until segfault or webadmin/console says you are online (and you can't reconnect). then ask someone else to test how it reacts ingame.

core dump, command output.... https://qraut.alkaid.uberspace.de/report.tar.gz
output_\* is the output I piped through tee (to get everything, may be useful too)

### LINKED ISSUE #2644: Crash on first connect
Whenever a player connects to my server for the first time, the next player to disconnect causes a crash.
Log example:
[Log1.txt](https://github.com/cuberite/cuberite/files/34659/Log1.txt)
nic9f7l7/Log1.txt?dl=0

Running the server on a Pi B+, if that makes any difference.

### LINKED ISSUE #2682: crash
hello. another crash (not the newest master, but the bug is present in master, i think)

http://minecraft.ninslash.com/crash-2015-11-23.tar.gz 16M contains server dir excluding worlds

### LINKED ISSUE #2835: Segfault cProtocol180::SendChunkData
I get sometimes this segfault on the raspberry pi 2. The memory usage was only around 50 MB. I self compiled the build on the raspberry pi.

```
(gdb) bt
#0  0x00000000 in ?? ()
#1  0x00848784 in cProtocol180::SendChunkData (this=0x712bc3b0, a_ChunkX=2,
    a_ChunkZ=0, a_Serializer=...)
    at /home/lukas/cpp/cuberite/src/Protocol/Protocol18x.cpp:287
#2  0x0085b300 in cProtocolRecognizer::SendChunkData (this=0x6f815ee0,
    a_ChunkX=2, a_ChunkZ=0, a_Serializer=...)
    at /home/lukas/cpp/cuberite/src/Protocol/ProtocolRecognizer.cpp:164
#3  0x00608918 in cClientHandle::SendChunkData (this=0x6f815c40, a_ChunkX=2,
    a_ChunkZ=0, a_Serializer=...)
    at /home/lukas/cpp/cuberite/src/ClientHandle.cpp:2214
#4  0x005f4a70 in cChunkSender::SendChunk (this=0x75525f98, a_ChunkX=2,
    a_ChunkZ=0, a_Clients=std::unordered_set with 1 elements = {...})
    at /home/lukas/cpp/cuberite/src/ChunkSender.cpp:265
#5  0x005f46dc in cChunkSender::Execute (this=0x75525f98)
    at /home/lukas/cpp/cuberite/src/ChunkSender.cpp:209
#6  0x006e2d08 in cIsThread::DoExecute (this=0x75525f98)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#7  0x006e46e0 in std::_Mem_fn<void (cIsThread::*)()>::operator()<, void>(cIsThr                                   ead*) const (this=0x24c1104, __object=0x75525f98)
    at /usr/include/c++/4.9/functional:569
#8  0x006e4610 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThre                                   ad*)>::_M_invoke<0u>(std::_Index_tuple<0u>) (this=0x24c1100)
    at /usr/include/c++/4.9/functional:1700
#9  0x006e44b8 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThre                                   ad*)>::operator()() (this=0x24c1100) at /usr/include/c++/4.9/functional:1688
#10 0x006e442c in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (cIsThr                                   ead::*)()> (cIsThread*)> >::_M_run() (this=0x24c10f4)
```

### LINKED ISSUE #2839: Segfault cTCPLinkImpl::EventCallback
I had yesterday a few segfaults at this position [TCPLinkImpl.cpp:L265](https://github.com/cuberite/cuberite/blob/master/src/OSSupport/TCPLinkImpl.cpp#L265). The windows crashdump that I have, shows that Self was empty.

Tried to reproduce it in a debug build, had no luck so far.

### LINKED ISSUE #2893: Player stays online when pressing cancel while joining
When you join a server, but quickly press cancel the player can stay online. Here is a video:
https://www.youtube.com/watch?v=mxBWZzqAXLg
I'm sorry for the long wait at the player page, I was refreshing, but that wasn't really visible.

### LINKED ISSUE #3182: Investigate cClientHandle related crashes
This is a general issue. 

It appears that almost 100% of the current crashes happen in `cClientHandle` and its surrounding classes such as `cChunkSender`, `cTCPLinkImpl`. I've decided to investigate this and see if I can fix it. Also, I've created a milestone called "[cClientHandle stability](https://github.com/cuberite/cuberite/milestones/cClientHandle%20stability)" which will include all issues related to this.

Fixing this would be a major stability boost.

### LINKED ISSUE #3345: Server crashes on connecting
Client version:  1.9.X
Server OS:        Windows
Commit id:        (6c57cc389cbbd43d40e160db311dc685557c95f7)

I used a headless client named [pycraft](https://github.com/ammaraskar/pyCraft) to test cuberite's stability by connecting the client many times and close the connection immediately.
Tested the client under Linux and it results in the crash from issue #2835.

Currently I have these 2 crashes:

```
>   Cuberite_debug.exe!mtx_do_lock(_Mtx_internal_imp_t *, const xtime *) Zeile 82   C++
    Cuberite_debug.exe!_Mtx_lock(_Mtx_internal_imp_t *) Zeile 187   C++
    Cuberite_debug.exe!std::_Mtx_lockX(_Mtx_internal_imp_t *) Zeile 70  C++
    Cuberite_debug.exe!std::_Mutex_base::lock() Zeile 44    C++
    Cuberite_debug.exe!cCriticalSection::Lock() Zeile 28    C++
    Cuberite_debug.exe!cCSLock::Lock() Zeile 114    C++
    Cuberite_debug.exe!cCSLock::cCSLock(cCriticalSection &) Zeile 90    C++
    Cuberite_debug.exe!cWorld::QueueTask(std::function<void __cdecl(cWorld &)>) Zeile 3508  C++
    Cuberite_debug.exe!cClientHandle::SocketClosed() Zeile 3123 C++
    Cuberite_debug.exe!cClientHandle::OnError(int, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &) Zeile 3189 C++
    Cuberite_debug.exe!cTCPLinkImpl::EventCallback(bufferevent *, short, void *) Zeile 347  C++
    Cuberite_debug.exe!bufferevent_run_eventcb_(bufferevent *, short, int) Zeile 281    C
    Cuberite_debug.exe!bufferevent_readcb(__int64, short, void *) Zeile 220 C
    Cuberite_debug.exe!event_persist_closure(event_base *, event *) Zeile 1577  C
    Cuberite_debug.exe!event_process_active_single_queue(event_base *, evcallback_list *, int, const timeval *) Zeile 1636  C
    Cuberite_debug.exe!event_process_active(event_base *) Zeile 1734    C
    Cuberite_debug.exe!event_base_loop(event_base *, int) Zeile 1957    C
    Cuberite_debug.exe!cNetworkSingleton::RunEventLoop(cNetworkSingleton *) Zeile 160   C++
    [Externer Code] 
    Cuberite_debug.exe!invoke_thread_procedure(unsigned int(*)(void *), void * const) Zeile 92  C++
    Cuberite_debug.exe!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const) Zeile 115    C++
    [Externer Code]
```

```
    ntdll.dll!00007ff8cc5d0886()    Unbekannt
>   Cuberite_debug.exe!evthread_win32_unlock(unsigned int, void *) Zeile 88 C
    Cuberite_debug.exe!evthreadimpl_lock_unlock_(unsigned int, void *) Zeile 458    C
    Cuberite_debug.exe!evbuffer_add(evbuffer *, const void *, unsigned __int64) Zeile 1806  C
    Cuberite_debug.exe!bufferevent_write(bufferevent *, const void *, unsigned __int64) Zeile 433   C
    Cuberite_debug.exe!cTCPLinkImpl::SendRaw(const void *, unsigned __int64) Zeile 482  C++
    Cuberite_debug.exe!cTCPLinkImpl::Send(const void *, unsigned __int64) Zeile 145 C++
    Cuberite_debug.exe!cClientHandle::ServerTick(float) Zeile 2094  C++
    Cuberite_debug.exe!cServer::TickClients(float) Zeile 383    C++
    Cuberite_debug.exe!cServer::Tick(float) Zeile 336   C++
    Cuberite_debug.exe!cServer::cTickThread::Execute() Zeile 114    C++
    Cuberite_debug.exe!cIsThread::DoExecute() Zeile 75  C++
    [Externer Code] 
    Cuberite_debug.exe!invoke_thread_procedure(unsigned int(*)(void *), void * const) Zeile 92  C++
    Cuberite_debug.exe!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const) Zeile 115    C++
    [Externer Code]
```

### LINKED ISSUE #3383: Server crashes on ClientHandle:GetPlayer
Client version:   1.9.4
Server OS:        Linux
Commit id:        (b268db4caae1b5612ae0f3adabf164efc06de368)
### Actual behavior

Looks like the GetPlayer() was nullptr or ClientHandle itself.

Backtrace for every thread:

```
Currently logging to "crash.txt".
Logs will be appended to the log file.
Output is being logged and displayed.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6b72700 (LWP 8163)]
[New Thread 0x7ffff5bf6700 (LWP 8165)]
[New Thread 0x7ffff53f5700 (LWP 8166)]
[New Thread 0x7ffff4bf4700 (LWP 8167)]
[New Thread 0x7fffef7fa700 (LWP 8168)]
[New Thread 0x7fffeeff9700 (LWP 8169)]
[New Thread 0x7fffee7f8700 (LWP 8170)]
[New Thread 0x7fffedff7700 (LWP 8171)]
[New Thread 0x7fffed7f6700 (LWP 8172)]
[New Thread 0x7fffecff5700 (LWP 8173)]

Thread 10 "Cuberite_debug" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffed7f6700 (LWP 8172)]
cClientHandle::GetPlayer (this=0x0) at /home/lukas/cpp/cuberite/src/./Entities/../ClientHandle.h:77
warning: Source file is more recent than executable.
77      cPlayer * GetPlayer(void) { return m_Player; }  // tolua_export
Saved corefile core.8159
  Id   Target Id         Frame 
  1    Thread 0x7ffff7fe8740 (LWP 8159) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7ffff6b72700 (LWP 8163) "Cuberite_debug" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  3    Thread 0x7ffff5bf6700 (LWP 8165) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 0x7ffff53f5700 (LWP 8166) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7ffff4bf4700 (LWP 8167) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 0x7fffef7fa700 (LWP 8168) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7fffeeff9700 (LWP 8169) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  8    Thread 0x7fffee7f8700 (LWP 8170) "Cuberite_debug" std::get<0ul, cChunk*, std::default_delete<cChunk> > (__t=std::tuple containing = {...}) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/tuple:1261
  9    Thread 0x7fffedff7700 (LWP 8171) "Cuberite_debug" 0x00007ffff74bb7ad in nanosleep () at ../sysdeps/unix/syscall-template.S:84
* 10   Thread 0x7fffed7f6700 (LWP 8172) "Cuberite_debug" cClientHandle::GetPlayer (this=0x0) at /home/lukas/cpp/cuberite/src/./Entities/../ClientHandle.h:77
  11   Thread 0x7fffecff5700 (LWP 8173) "Cuberite_debug" 0x00007ffff6c4d07d in read () at ../sysdeps/unix/syscall-template.S:84

Thread 11 (Thread 0x7fffecff5700 (LWP 8173)):
#0  0x00007ffff6c4d07d in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff6be45c8 in _IO_new_file_underflow (fp=0x7ffff6f0e8e0 <_IO_2_1_stdin_>) at fileops.c:592
#2  0x00007ffff6be54be in __GI__IO_default_uflow (fp=0x7ffff6f0e8e0 <_IO_2_1_stdin_>) at genops.c:413
#3  0x00007ffff6be0778 in _IO_getc (fp=0x7ffff6f0e8e0 <_IO_2_1_stdin_>) at getc.c:38
#4  0x00007ffff7212ebd in __gnu_cxx::stdio_sync_filebuf<char, std::char_traits<char> >::underflow() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff71d2889 in std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000000000096a295 in cRoot::InputThread (a_Params=...) at /home/lukas/cpp/cuberite/src/Root.cpp:85
#7  0x00000000009732ea in std::_Bind_simple<void (*(std::reference_wrapper<cRoot>))(cRoot&)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x184d368) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1399
#8  0x0000000000973295 in std::_Bind_simple<void (*(std::reference_wrapper<cRoot>))(cRoot&)>::operator()() (this=0x184d368) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1389
#9  0x0000000000973059 in std::thread::_State_impl<std::_Bind_simple<void (*(std::reference_wrapper<cRoot>))(cRoot&)> >::_M_run() (this=0x184d360) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/thread:196
#10 0x00007ffff71e398f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff74b2444 in start_thread (arg=0x7fffecff5700) at pthread_create.c:333
#12 0x00007ffff6c5a20d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 10 (Thread 0x7fffed7f6700 (LWP 8172)):
#0  cClientHandle::GetPlayer (this=0x0) at /home/lukas/cpp/cuberite/src/./Entities/../ClientHandle.h:77
#1  0x00000000008eb3fd in cClientHandle::SendChat (this=0x0, a_Message=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, a_ChatPrefix=mtCustom, a_AdditionalData=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
) at /home/lukas/cpp/cuberite/src/ClientHandle.cpp:2184
#2  0x0000000000b17108 in cPlayer::SendMessage (this=0x7fffdc037890, a_Message=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
) at /home/lukas/cpp/cuberite/src/Bindings/./../BlockEntities/../Entities/Player.h:248
#3  0x0000000000b03b39 in tolua_AllToLua_cPlayer_SendMessage00 (tolua_S=0x1716420) at /home/lukas/cpp/cuberite/src/Bindings/Bindings.cpp:37557
#4  0x0000000000b047d5 in tolua_AllToLua_cPlayer_SendMessage01 (tolua_S=0x1716420) at /home/lukas/cpp/cuberite/src/Bindings/Bindings.cpp:37801
#5  0x0000000000ed4ca4 in luaD_precall (L=0x1716420, func=0x19a8470, nresults=0) at /home/lukas/cpp/cuberite/lib/lua/src/ldo.c:319
#6  0x0000000000eec2fa in luaV_execute (L=0x1716420, nexeccalls=2) at /home/lukas/cpp/cuberite/lib/lua/src/lvm.c:587
#7  0x0000000000ed5443 in luaD_call (L=0x1716420, func=0x19a83f0, nResults=1) at /home/lukas/cpp/cuberite/lib/lua/src/ldo.c:377
#8  0x0000000000ecf64f in f_call (L=0x1716420, ud=0x7fffed7f47b8) at /home/lukas/cpp/cuberite/lib/lua/src/lapi.c:800
#9  0x0000000000ed43d5 in luaD_rawrunprotected (L=0x1716420, f=0xecf620 <f_call>, ud=0x7fffed7f47b8) at /home/lukas/cpp/cuberite/lib/lua/src/ldo.c:116
#10 0x0000000000ed588a in luaD_pcall (L=0x1716420, func=0xecf620 <f_call>, u=0x7fffed7f47b8, old_top=32, ef=16) at /home/lukas/cpp/cuberite/lib/lua/src/ldo.c:463
#11 0x0000000000ecf5d8 in lua_pcall (L=0x1716420, nargs=1, nresults=1, errfunc=-3) at /home/lukas/cpp/cuberite/lib/lua/src/lapi.c:821
#12 0x0000000000a0224a in cLuaState::CallFunction (this=0x7fffed7f49b0, a_NumResults=1) at /home/lukas/cpp/cuberite/src/Bindings/LuaState.cpp:1473
#13 0x0000000000a3001c in cLuaState::PushCallPop<bool&> (this=0x7fffed7f49b0, args=@0x7fffed7f4b43: false) at /home/lukas/cpp/cuberite/src/./Bindings/LuaState.h:835
#14 0x0000000000a75fcd in cLuaState::PushCallPop<cPlayer*, cLuaState::cRet const&, bool&>(cPlayer*&&, cLuaState::cRet const&, bool&) (this=0x7fffed7f49b0, a_Param=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x5f4a8b, DIE 0x630cfe>, args=@0x7fffed7f4b43: false, args=@0x7fffed7f4b43: false) at /home/lukas/cpp/cuberite/src/./Bindings/LuaState.h:824
#15 0x0000000000a75f4b in cLuaState::Call<cLuaState::cRef, cPlayer*, cLuaState::cRet const&, bool&>(cLuaState::cRef const&, cPlayer*&&, cLuaState::cRet const&, bool&) (this=0x7fffed7f49b0, a_Function=..., args=@0x7fffed7f4b43: false, args=@0x7fffed7f4b43: false, args=@0x7fffed7f4b43: false) at /home/lukas/cpp/cuberite/src/./Bindings/LuaState.h:663
#16 0x0000000000a75e33 in cLuaState::cCallback::Call<cPlayer*, cLuaState::cRet const&, bool&>(cPlayer*&&, cLuaState::cRet const&, bool&) (this=0x17d7d00, args=@0x7fffed7f4b43: false, args=@0x7fffed7f4b43: false, args=@0x7fffed7f4b43: false) at /home/lukas/cpp/cuberite/src/./Bindings/LuaState.h:219
#17 0x0000000000a62837 in cPluginLua::CallSimpleHooks<cPlayer*>(int, cPlayer*&&) (this=0x1579330, a_HookType=33, a_Args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x5f4a8b, DIE 0x6219f5>) at /home/lukas/cpp/cuberite/src/Bindings/./PluginLua.h:200
#18 0x0000000000a5bafc in cPluginLua::OnPlayerJoined (this=0x1579330, a_Player=...) at /home/lukas/cpp/cuberite/src/Bindings/PluginLua.cpp:624
#19 0x0000000000a84d20 in cPluginManager::CallHookPlayerJoined (this=0x1645f10, a_Player=...) at /home/lukas/cpp/cuberite/src/Bindings/PluginManager.cpp:932
#20 0x00000000008e862e in cClientHandle::Authenticate (this=0x7ffff0025660, a_Name=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, a_UUID=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, a_Properties=...) at /home/lukas/cpp/cuberite/src/ClientHandle.cpp:361
#21 0x0000000000982290 in cServer::AuthenticateUser (this=0x1479040, a_ClientID=6, a_Name=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, a_UUID=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, a_Properties=...) at /home/lukas/cpp/cuberite/src/Server.cpp:698
#22 0x000000000096f07a in cRoot::AuthenticateUser (this=0x7fffffffe138, a_ClientID=6, a_Name=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, a_UUID=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, a_Properties=...) at /home/lukas/cpp/cuberite/src/Root.cpp:667
#23 0x0000000000b6f984 in cAuthenticator::Authenticate (this=0x7fffffffe270, a_ClientID=6, a_UserName=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, a_ServerHash=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
) at /home/lukas/cpp/cuberite/src/Protocol/Authenticator.cpp:63
#24 0x00000000008e9f12 in cClientHandle::HandleLogin (this=0x7ffff0025660, a_ProtocolVersion=4, a_Username=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
) at /home/lukas/cpp/cuberite/src/ClientHandle.cpp:680
#25 0x0000000000ba6ede in cProtocol190::HandlePacketLoginStart (this=0x7fffdc030cf0, a_ByteBuffer=...) at /home/lukas/cpp/cuberite/src/Protocol/Protocol19x.cpp:2266
#26 0x0000000000ba68c5 in cProtocol190::HandlePacket (this=0x7fffdc030cf0, a_ByteBuffer=..., a_PacketType=0) at /home/lukas/cpp/cuberite/src/Protocol/Protocol19x.cpp:2044
#27 0x0000000000b97715 in cProtocol190::AddReceivedData (this=0x7fffdc030cf0, a_Data=0x7fffed7f59e8 "\016", a_Size=15) at /home/lukas/cpp/cuberite/src/Protocol/Protocol19x.cpp:1956
#28 0x0000000000b968c4 in cProtocol190::DataReceived (this=0x7fffdc030cf0, a_Data=0x7fffed7f59e8 "\016", a_Size=15) at /home/lukas/cpp/cuberite/src/Protocol/Protocol19x.cpp:176
#29 0x0000000000bb0eee in cProtocolRecognizer::DataReceived (this=0x7ffff0025b20, a_Data=0x7ffff0000a00 "\022", a_Size=34) at /home/lukas/cpp/cuberite/src/Protocol/ProtocolRecognizer.cpp:110
#30 0x00000000008efaff in cClientHandle::ServerTick (this=0x7ffff0025660, a_Dt=56) at /home/lukas/cpp/cuberite/src/ClientHandle.cpp:2080
#31 0x00000000009804d5 in cServer::TickClients (this=0x1479040, a_Dt=56) at /home/lukas/cpp/cuberite/src/Server.cpp:382
#32 0x000000000097e567 in cServer::Tick (this=0x1479040, a_Dt=56) at /home/lukas/cpp/cuberite/src/Server.cpp:334
#33 0x000000000097e422 in cServer::cTickThread::Execute (this=0x14794c0) at /home/lukas/cpp/cuberite/src/Server.cpp:114
#34 0x00000000009dfde7 in cIsThread::DoExecute (this=0x14794c0) at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#35 0x00000000009e074d in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (__f=@0x15abc90: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __t=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x491348>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:235
#36 0x00000000009e06c2 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x15abc90: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x48e2f3>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:259
#37 0x00000000009e0640 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x15abc90, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x494a37>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:613
#38 0x00000000009e05e2 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x15abc88) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1399
#39 0x00000000009e0595 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (this=0x15abc88) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1389
#40 0x00000000009e0359 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x15abc80) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/thread:196
#41 0x00007ffff71e398f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#42 0x00007ffff74b2444 in start_thread (arg=0x7fffed7f6700) at pthread_create.c:333
#43 0x00007ffff6c5a20d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 9 (Thread 0x7fffedff7700 (LWP 8171)):
#0  0x00007ffff74bb7ad in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x000000000090e8a0 in std::this_thread::sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/thread:322
#2  0x000000000090e3f1 in cDeadlockDetect::Execute (this=0x7fffffffdf98) at /home/lukas/cpp/cuberite/src/DeadlockDetect.cpp:90
#3  0x00000000009dfde7 in cIsThread::DoExecute (this=0x7fffffffdf98) at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#4  0x00000000009e074d in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (__f=@0x2e13550: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __t=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x491348>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:235
#5  0x00000000009e06c2 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x2e13550: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x48e2f3>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:259
#6  0x00000000009e0640 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x2e13550, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x494a37>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:613
#7  0x00000000009e05e2 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x2e13548) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1399
#8  0x00000000009e0595 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (this=0x2e13548) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1389
#9  0x00000000009e0359 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x2e13540) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/thread:196
#10 0x00007ffff71e398f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff74b2444 in start_thread (arg=0x7fffedff7700) at pthread_create.c:333
#12 0x00007ffff6c5a20d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 8 (Thread 0x7fffee7f8700 (LWP 8170)):
#0  std::get<0ul, cChunk*, std::default_delete<cChunk> > (__t=std::tuple containing = {...}) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/tuple:1261
#1  0x00000000008d4415 in std::unique_ptr<cChunk, std::default_delete<cChunk> >::get (this=0x2eb79d8) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/unique_ptr.h:305
#2  0x00000000008d4b35 in std::unique_ptr<cChunk, std::default_delete<cChunk> >::operator-> (this=0x2eb79d8) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/unique_ptr.h:299
#3  0x00000000008ced4d in cChunkMap::ForEachEntity (this=0x1b8bb10, a_Callback=warning: RTTI symbol not found for class 'cWorld::TickMobs(std::chrono::duration<long, std::ratio<1l, 1000l> >)::cCallback'
...) at /home/lukas/cpp/cuberite/src/ChunkMap.cpp:1620
#4  0x00000000009adf5f in cWorld::ForEachEntity (this=0x7ffff5bf7010, a_Callback=warning: RTTI symbol not found for class 'cWorld::TickMobs(std::chrono::duration<long, std::ratio<1l, 1000l> >)::cCallback'
...) at /home/lukas/cpp/cuberite/src/World.cpp:3204
#5  0x00000000009ad1e5 in cWorld::TickMobs (this=0x7ffff5bf7010, a_Dt=...) at /home/lukas/cpp/cuberite/src/World.cpp:1197
#6  0x000000000099ef9b in cWorld::Tick (this=0x7ffff5bf7010, a_Dt=..., a_LastTickDurationMSec=...) at /home/lukas/cpp/cuberite/src/World.cpp:1049
#7  0x000000000099e983 in cWorld::cTickThread::Execute (this=0x7ffff6371ac0) at /home/lukas/cpp/cuberite/src/World.cpp:111
#8  0x00000000009dfde7 in cIsThread::DoExecute (this=0x7ffff6371ac0) at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#9  0x00000000009e074d in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (__f=@0x2e9b380: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __t=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x491348>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:235
#10 0x00000000009e06c2 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x2e9b380: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x48e2f3>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:259
#11 0x00000000009e0640 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x2e9b380, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x494a37>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:613
#12 0x00000000009e05e2 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x2e9b378) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1399
#13 0x00000000009e0595 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (this=0x2e9b378) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1389
#14 0x00000000009e0359 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x2e9b370) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/thread:196
#15 0x00007ffff71e398f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007ffff74b2444 in start_thread (arg=0x7fffee7f8700) at pthread_create.c:333
#17 0x00007ffff6c5a20d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 7 (Thread 0x7fffeeff9700 (LWP 8169)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff71de04c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009dd411 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff5c20e40, __lock=..., __p=...) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/condition_variable:99
#3  0x00000000009dd390 in cEvent::Wait (this=0x7ffff5c20e10) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x00000000008da971 in cChunkSender::Execute (this=0x7ffff5bf8cd8) at /home/lukas/cpp/cuberite/src/ChunkSender.cpp:189
#5  0x00000000009dfde7 in cIsThread::DoExecute (this=0x7ffff5bf8cd8) at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009e074d in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (__f=@0x2dd57d0: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __t=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x491348>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:235
#7  0x00000000009e06c2 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x2dd57d0: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x48e2f3>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:259
#8  0x00000000009e0640 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x2dd57d0, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x494a37>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:613
#9  0x00000000009e05e2 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x2dd57c8) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1399
#10 0x00000000009e0595 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (this=0x2dd57c8) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1389
#11 0x00000000009e0359 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x2dd57c0) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/thread:196
#12 0x00007ffff71e398f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff74b2444 in start_thread (arg=0x7fffeeff9700) at pthread_create.c:333
#14 0x00007ffff6c5a20d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7fffef7fa700 (LWP 8168)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff71de04c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009dd411 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff5bf8ad0, __lock=..., __p=...) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/condition_variable:99
#3  0x00000000009dd390 in cEvent::Wait (this=0x7ffff5bf8aa0) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x0000000000bb929b in cChunkGenerator::Execute (this=0x7ffff5bf89b0) at /home/lukas/cpp/cuberite/src/Generating/ChunkGenerator.cpp:218
#5  0x00000000009dfde7 in cIsThread::DoExecute (this=0x7ffff5bf89b0) at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009e074d in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (__f=@0x2dd1d90: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __t=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x491348>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:235
#7  0x00000000009e06c2 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x2dd1d90: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x48e2f3>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:259
#8  0x00000000009e0640 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x2dd1d90, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x494a37>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:613
#9  0x00000000009e05e2 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x2dd1d88) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1399
#10 0x00000000009e0595 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (this=0x2dd1d88) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1389
#11 0x00000000009e0359 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x2dd1d80) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/thread:196
#12 0x00007ffff71e398f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff74b2444 in start_thread (arg=0x7fffef7fa700) at pthread_create.c:333
#14 0x00007ffff6c5a20d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7ffff4bf4700 (LWP 8167)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff71de04c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009dd411 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff5bf88b8, __lock=..., __p=...) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/condition_variable:99
#3  0x00000000009dd390 in cEvent::Wait (this=0x7ffff5bf8888) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x0000000000cc08a5 in cWorldStorage::Execute (this=0x7ffff5bf8588) at /home/lukas/cpp/cuberite/src/WorldStorage/WorldStorage.cpp:207
#5  0x00000000009dfde7 in cIsThread::DoExecute (this=0x7ffff5bf8588) at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009e074d in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (__f=@0x1b8bc20: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __t=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x491348>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:235
#7  0x00000000009e06c2 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x1b8bc20: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x48e2f3>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:259
#8  0x00000000009e0640 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x1b8bc20, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x494a37>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:613
#9  0x00000000009e05e2 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x1b8bc18) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1399
#10 0x00000000009e0595 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (this=0x1b8bc18) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1389
#11 0x00000000009e0359 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x1b8bc10) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/thread:196
#12 0x00007ffff71e398f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff74b2444 in start_thread (arg=0x7ffff4bf4700) at pthread_create.c:333
#14 0x00007ffff6c5a20d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7ffff53f5700 (LWP 8166)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff71de04c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009dd411 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff5c21120, __lock=..., __p=...) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/condition_variable:99
#3  0x00000000009dd390 in cEvent::Wait (this=0x7ffff5c210f0) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x000000000092e79d in cLightingThread::Execute (this=0x7ffff5c20fe8) at /home/lukas/cpp/cuberite/src/LightingThread.cpp:203
#5  0x00000000009dfde7 in cIsThread::DoExecute (this=0x7ffff5c20fe8) at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009e074d in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (__f=@0x1b8b5c0: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __t=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x491348>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:235
#7  0x00000000009e06c2 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x1b8b5c0: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x48e2f3>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:259
#8  0x00000000009e0640 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x1b8b5c0, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x494a37>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:613
#9  0x00000000009e05e2 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x1b8b5b8) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1399
#10 0x00000000009e0595 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (this=0x1b8b5b8) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1389
#11 0x00000000009e0359 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x1b8b5b0) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/thread:196
#12 0x00007ffff71e398f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff74b2444 in start_thread (arg=0x7ffff53f5700) at pthread_create.c:333
#14 0x00007ffff6c5a20d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7ffff5bf6700 (LWP 8165)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff71de04c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009dd411 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7fffffffe3c0, __lock=..., __p=...) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/condition_variable:99
#3  0x00000000009dd390 in cEvent::Wait (this=0x7fffffffe390) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x0000000000b6fbc4 in cAuthenticator::Execute (this=0x7fffffffe270) at /home/lukas/cpp/cuberite/src/Protocol/Authenticator.cpp:106
#5  0x00000000009dfde7 in cIsThread::DoExecute (this=0x7fffffffe270) at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009e074d in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (__f=@0x1b84270: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __t=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x491348>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:235
#7  0x00000000009e06c2 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x1b84270: (void (cIsThread::*)(cIsThread * const)) 0x9dfdb0 <cIsThread::DoExecute()>, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x48e2f3>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:259
#8  0x00000000009e0640 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x1b84270, __args=<unknown type in /home/lukas/minecraft/servers/Server_ddos/Cuberite_debug, CU 0x48e1ca, DIE 0x494a37>) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:613
#9  0x00000000009e05e2 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x1b84268) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1399
#10 0x00000000009e0595 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (this=0x1b84268) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1389
#11 0x00000000009e0359 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x1b84260) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/thread:196
#12 0x00007ffff71e398f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff74b2444 in start_thread (arg=0x7ffff5bf6700) at pthread_create.c:333
#14 0x00007ffff6c5a20d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7ffff6b72700 (LWP 8163)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x0000000000f26547 in epoll_wait (epfd=3, events=0x1477840, maxevents=32, timeout=-1) at /home/lukas/cpp/cuberite/lib/libevent/epoll_sub.c:64
#2  0x0000000000f255b2 in epoll_dispatch (base=0x1477e40, tv=0x0) at /home/lukas/cpp/cuberite/lib/libevent/epoll.c:462
#3  0x0000000000f0e5de in event_base_loop (base=0x1477e40, flags=4) at /home/lukas/cpp/cuberite/lib/libevent/event.c:1943
#4  0x00000000009e0f0f in cNetworkSingleton::RunEventLoop (a_Self=0x1457bc8 <cNetworkSingleton::Get()::Instance>) at /home/lukas/cpp/cuberite/src/OSSupport/NetworkSingleton.cpp:159
#5  0x00000000009e3a02 in std::_Bind_simple<void (*(cNetworkSingleton*))(cNetworkSingleton*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x14752c8) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1399
#6  0x00000000009e39b5 in std::_Bind_simple<void (*(cNetworkSingleton*))(cNetworkSingleton*)>::operator()() (this=0x14752c8) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1389
#7  0x00000000009e3779 in std::thread::_State_impl<std::_Bind_simple<void (*(cNetworkSingleton*))(cNetworkSingleton*)> >::_M_run() (this=0x14752c0) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/thread:196
#8  0x00007ffff71e398f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff74b2444 in start_thread (arg=0x7ffff6b72700) at pthread_create.c:333
#10 0x00007ffff6c5a20d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7ffff7fe8740 (LWP 8159)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff71de04c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009dd411 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7fffffffe200, __lock=..., __p=...) at /usr/lib/gcc/x86_64-linux-gnu/6.1.1/../../../../include/c++/6.1.1/condition_variable:99
#3  0x00000000009dd390 in cEvent::Wait (this=0x7fffffffe1d0) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x000000000096b97b in cRoot::Start (this=0x7fffffffe138, a_OverridesRepo=std::unique_ptr<cSettingsRepositoryInterface> containing 0x0) at /home/lukas/cpp/cuberite/src/Root.cpp:227
#5  0x00000000009ccfba in UniversalMain (a_OverridesRepo=std::unique_ptr<cSettingsRepositoryInterface> containing 0x0) at /home/lukas/cpp/cuberite/src/main.cpp:231
#6  0x00000000009cb543 in main (argc=1, argv=0x7fffffffe638) at /home/lukas/cpp/cuberite/src/main.cpp:548
A debugging session is active.

    Inferior 1 [process 8159] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]
```

### LINKED ISSUE #3418: Logging a ghost of the user.
Client version:   1.8 liteloader with optifine and an old mod that doesn't work
Server OS:        Linux
Commit id:        (f8f0dc4558a0a60766e8699b1b07dbebeaf5336a)
### Expected behavior

Log me in
### Actual behavior

Logging a ghost of me?
### Steps to reproduce the behavior
connect to a server after and disconnect before connecting.

### PR DESCRIPTION
**Pull request by madmaxoft**
Hopefully this PR should fix all the issues seen lately with `cClientHandle`. There were race conditions that caused keeping the player object in the game after the player has disconnected, and more.

Fixes #3418.
Fixes #3383.
Fixes #3345.
Fixes #3182.
Fixes #2893.
Fixes #2839.
Fixes #2835.
Fixes #2682.
Fixes #2644.
Fixes #2608.
Fixes #2588.
Fixes #2529.
Fixes #1895.

### CODE REVIEW

**Comment by madmaxoft** [comment]
Mostly, the change is about adding a `cCriticalSection` wrapped around `cClientHandle::m_State`, so that each write is protected. If such a write depends on a previous read, the read is included in the CS lock. Still, there are places where the value of `m_State` is not as important (say, when deciding what chunks to send next, it's not exactly important if the client has just disconnected - the chunk will be chosen and then the clienthandle destroyed anyway), so there are places where it makes sense to read the `m_State` value without holding the CS. For that reason, `m_State` is kept as a `std::atomic`.

**Comment by Seadragon91** [comment]
Works fine. Ready for merge?

File: src/ClientHandle.cpp [hunk 1]
```diff
@@ -318,84 +322,100 @@ void cClientHandle::Kick(const AString & a_Reason)
 
 void cClientHandle::Authenticate(const AString & a_Name, const AString & a_UUID, const Json::Value & a_Properties)
 {
-	if (m_State != csAuthenticating)
+	cWorld * World;
 	{
```
Comment (sphinxc0re) [inline src/ClientHandle.cpp]: Why is this scope here? Does it do anything?

Comment (madmaxoft) [inline src/ClientHandle.cpp]: It limits the `lock(m_CSState)`  on the next line only to lock within this scope, rather than till the function end. Specifically, I want to avoid calling plugins (line 433) with this lock held as much as possible.

Comment (sphinxc0re) [inline src/ClientHandle.cpp]: Ah, I didn't know cpp had scope detetection

**Comment by sphinxc0re** [comment]
Looks good to me

**Comment by tigerw** [comment]
It is, of course, my duty to inform you of both #3115 and the available evidence suggesting that multithreaded access is rarely conducive to a clean and verifiably bug-free codebase.

But yeah, if it closes so many issues, why not? (are you sure they're *all* to do with the client handle? We shouldn't accidentally bury an unrelated bug)

File: src/ClientHandle.cpp (hunk 1 above)
Comment (madmaxoft) [inline src/ClientHandle.cpp]: It's simple RAII - acquire resource in constructor, release in destructor. C++ guarantees the destructor to be called upon scope exit.

**Comment by madmaxoft** [comment]
Yeah, 3115 is our Lord Savior, Hallelujah! :D But the same as the Messiah, it's coming in the future and no-one knows when. Not to mention it's a super-complicated change that no-one trusts.

Yes, multi-threading is rarely clean, but it IS needed. And this PR actually cleans it up, since it clearly defines the conditions for how the clienthandle is to be accessed by multiple threads. And yes, it needs to be accessed by multiple threads - we don't want to do world ticking and chunk generating and network manipulation all in the same thread, do we?

Yes, I've manually gone through all the issues and they all can be tracked back to that race condition.

**Comment by madmaxoft** [comment]
@tigerw, are you against a merge, or not?

**Comment by tigerw** [comment]
It's not that I'm hoping for a single thread to do everything, just multiple threads which have obvious places for data input and output, are self-contained, and which do not interfere with each other's state in the middle of their operation.

As they say, if xoft's a dinosaur, then I'm a novice, and novices don't have the experience or ability to trace through the intricacies of complex thread interactions when we want make some protocol change.

Definitely not against a merge. As you say, the other change is coming in the far future. :P

**Comment by tigerw** [comment]
Could you expound a bit on where exactly m_State was being improperly accessed concurrently?

**Comment by madmaxoft** [comment]
It was accessed from both the tick thread and the networking thread.

**Comment by LogicParrot** [comment]
Thanks!

**Comment by LogicParrot** [comment]
>Yes, I've manually gone through all the issues and they all can be tracked back to that race condition.

Could you explain how this fixes #2835? It was really painful to debug and I found nothing.

**Comment by madmaxoft** [comment]
I don't remember all the details anymore, but I know the issue fixed by this PR was about race conditions in `cClientHandle` - the object was being used from multiple threads and it could be used from one thread while another thread was already deleting the object. In the special case of 2835, I suspect that there was a concurrent read / write of the `m_State` member (which is undefined behavior in C++11) which caused one of the reads to report a value that has never been there, thus taking the wrong code path.
