### PR TITLE
Shutdown connection when disconnect packet sent

### LINKED ISSUE #3159: Kick packet, can be ignored from client / Server doesn't close connection, correctly
### Expected behavior

Connection to client should be fully closed, if the player has been kicked / banned from server.
### Actual behavior

Connection is not closed and player is still in the world.
### Steps to reproduce the behavior

Used this [minecraft client python](https://github.com/ammaraskar/pyCraft) to test packets.

### PR DESCRIPTION
**Pull request by bearbin**
Fixes #3159

Tested with a normal client, and it works fine, but no advanced testing undergone.

### CODE REVIEW

**Comment by Seadragon91** [comment]
Tested with pycraft and the client is now kicked. Thanks for the fix.

File: src/ClientHandle.cpp [hunk 1]
```diff
@@ -2515,6 +2521,7 @@ void cClientHandle::SendDisconnect(const AString & a_Reason)
 		LOGD("Sending a DC: \"%s\"", StripColorCodes(a_Reason).c_str());
 		m_Protocol->SendDisconnect(a_Reason);
 		m_HasSentDC = true;
+		m_State = csKicked;
```
Comment (madmaxoft) [inline src/ClientHandle.cpp]: Why not just shutdown the link here? Postponing until the (next) tick seems needless.

Comment (bearbin) [reply src/ClientHandle.cpp]: The server crashes with a segfault if you do that, so I decided it wasn't the best idea.

Comment (madmaxoft) [reply src/ClientHandle.cpp]: That's weird, and it means a race condition is probably present even in your code (although probably hard-to-replicate).
Can you investigate into that segfault a bit?

Comment (bearbin) [reply src/ClientHandle.cpp]: I will try to, if I can replicate it.

Comment (bearbin) [reply src/ClientHandle.cpp]: I found the race condition that was causing the segfault - once the client closed the connection after receiving the DC packet, `Destroy()` was called on the client, which would attempt to `Shutdown()` a `nullptr` `m_Link`.

However, if `m_Link` is shut down immediately after `m_Protocol->SendDisconnect()` is called, the kick message doesn't get through to the player - the connection must end before the data in transit gets through.

Comment (madmaxoft) [reply src/ClientHandle.cpp]: Ah, right, now I remember. The packet sending is done from the client tick thread, so the DC packet is queued here, and then at least one tick is needed for it to be actually sent over the link. So yeah, this code is perfect, then.

Perhaps add a note of this next to this line, so that we know in the future.

**Comment by bearbin** [comment]
The comment is added.

**Comment by madmaxoft** [comment]
Sorry, it's not good enough. It doesn't explain that the packet sending is delayed and the data is actually sent in the Tick thread.

**Comment by bearbin** [comment]
I have changed the comment again for you.
