### PR TITLE
PF - Improved mob jumping

### LINKED ISSUE #2646: Allow mobs to jump down up to 3 or 4 blocks
I have built a few grinders on my skyblock server, but although the mobs spawn normally, they never walk off the edge into the water unless pushed by other mobs.  Spiders are an exception, and seem to walk over the edge almost as the first thing they do after spawning.  I would say that this is an error in the 4 block entity-jump-limit, but mobs that spawn on top of the grinder seem to be more than willing to jump off the top and make feeble attempts at trying to ambush me. :P

### LINKED ISSUE #2787: PF - Mob bugs when going up a block
A mob will ignore the upper green block and manage to get inside the glass structure. I'm reorganizing path.cpp, that should fix this and #2646

### PR DESCRIPTION
**Pull request by SafwatHalaby**
This PR drastically improves mob jumping.
Fixes #2787.
Closes #2646.

Makes the problems discussed in #2771 less severe. Specifically, chickens flight is now better handled, and zombies will not weirdly look back after going down a block.

Mobs no longer act weird when the player jumps.

`StepOnce` is now more readable.

### CODE REVIEW

File: src/Mobs/Path.cpp [hunk 1]
```diff
@@ -57,7 +57,7 @@ cPath::cPath(
 	m_Destination.y = FloorC(a_EndingPoint.y);
 	m_Destination.z = FloorC(a_EndingPoint.z - HalfWidthInt);
 
-	if (GetCell(m_Source)->m_IsSolid || GetCell(m_Destination)->m_IsSolid)
+	if (!IsWalkable(m_Source))
```
Comment (SafwatHalaby) [inline src/Mobs/Path.cpp]: Explanation: The mob should pathfind even if target is not reachable because the pathfinder can pick a nearby spot.

**Comment by worktycho** [comment]
Looks good. Merge if CI.

File: src/Mobs/Path.cpp (hunk 1 above)
Comment (NiLSPACE) [inline src/Mobs/Path.cpp]: Isn't it better to add that in the source?

**Comment by Seadragon91** [comment]
Looks like AppVeyor, has problems.

**Comment by SafwatHalaby** [comment]
Leap of faith. Report of Windows has trouble compiling this (it shouldn't).

File: src/Mobs/Path.cpp (hunk 1 above)
Comment (SafwatHalaby) [inline src/Mobs/Path.cpp]: Mind explaining?

File: src/Mobs/Path.cpp [hunk 2]
```diff
@@ -207,46 +206,103 @@ bool cPath::StepOnce()
...
+	// Now we start checking adjacent cells.
 
-	// Check diagonals on XY plane.
-	// x = -1: west, x = 1: east.
-	for (int x = -1; x <= 1; x += 2)
+
+	bool done_east = false,
+	done_west = false,
+	done_north = false,
+	done_south = false;  // If true, no need to do more checks in that direction
```
Comment (SafwatHalaby) [inline src/Mobs/Path.cpp]: Proper CamelCase needed here. Will do that in my followup PR.
