### PR TITLE
Fix non-fuel items in furnace fuel slot

### LINKED ISSUE #5366: Furnace accepts illegal blocks in fuel slot
Client version: 1.12.x
Server OS: Windows
Cuberite Commit id: 1edc6c8601f9d00751bf7c9f7fcc69d1e18bb46a

### Expected behavior
Being unable to put cobblestone in the fuel slot of the furnace

### Actual behavior
Furnace accepts cobblestone in fuel slot of furnace

### Steps to reproduce the behavior
Place a furnace and put a cobblestone block in fuel slot

### PR DESCRIPTION
**Pull request by KingCol13**
Fixes #5366.

Refactoring into a switch statement may have been a mistake.

### CODE REVIEW

**Review by tigerw — APPROVED** [review]
can't see what changed, i'm sure it works

**Comment by KingCol13** [comment]
Yea I turned the whole `if (a_SlotNum == 2)` block into a switch statement and then the diff got it's knickers in a twist. The new part is the `case 1:  // Fuel slot clicked` bit.

File: src/UI/SlotArea.cpp [hunk 1]
```diff
@@ -1891,114 +1891,130 @@ void cSlotAreaFurnace::Clicked(cPlayer & a_Player, int a_SlotNum, eClickAction a
...
-				MiddleClicked(a_Player, a_SlotNum);
-				return;
-			}
-			case caDropKey:
-			case caCtrlDropKey:
-			{
-				DropClicked(a_Player, a_SlotNum, (a_SlotNum == caCtrlDropKey));
-				Slot.m_ItemCount = Slot.m_ItemCount - GetSlot(a_SlotNum, a_Player)->m_ItemCount;
-				HandleSmeltItem(Slot, a_Player);
+				LOGD("Rejecting non fuel item being placed in fuel slot.");
```
Comment (bearbin) [inline src/UI/SlotArea.cpp:1904]: Not sure about this, we don't need to log something that's not a problem.

**Review by bearbin — APPROVED** [review]
