### PR TITLE
Updated cChunk::SetMeta, fixed grass growth

### LINKED ISSUE #2850: Grass spreads underground
This only happens when it's day (not with torches). You can see it happening by executing a simple script like this:
```lua
function OnBlockSpread(...)
	print(...)
end

cPluginManager:AddHook(cPluginManager.HOOK_BLOCK_SPREAD, OnBlockSpread)
```

### PR DESCRIPTION
**Pull request by LogicParrot**
This PR resolves the grass underground spread issue  (#2850), also, it stops leaves decay checks from sending needless packets to the client and needless writing to disk. This is part of the solution for #3110.

Closes #2850.

### CODE REVIEW

File: src/Chunk.h [hunk 1]
```diff
@@ -392,18 +392,37 @@ class cChunk :
 	{
 		return m_ChunkData.GetMeta(a_RelX, a_RelY, a_RelZ);
 	}
-	inline void       SetMeta(int a_RelX, int a_RelY, int a_RelZ, NIBBLETYPE a_Meta)
+	inline void  SetMeta(int a_RelX, int a_RelY, int a_RelZ, NIBBLETYPE a_Meta)
```
Comment (sgtbigman) [inline src/Chunk.h]: With the added `SetMetaQuiet` method, would it be worth having the `SetMeta` method just call `SetMetaQuiet` with the boolean arguments set to `true`?

Comment (LogicParrot) [inline src/Chunk.h]: I've been wondering about this too. My reasoning was that `SetMeta` is a heavily used function, and for the sake of speed, one should skip the two extra ifs of `SetMetaQuiet` when possible. I have no idea if this argument holds in practice.

Comment (LogicParrot) [inline src/Chunk.h]: >With the added SetMetaQuiet method, would it be worth having the SetMeta method just call SetMetaQuiet with the boolean arguments set to true?

- Or, Just add the two extra parameters to the regular `SetMeta` and make them default to true, this eliminates the need for metaQuiet -

Comment (sgtbigman) [inline src/Chunk.h]: Good point. It may not affect speed, but something worth considering.

Comment (sgtbigman) [inline src/Chunk.h]: > -Or, Just add the two extra parameters to the regular SetMeta and make them default to true, this eliminates the need for metaQuiet-

Right, I was thinking of that when I made my original comment. It may be the better route in this case.

Comment (LogicParrot) [inline src/Chunk.h]: I'll do it your way. Readability is preferred, especially if it turns out to be a micro optimization or if compilers optimize this away. If someone comes up with benchmarks in favor of a dedicated function, we'll later just use function overloading instead of a different brand new function. This keeps the Lua Api clean and saves an export of an additional function.

**Comment by LogicParrot** [comment]
Todo update `APIDesc` for cWorld et al.

**Comment by LogicParrot** [comment]
Potential todo: Replace the bools with named consts or with a bitmask to avoid parameter ordering confusion? I got confused myself already.

**Comment by LogicParrot** [comment]
I am hesitant to change the API without consulting @madmaxoft . So, for now, I did not document the new optional parameters at the API.

**Comment by tigerw** [comment]
The client uses this metadata for leaf decay indication in the debug screen. This is a hotfix only.

File: src/Blocks/BlockDirt.h [hunk 2]
```diff
@@ -51,8 +51,8 @@ class cBlockDirtHandler :
 		{
 			BLOCKTYPE above = a_Chunk.GetBlock(a_RelX, a_RelY + 1, a_RelZ);
 
-			// Grass turns back to dirt when the block above is not transparent
-			if (!cBlockInfo::IsTransparent(above))
+			// Grass turns back to dirt when the block above it is not transparent or water
+			if (!cBlockInfo::IsTransparent(above) || IsBlockWater(above))
```
Comment (tigerw) [inline src/Blocks/BlockDirt.h]: hmmm. Should water be considered transparent?

**Comment by LogicParrot** [comment]
@tigerw I could easily send that to the client without marking dirty chunks by modifying a single line. But is it worth the bandwidth?

File: src/Blocks/BlockDirt.h (hunk 2 above)
Comment (SphinxC0re) [inline src/Blocks/BlockDirt.h]: Isn't water already considered transparent? Wow!

File: src/BlockInfo.cpp [hunk 3]
```diff
@@ -250,7 +250,6 @@ void cBlockInfo::Initialize(cBlockInfoArray & a_Info)
 	a_Info[E_BLOCK_REDSTONE_WIRE       ].m_Transparent = true;
 	a_Info[E_BLOCK_SAPLING             ].m_Transparent = true;
 	a_Info[E_BLOCK_SIGN_POST           ].m_Transparent = true;
-	a_Info[E_BLOCK_SNOW                ].m_Transparent = true;
```
Comment (LogicParrot) [inline src/BlockInfo.cpp]: Should snowing destroy grass?

**Comment by Pokechu22** [comment]
@tigerw Actually, the notchian server also doesn't send this data.  For leaf decay, a special "Update but don't tell the client" mode is used.  From `BlockLeaves`:

```java
worldIn.setBlockState(blockpos, iblockstate.withProperty(CHECK_DECAY, Boolean.valueOf(true)), 4);
```

and 

```java
worldIn.setBlockState(pos, state.withProperty(CHECK_DECAY, Boolean.valueOf(false)), 4);
```

Here's the header for `World.setBlockState`:

```java
/**
 * Sets the block state at a given location. Flag 1 will cause a block update. Flag 2 will send the change to
 * clients (you almost always want this). Flag 4 prevents the block from being re-rendered, if this is a client
 * world. Flags can be added together.
 */
public boolean setBlockState(BlockPos pos, IBlockState newState, int flags)
```

Note how flags 1 and 2 are unset (in almost all cases they are set).

**Comment by Pokechu22** [comment]
To clarify, the server doesn't send a block change packet when leaves decay, but if the player relogs then it does send the changed version.

**Comment by LogicParrot** [comment]
@Pokechu22 this is the exact behavior after this PR.

**Comment by tigerw** [comment]
How many of these packets are sent? It seems cleaner to tell clients what's happening, and less clean to add a bunch of fields to SetMeta (:P). I am quite surprised that its allegedly causing so much network utilisation.

File: src/BlockInfo.cpp (hunk 3 above)
Comment (tigerw) [inline src/BlockInfo.cpp]: It shouldn't.

File: src/Blocks/BlockDirt.h (hunk 2 above)
Comment (tigerw) [inline src/Blocks/BlockDirt.h]: w...was that a good wow or a bad wow?

**Comment by LogicParrot** [comment]
Multiple packets per second in a dense forest. Also, completely non dirty chunks are being marked dirty and saved to disk all the time. That is very serious. (They are also kept longer in ram when dirty, and that is very significant, see #3142).

Note that with the idea I had in mind, `SetMeta` flags are general purpose and should be used elsewhere whenever the meta update is not too important. E.g.:
- Pressing a button or opening a chest shouldn't mark the chunk dirty but should send the meta update to the client.
- Some non visually changing block change should save its meta to disk without telling the client.

**Comment by tigerw** [comment]
Even multiple packets per second doesn't sound like much. In any case, why are so many leaves being generated decaying?

**Comment by LogicParrot** [comment]
@tigerw Would you like to revert and discuss this?

**Comment by tigerw** [comment]
Not at all, just asking about the original problem.

**Comment by LogicParrot** [comment]
The original concern was the insanely high amount of dirty chunks on a Raspberry Pi. I found out that leaves and grass were behaving wildly and decided to fix them.

I thought that leaf decay meta updates, as well as many other meta updates (e.g. button pressing) are too unimportant for a disk write and/or a sent packet, so I made those optional at `setMeta`. I thought that perhaps many of code paths could utilize these flags in the future to reduce resource usage.

The immediate benefit is the reduced dirties and packets. I now realize this could have also been achieved by fixing the generator.

File: src/BlockInfo.cpp (hunk 3 above)
Comment (LogicParrot) [inline src/BlockInfo.cpp]: This has created a bug, then.

File: src/Blocks/BlockDirt.h (hunk 2 above)
Comment (LogicParrot) [inline src/Blocks/BlockDirt.h]: I *think* that zombies will not burn when water is above.

**Comment by LogicParrot** [comment]
The original concern was the insanely high amount of dirty chunks on a Raspberry Pi. I found out that leaves and grass were behaving wildly and decided to fix them.

I thought that leaf decay meta updates, as well as many other meta updates (e.g. button pressing, water/lava simulator bookeeping) are too unimportant for a disk write and/or a sent packet, so I made those optional at `setMeta`. I thought that perhaps many of the code paths could utilize these flags in the future to reduce resource usage.

The immediate benefit is the reduced dirties and packets. I now realize this could have also been achieved by fixing the generator.

**Comment by LogicParrot** [comment]
>Even multiple packets per second doesn't sound like much.

I'll show you the log in a moment. You decide.

**Comment by LogicParrot** [comment]
Here's a log of a STATIONARY player. (Only Moved a few meters upon startup, then stopped).
[decay.txt](https://github.com/cuberite/cuberite/files/222361/decay.txt)

**Comment by LogicParrot** [comment]
We've got 610 updates at `22:05:46`. And this is probably not the peak.

**Comment by LogicParrot** [comment]
@tigerw It seems that those flags have little use in any other code path. I think the generator is creating all leaves with the decay flag on, a fix should be easy. I'll fix the generator and revert this, except for the grass changes. 

Also, it seems someone took the leaf update into account in `FastSetBlock` already, but the leaves do not use that function.

**Comment by tigerw** [comment]
SetBlock goes to FastSetBlock. Not sure about SetMeta.

I'm wondering if the generators are creating leaves with metadata zero? There are a lot of "leaf marked as checked" outputs which probably can be set during generation.

**Comment by LogicParrot** [comment]
>SetBlock goes to FastSetBlock. Not sure about SetMeta.

Oh, sorry. I confused metas and blocks. I take the 2nd paragraph of my last comment back.

>I'm wondering if the generators are creating leaves with metadata zero?

Apparently so. all generaterd leaves can be safely marked as checked on generation.

**Comment by tigerw** [comment]
progress :D

**Comment by LogicParrot** [comment]
So, the plan for handling non important meta updates:
- For leaves: Fix generator to eradicate the updates. 
- For liquid simulators: Useless updates are probably already not sent to the client thanks to code in`setFastBlock`. Modify that code slightly so that it additionally does not call `markDirty` when nothing actually changes.
- For other blocks like buttons: The metas change too rarely to worry about.

It seems that no other use cases require my newly added meta flags, so that's all.

**Comment by tigerw** [comment]
Plan is a good plan.
