### PR TITLE
Preserve banner names across place and pick up

### LINKED ISSUE #5564: Banners lose their names after being placed and picked up
Client version: 1.12.2
Server OS: Linux
Cuberite Commit id: a66a67c

### Expected behavior

Banner name should be retained.

### Actual behavior

Banner name is gone.

### Steps to reproduce the behavior

Name a banner on an anvil. Place it down. Pick it up. Bang! And the name is gone!

### PR DESCRIPTION
**Pull request by mjagdis**
As with named enchanting tables, copy banner names back and forth between items and block entities. NBT format verified against actual Java Edition chunk saves.

Fixes #5564

### CODE REVIEW

File: src/BlockEntities/BannerEntity.h [hunk 1]
```diff
@@ -25,16 +25,20 @@ class cBannerEntity :
 
 public:
 
-	cBannerEntity(BLOCKTYPE a_BlockType, NIBBLETYPE a_BlockMeta, Vector3i a_Pos, cWorld * a_World);
-	cBannerEntity(BLOCKTYPE a_BlockType, NIBBLETYPE a_BlockMeta, Vector3i a_Pos, cWorld * a_World, unsigned char a_BaseColor);
+	cBannerEntity(BLOCKTYPE a_BlockType, NIBBLETYPE a_BlockMeta, Vector3i a_Pos, cWorld * a_World, unsigned char a_BaseColor = 15, AString a_CustomName = "");
```
Comment (bearbin) [inline src/BlockEntities/BannerEntity.h:28]: Previously the default BaseColor was 1, now it's 15?

Comment (mjagdis) [reply src/BlockEntities/BannerEntity.h:28]: It's a bit pedantic, I guess :-). Banner colours are inverted 0-15 so 15 is white (0 is black and 1 is just somewhat random). That said crafting a banner always sets damage (i.e. colour) on the crafted item, loading by WSSAnvil always sets the colour to whatever was saved and placing a banner always does a SetBaseColor using the source item's damage. Unless there's a way to magic a banner into existence from Lua (I haven't checked) those two defaulted args have no real purpose and could be vacuumed up?

Comment (bearbin) [inline src/BlockEntities/BannerEntity.h:28]:
```suggestion
	cBannerEntity(BLOCKTYPE a_BlockType, NIBBLETYPE a_BlockMeta, Vector3i a_Pos, cWorld * a_World, unsigned char a_BaseColor = 1, AString a_CustomName = "");
```

They could probably be cleaned up, something for another day though. Let's leave it how it was at the start.

**Review by bearbin — APPROVED** [review]
