### PR TITLE
TNT position fixes

### LINKED ISSUE #2093: Igniting TNT while block above makes the TNT move up
When you ignite a TNT while a block is above, the TNT will jump to the nearest possible place on the Y axis. This is probably caused by an entity collision test for the TNT block

### LINKED ISSUE #4462: TNT misbehaving
Client version:  1.12.2
Server OS:        MineOS Turnkey (current)
Commit id:        (Found at the top of the server's console output)

### Expected behavior
TNT explodes in water without causing block destruction and launches the player

### Actual behavior
TNT explodes but causes block destruction

### Steps to reproduce the behavior
make a 3x3 area with water covering the inside, dispense TNT into the inside edges

### PR DESCRIPTION
**Pull request by mathiascode**
- Position offset didn't apply properly to TNT ignited by redstone, and was missing from TNT ignited by fire. Fixes #2093
- In some cases, TNT destroyed blocks despite being in water, due to an offset applied to the explosion position. Fixes #4462
- TNT ignited by fire had incorrect fuse ticks
- Added missing TNT ignition sounds in a few cases

### CODE REVIEW

**Comment by Seadragon91** [comment]
TNT cannon possible? :)

**Comment by mathiascode** [comment]
Yes, once the TNT knockback calculations have been fixed.

File: src/Simulator/IncrementalRedstoneSimulator/TNTHandler.h [hunk 1]
```diff
@@ -39,7 +39,7 @@ class cTNTHandler : public cRedstoneHandler
 		{
 			a_World.BroadcastSoundEffect("entity.tnt.primed", a_Position, 0.5f, 0.6f);
 			a_World.SetBlock(a_Position.x, a_Position.y, a_Position.z, E_BLOCK_AIR, 0);
-			a_World.SpawnPrimedTNT(a_Position + Vector3d(0.5, 0.5, 0.5));  // 80 ticks to boom
+			a_World.SpawnPrimedTNT(Vector3d(a_Position.x + 0.5, a_Position.y + 0.5, a_Position.z + 0.5));  // 80 ticks to boom
```
Comment (bearbin) [inline src/Simulator/IncrementalRedstoneSimulator/TNTHandler.h]: I don't understand the advantage of this change except making the code longer and less clear.

Comment (mathiascode) [reply src/Simulator/IncrementalRedstoneSimulator/TNTHandler.h]: The previous code didn't work, but I suppose
`a_World.SpawnPrimedTNT(Vector3d(a_Position) + Vector3d(0.5, 0.5, 0.5))`
could be used too, if you prefer that?

File: src/BlockEntities/DispenserEntity.cpp [hunk 2]
```diff
@@ -126,6 +126,7 @@ void cDispenserEntity::DropSpenseFromSlot(cChunk & a_Chunk, int a_SlotNum)
 			// Spawn a primed TNT entity, if space allows:
 			if (!cBlockInfo::IsSolid(dispBlock))
 			{
```
[the remark this answers is not in the document]
Comment (mathiascode) [reply src/BlockEntities/DispenserEntity.cpp]: There is no sound for chain reactions.

[the remark this answers is not in the document]
Comment (bearbin) [reply src/BlockEntities/DispenserEntity.cpp]: I still think adding the sound playback into the spawn function would be a good idea, even if it means adding a flag to play the sound or not.

File: src/Simulator/IncrementalRedstoneSimulator/TNTHandler.h (hunk 1 above)
Comment (bearbin) [reply src/Simulator/IncrementalRedstoneSimulator/TNTHandler.h]: Ah, yes a_Position is not a Vector3d to start with. Your working alternative does seem better though.

File: src/BlockEntities/DispenserEntity.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (mathiascode) [reply src/BlockEntities/DispenserEntity.cpp]: Sure, will do.

File: src/Simulator/IncrementalRedstoneSimulator/TNTHandler.h [hunk 3]
```diff
@@ -39,7 +39,7 @@ class cTNTHandler : public cRedstoneHandler
 		{
 			a_World.BroadcastSoundEffect("entity.tnt.primed", a_Position, 0.5f, 0.6f);
 			a_World.SetBlock(a_Position.x, a_Position.y, a_Position.z, E_BLOCK_AIR, 0);
-			a_World.SpawnPrimedTNT(Vector3d(a_Position.x + 0.5, a_Position.y + 0.5, a_Position.z + 0.5));  // 80 ticks to boom
+			a_World.SpawnPrimedTNT(Vector3d(a_Position) + Vector3d(0.5, 0.5, 0.5));  // 80 ticks to boom
```
Comment (bearbin) [inline src/Simulator/IncrementalRedstoneSimulator/TNTHandler.h]: Now you're double-playing the primed sound.

Comment (mathiascode) [reply src/Simulator/IncrementalRedstoneSimulator/TNTHandler.h]: I thought I changed this...

File: src/Simulator/FireSimulator.cpp [hunk 4]
```diff
@@ -385,7 +385,7 @@ void cFireSimulator::RemoveFuelNeighbors(cChunk * a_Chunk, Vector3i a_RelPos)
 		if (BlockType == E_BLOCK_TNT)
 		{
 			neighbor->SetBlock(relPos, E_BLOCK_AIR, 0);
-			m_World.SpawnPrimedTNT(absPos, 0);
+			m_World.SpawnPrimedTNT(Vector3d(absPos.x + 0.5, absPos.y + 0.5, absPos.z + 0.5));  // 80 ticks to boom
```
Comment (bearbin) [inline src/Simulator/FireSimulator.cpp]: This could do with being changed to match the way in TNTHandler.h
