### PR TITLE
Corrected brewingstands and added support for fuel

### LINKED ISSUE #3692: Brewing stand doesn't work
Client version:   1.11
Server OS:        Windows

### Actual behavior
Unusable, get out-of-sync error. I think the cause is the new slot (fuel slot)

Will look into fixing that.

### PR DESCRIPTION
**Pull request by Seadragon91**
Do not merge yet.

Done:
* Added new fuel slot
* Added support for fuel: NBT reading, writing and logic
* Updated slot handling: Disallow placing items into wrong slots
* Completely reworked the slot handling for the brewing stand

Fixes #3692

### CODE REVIEW

File: src/BlockEntities/BrewingstandEntity.h [hunk 1]
```diff
@@ -59,6 +60,8 @@ class cBrewingstandEntity :
 	/** Returns the time that the current items has been brewing, in ticks */
 	short GetTimeBrewed(void) { return m_TimeBrewed; }
 
+	short GetFuel(void) { return m_Fuel; }
```
Comment (Seadragon91) [inline src/BlockEntities/BrewingstandEntity.h]: Missing export to lua and doxy comment.

**Comment by Seadragon91** [comment]
Completely reworked the slot handling for the brewing stand. Didn't got any problems doing testing.

**Comment by Seadragon91** [comment]
There are still a few problems with it. For example:
1) Bottle slot contains a bottle
2) Place clicks on the bottle slot with an item that is invalid

This will result in a out-of-sync. Should this cases also be handled?

**Comment by Seadragon91** [comment]
Handled the case above and now the slot handling should work like in vanilla ... should :)

File: Server/Plugins/APIDump/Classes/BlockEntities.lua [hunk 2]
```diff
@@ -441,6 +441,16 @@ return
...
 			},
+			GetFuel =
+			{
+				Returns =
+				{
+					{
+						Type = "number",
+					},
+				},
+				Notes = "Returns the fuel that is left.",
```
Comment (madmaxoft) [inline Server/Plugins/APIDump/Classes/BlockEntities.lua]: `Returns the amount of fuel left`.

File: src/BlockEntities/BrewingstandEntity.cpp [hunk 3]
```diff
@@ -111,7 +112,27 @@ bool cBrewingstandEntity::Tick(std::chrono::milliseconds a_Dt, cChunk & a_Chunk)
 		Ingredient.m_ItemCount -= 1;
 		m_Contents.SetSlot(bsIngredient, Ingredient);
 
+		// Fuel slot
+		m_Fuel--;
+		if (m_Fuel == 0)
```
Comment (madmaxoft) [inline src/BlockEntities/BrewingstandEntity.cpp]: Shouldn't a `<= 0` check be here, or a `> 0` check for the line above?

File: src/BlockEntities/BrewingstandEntity.cpp [hunk 4]
```diff
@@ -111,7 +112,27 @@ bool cBrewingstandEntity::Tick(std::chrono::milliseconds a_Dt, cChunk & a_Chunk)
...
+		{
+			if (!m_Contents.GetSlot(bsFuel).IsEmpty())
+			{
+				cItem Fuel = m_Contents.GetSlot(bsFuel);
+				Fuel.m_ItemCount -= 1;
+				m_Contents.SetSlot(bsFuel, Fuel);
+				m_Fuel = 20;
```
Comment (madmaxoft) [inline src/BlockEntities/BrewingstandEntity.cpp]: Does each fuel type give the same amount? (I don't know the new game mechanics)

File: src/BlockEntities/BrewingstandEntity.cpp [hunk 5]
```diff
@@ -258,19 +298,10 @@ void cBrewingstandEntity::UpdateProgressBars(bool a_ForceUpdate)
...
-
-
-
-
-
 void cBrewingstandEntity::ContinueBrewing(void)
 {
 	// Continue brewing if number is greater than 0
-	if (m_TimeBrewed > 0)
+	if (m_TimeBrewed > 0 && m_Fuel > 0)
```
Comment (madmaxoft) [inline src/BlockEntities/BrewingstandEntity.cpp]: Parentheses around the comparisons.

File: src/BlockEntities/BrewingstandEntity.h [hunk 6]
```diff
@@ -119,6 +126,9 @@ class cBrewingstandEntity :
 	/** Amount of ticks that the current item has been brewed */
 	short m_TimeBrewed;
 
+	/** The fuel for the brewing stand */
+	short m_Fuel;
```
Comment (madmaxoft) [inline src/BlockEntities/BrewingstandEntity.h]: What's `the fuel`, is it the item being consumed, or some entity? How about renaming to `FuelTicksLeft` (and all the related functions renamed accordingly)?

File: src/BrewingRecipes.h [hunk 7]
```diff
@@ -40,6 +40,9 @@ class cBrewingRecipes
 
 	/** Returns true if the item is a bottle / potion, false if not. */
 	bool IsBottle(const cItem & a_Bottle) const;
+
+	/** Returns true if the item is the fuel, false if not. */
+	bool IsFuel(const cItem & a_Bottle) const;
```
Comment (madmaxoft) [inline src/BrewingRecipes.h]: `a_Bottle`?

File: src/UI/SlotArea.cpp [hunk 8]
```diff
@@ -1975,100 +1975,98 @@ void cSlotAreaBrewingstand::Clicked(cPlayer & a_Player, int a_SlotNum, eClickAct
...
-				case caDblClick:
+				super::ShiftClicked(a_Player, a_SlotNum, Slot);
+				break;
+			}
+			default:
+			{
+				if (!BR->IsFuel(DraggingItem))
 				{
-					DblClicked(a_Player, a_SlotNum);
+					// Deny placing a invalid item into the ingredient slot
```
Comment (madmaxoft) [inline src/UI/SlotArea.cpp]: Isn't this the `fuel` slot?

File: src/UI/SlotArea.cpp [hunk 9]
```diff
@@ -2078,9 +2076,13 @@ void cSlotAreaBrewingstand::Clicked(cPlayer & a_Player, int a_SlotNum, eClickAct
 
 
 
-void cSlotAreaBrewingstand::HandleBrewedItem(cPlayer & a_Player)
+void cSlotAreaBrewingstand::HandleBrewedItem(cPlayer & a_Player, const cItem & a_ClickedItem)
 {
-	a_Player.AwardAchievement(achBrewPotion);
+	// Check if the clicked item has damage value 0 (water bottle)
```
Comment (madmaxoft) [inline src/UI/SlotArea.cpp]: -> `Award an achievement if the item is not a water bottle (is a real brewed potion)`

File: Server/Plugins/APIDump/Classes/BlockEntities.lua (hunk 2 above)
Comment (Pokechu22) [inline Server/Plugins/APIDump/Classes/BlockEntities.lua]: How about `Returns the remaining amount of fuel`?

Comment (madmaxoft) [inline Server/Plugins/APIDump/Classes/BlockEntities.lua]: Okay, and the amount is measured how?

File: src/BlockEntities/BrewingstandEntity.cpp (hunk 4 above)
Comment (Pokechu22) [inline src/BlockEntities/BrewingstandEntity.cpp]: There's only one type of fuel: blaze powder (which always gives the same amount).  Nothing else can be put into the slot.

Comment (Seadragon91) [inline src/BlockEntities/BrewingstandEntity.cpp]: There is only one fuel item `blaze powder` :)

File: src/BlockEntities/BrewingstandEntity.h (hunk 6 above)
Comment (Pokechu22) [inline src/BlockEntities/BrewingstandEntity.h]: Fuel in brewing stands doesn't work by ticks; it's decremented each time brewing starts (but once it starts, the brewing of that batch of potions will continue without decrementing it further).

Comment (madmaxoft) [inline src/BlockEntities/BrewingstandEntity.h]: Okay, but we still need a more descriptive variable name, so that it's clear that it's not the actual item, but some measure of the fuel left. `m_FuelLeft` would be okayish with me, if we can't think of anything better.

Comment (madmaxoft) [inline src/BlockEntities/BrewingstandEntity.h]: (and with @Pokechu22 's description in the doxy-comment and somewhere in the APIDoc)

Comment (Seadragon91) [inline src/BlockEntities/BrewingstandEntity.h]: The fuel means how many brewing operations can be done.
I would say new name `FuelRemaining` and the doxy comment, to:
`Amount of brewing operations that can be done with the remaining fuel.`

Comment (madmaxoft) [inline src/BlockEntities/BrewingstandEntity.h]: Sounds good. Don't forget to rename the related functions, too.

File: src/BlockEntities/BrewingstandEntity.cpp (hunk 4 above)
Comment (Seadragon91) [inline src/BlockEntities/BrewingstandEntity.cpp]: @Pokechu22 "can be" - we could allow it :), but want vanilla behavior.

File: src/BlockEntities/BrewingstandEntity.h (hunk 6 above)
Comment (Seadragon91) [inline src/BlockEntities/BrewingstandEntity.h]: No auto update in github :(. Only saw your comments after refresh...

File: src/BlockEntities/BrewingstandEntity.cpp (hunk 3 above)
Comment (Seadragon91) [inline src/BlockEntities/BrewingstandEntity.cpp]: Changed to `<= 0`.

File: src/BlockEntities/BrewingstandEntity.cpp (hunk 5 above)
Comment (Seadragon91) [inline src/BlockEntities/BrewingstandEntity.cpp]: Added them, can the style check script not detect this?

File: src/BrewingRecipes.h (hunk 7 above)
Comment (Seadragon91) [inline src/BrewingRecipes.h]: Changed both to `a_Item`, as there are different items passed and then checked there,

File: src/UI/SlotArea.cpp (hunk 9 above)
Comment (Seadragon91) [inline src/UI/SlotArea.cpp]: Changed.

**Comment by Seadragon91** [comment]
Updated and also added missing functions `SetSlotFuel` and `GetSlotFuel`.

**Comment by Seadragon91** [comment]
Should have done a local build, updated old function names to new ones.

File: src/BlockEntities/BrewingstandEntity.cpp (hunk 5 above)
Comment (Seadragon91) [inline src/BlockEntities/BrewingstandEntity.cpp]: Looked into the style check and see why it's not checked.
