### PR TITLE
Cactus cannot be placed on a forbidden blocks

### LINKED ISSUE #4641: Cactus drops when placed on something else than sand or another cactus
Client version: 12.2.2
Server OS: Linux
Cuberite Commit id: 0d722701861ad9acfa7d36c5156fd184e3ba6bee

### Expected behavior
Cactus would just not be placable. Players hand wouldn't even move.

### Actual behavior
The attempt is made to place the cactus and it just drops as a block.
I think this is _kind of_ similar to the issue with dropping levers, buttons, etc. on glass, lilypads, halfslabs, but it might be not, because the other pieces are not solid blocks.

### Steps to reproduce the behavior
Place a cactus e.g. on grass.

### Server log
```
-
```

### PR DESCRIPTION
**Pull request by morsmordere**
A fix for #4641. 
Overrode _GetPlacementBlockTypeMeta_ for CactusBlock, which gets called before a player places the cactus block, so it returns true if the placement is allowed or false if not, in which case the cactus does not drop as a block but stays in the player's hand which is the expected behavior. Tested in Minecraft client 1.12.2.
**Before:**
buggy
**After:**
fixed

### CODE REVIEW

File: src/Blocks/BlockCactus.h [hunk 1]
```diff
@@ -23,6 +23,39 @@ class cBlockCactusHandler :
...
+	bool GetPlacementBlockTypeMeta(
+		cChunkInterface & a_ChunkInterface,
+		cPlayer & a_Player,
+		const Vector3i a_PlacedBlockPos,
+		eBlockFace a_ClickedBlockFace,
+		const Vector3i a_CursorPos,
+		BLOCKTYPE & a_BlockType, NIBBLETYPE & a_BlockMeta
+	) override
+	{
+		if (a_Player.GetWorld()->DoWithChunkAt(a_PlacedBlockPos,
```
Comment (madmaxoft) [inline src/Blocks/BlockCactus.h:37]: Style: When using multi-line `if`, split line after `if(`

File: src/Blocks/BlockCactus.h [hunk 2]
```diff
@@ -23,6 +23,39 @@ class cBlockCactusHandler :
...
+			[this, a_PlacedBlockPos, &a_ChunkInterface](cChunk & a_Chunk)
+			{
+				auto RelPos = cChunkDef::AbsoluteToRelative(a_PlacedBlockPos);
+				return CanBeAt(a_ChunkInterface, RelPos, a_Chunk);
+			}
+			))
```
Comment (madmaxoft) [inline src/Blocks/BlockCactus.h:43]: Style: This should be have one less indent level (so that it's the same level as the `if` the last parenthesis belongs to.)

**Comment by madmaxoft** [comment]
Since you're also first-time contributing to the project, you should add your name to the CONTRIBUTORS file, too.

File: src/Blocks/BlockCactus.h (hunk 1 above)
Comment (morsmordere) [reply src/Blocks/BlockCactus.h]: Hopefully my last commits reflected the changes you wanted.

File: src/Blocks/BlockCactus.h (hunk 2 above)
Comment (morsmordere) [reply src/Blocks/BlockCactus.h]: Hopefully my last commits reflected the changes you wanted.

**Comment by madmaxoft** [comment]
It is going to get merged after a second person has a look at it - we generally want at least two people to review a PR before merging it.
