### PR TITLE
Removed duplicate code

### LINKED ISSUE #3670: a few hundred wolves too many
Client version:   `1.11.2`
Server OS:         `Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-72-generic x86_64)`
Commit id:        `6c420ce5570ca4ac2aa5cabf80c3fa743d11ecf2`

### Expected behavior
"normal" amount of wolves

### Actual behavior
many hundreds of wolves

### Steps to reproduce the behavior
I noticed a "few" extra wolves around than usual, but when we logged in today, there were many many hundreds. We've starting killing them with lava, but there are still enough to be lagging the server.

doges

This picture is from the country side, but where there are holes where they can get trapped, its horrifying.

/cc @gavindinubilo

### PR DESCRIPTION
**Pull request by Bond-009**
This should also fix #3670

### CODE REVIEW

File: src/MobSpawner.cpp [hunk 1]
```diff
@@ -340,6 +296,139 @@ bool cMobSpawner::CanSpawnHere(cChunk * a_Chunk, int a_RelX, int a_RelY, int a_R
...
+		{
+			ListOfSpawnables.insert(mtHorse);
+			break;
+		}
+
+		// Add wolves in forest biomes
+		case biForest:
+		{
+			ListOfSpawnables.insert(mtWolf);
+		}
```
Comment (madmaxoft) [inline src/MobSpawner.cpp]: A `break` seems to be missing here; if this is intentional, add a comment: `// fall-through`

File: src/MobSpawner.cpp [hunk 2]
```diff
@@ -45,75 +45,31 @@ bool cMobSpawner::CheckPackCenter(BLOCKTYPE a_BlockType)
...
-		addIfAllowed(mtBat, allowedMobs);
-		addIfAllowed(mtSpider, allowedMobs);
-		addIfAllowed(mtZombie, allowedMobs);
-		addIfAllowed(mtSkeleton, allowedMobs);
-		addIfAllowed(mtCreeper, allowedMobs);
-		addIfAllowed(mtSquid, allowedMobs);
-		addIfAllowed(mtGuardian, allowedMobs);
-
-		if ((a_Biome != biDesert) && (a_Biome != biBeach) && (a_Biome != biOcean))
+		std::set<eMonsterType>::iterator itr = m_AllowedTypes.find(MobType);
```
Comment (madmaxoft) [inline src/MobSpawner.cpp]: Use `auto`

File: src/MobSpawner.cpp [hunk 3]
```diff
@@ -340,6 +290,109 @@ bool cMobSpawner::CanSpawnHere(cChunk * a_Chunk, int a_RelX, int a_RelY, int a_R
...
+		if (
+			(a_Biome != biJungle) &&
+			(a_Biome != biJungleHills) &&
+			(a_Biome != biJungleEdge) &&
+			(a_Biome != biJungleM) &&
+			(a_Biome != biJungleEdgeM))
+		{
+			ListOfSpawnables.insert(mtOcelot);
+		}
+		if (
```
Comment (bearbin) [inline src/MobSpawner.cpp]: These conditions for biomes look to be all inverted.

File: src/Generating/FinishGen.cpp [hunk 4]
```diff
@@ -1505,100 +1506,26 @@ bool cFinishGenPassiveMobs::TrySpawnAnimals(cChunkDesc & a_ChunkDesc, int a_RelX
...
 {
 
-	std::set<eMonsterType> ListOfSpawnables;
+	std::vector<eMonsterType> ListOfSpawnables;
 	int chunkX = a_ChunkDesc.GetChunkX();
 	int chunkZ = a_ChunkDesc.GetChunkZ();
 	int x = (m_Noise.IntNoise2DInt(chunkX, chunkZ + 10) / 7) % cChunkDef::Width;
 	int z = (m_Noise.IntNoise2DInt(chunkX + chunkZ, chunkZ) / 7) % cChunkDef::Width;
 
-	// Check biomes first to get a list of animals
```
Comment (bearbin) [inline src/Generating/FinishGen.cpp]: Is re-constructing this vector every time not a waste of resources? I think this could be better done just once.

File: src/Generating/FinishGen.cpp [hunk 5]
```diff
@@ -1505,100 +1506,26 @@ bool cFinishGenPassiveMobs::TrySpawnAnimals(cChunkDesc & a_ChunkDesc, int a_RelX
...
-	auto MobIter = ListOfSpawnables.begin();
-	using diff_type =
-		std::iterator_traits<decltype(MobIter)>::difference_type;
-	diff_type RandMob = static_cast<diff_type>
-		(static_cast<size_t>(m_Noise.IntNoise2DInt(chunkX - chunkZ + 2, chunkX + 5) / 7)
-		% ListOfSpawnables.size());
-	std::advance(MobIter, RandMob);
-
-	return *MobIter;
+	return ListOfSpawnables[GetRandomProvider().RandInt(ListOfSpawnables.size() - 1)];
```
Comment (peterbell10) [inline src/Generating/FinishGen.cpp]: I think this should still be using noise instead of rng as it's part of the generator.

File: src/World.cpp [hunk 6]
```diff
@@ -1199,7 +1199,7 @@ void cWorld::TickMobs(std::chrono::milliseconds a_Dt)
 				else
 				{
 					auto & Wolf = static_cast<cWolf &>(Monster);
-					if (Wolf.IsAngry())
+					if (!Wolf.IsAngry())
 					{
 						Monster.Destroy(true);
```
Comment (peterbell10) [inline src/World.cpp]: Will this destroy tamed wolves as well?

File: src/MobSpawner.cpp [hunk 7]
```diff
@@ -340,6 +290,109 @@ bool cMobSpawner::CanSpawnHere(cChunk * a_Chunk, int a_RelX, int a_RelY, int a_R
...
+	std::set<eMonsterType> ListOfSpawnables;
+	// Check biomes first to get a list of animals
+	if (a_Biome == biNether)
+	{
+		ListOfSpawnables.insert(mtGhast);
+		ListOfSpawnables.insert(mtMagmaCube);
+		ListOfSpawnables.insert(mtZombiePigman);
+		ListOfSpawnables.insert(mtEnderman);
+	}
+	else if (a_Biome == biEnd)
```
Comment (peterbell10) [inline src/MobSpawner.cpp]: Is there a reason you've moved away from `switch` to `if`-`else` chains?

Comment (Bond-009) [reply src/MobSpawner.cpp]: Looks like I misread your last review :/

File: src/World.cpp (hunk 6 above)
Comment (Bond-009) [reply src/World.cpp]: It shouldn't, wolves only get angry when they aren't tamed https://github.com/cuberite/cuberite/blob/master/src/Mobs/Wolf.cpp#L58

Comment (peterbell10) [reply src/World.cpp]: But this is destroying wolves that are _not_ angry.

File: src/MobSpawner.cpp [hunk 8]
```diff
@@ -45,75 +45,26 @@ bool cMobSpawner::CheckPackCenter(BLOCKTYPE a_BlockType)
...
-	size_t allowedMobsSize = allowedMobs.size();
-	if (allowedMobsSize > 0)
+	if (AllowedMobs.empty())
 	{
-		return allowedMobs[GetRandomProvider().RandInt(allowedMobsSize - 1)];
+		return mtInvalidType;
 	}
-	return mtInvalidType;
+
+	return AllowedMobs[GetRandomProvider().RandInt(AllowedMobs.size() - 1)]
```
Comment (bearbin) [inline src/MobSpawner.cpp]: You're missing a semicolon here, which is causing the builds to fail.

**Comment by bearbin** [comment]
You're missing another semicolon - https://travis-ci.org/cuberite/cuberite/jobs/361752039#L1327

Can you try compiling on your local machine to avoid these silly omissions?

**Comment by Bond-009** [comment]
@bearbin Sorry I couldn't compile on the machine I made those commits from, next time I'll wait till I'm behind my Linux machine :/

File: src/MobSpawner.cpp [hunk 9]
```diff
@@ -340,6 +296,139 @@ bool cMobSpawner::CanSpawnHere(cChunk * a_Chunk, int a_RelX, int a_RelY, int a_R
...
+	}
+
+	if (
+		(a_Biome != biDesertHills) &&
+		(a_Biome != biDesert) &&
+		(a_Biome != biDesertM) &&
+		(a_Biome != biBeach) &&
+		(a_Biome != biOcean) &&
+		(a_Biome != biDeepOcean))
+	{
```
[the remark this answers is not in the document]
Comment (Bond-009) [reply src/MobSpawner.cpp]: IMO this is easier to understand than a switch statement that looks like this:
```c++
switch (biome)
    case biBeach:
    case biOcean:
    case ...:
         break;
    default:
    {
    // logic
    }
```

[the remark this answers is not in the document]
Comment (peterbell10) [reply src/MobSpawner.cpp]: Okay, fair enough.
