### PR TITLE
Webadmin: Added a missing CS lock.

### LINKED ISSUE #3547: Assertion failed: Opened webamin page and wanted to login
Server OS:        Linux
Commit id:        0256daa7ca98bab7482581dad39f66d570030874

### Expected behavior
Login should maybe work in debug mode, too?

### Actual behavior
Assertion occurs on trying to login into webamin.

### Steps to reproduce the behavior
1. Enable user login from `webadmin.ini`
2. Start server compiled with debug flag
3. Open webamin page
4. Try to login

```
Currently logging to "gdb.txt".
Logs will be appended to the log file.
Output is being logged and displayed.
Starting program: /home/lukas/minecraft/servers/Server_master/Cuberite_debug 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6d7e700 (LWP 2724)]
[New Thread 0x7ffff4f0c700 (LWP 2725)]
[New Thread 0x7fffeffff700 (LWP 2726)]
[New Thread 0x7fffef7fe700 (LWP 2727)]
[New Thread 0x7fffee7f8700 (LWP 2728)]
[New Thread 0x7fffedff7700 (LWP 2729)]
[New Thread 0x7fffed7f6700 (LWP 2730)]
[New Thread 0x7fffecff5700 (LWP 2731)]
[New Thread 0x7fffdffff700 (LWP 2732)]
[New Thread 0x7fffdeff9700 (LWP 2733)]
[New Thread 0x7fffde7f8700 (LWP 2734)]
[New Thread 0x7fffddff7700 (LWP 2735)]
[New Thread 0x7fffdd7f6700 (LWP 2736)]
[New Thread 0x7fffdcff5700 (LWP 2737)]
[New Thread 0x7fffcf7fa700 (LWP 2738)]
[New Thread 0x7fffceff9700 (LWP 2739)]
[New Thread 0x7fffce7f8700 (LWP 2740)]
[New Thread 0x7fffcdff7700 (LWP 2741)]
[New Thread 0x7fffcd7f6700 (LWP 2742)]
[New Thread 0x7fffccff5700 (LWP 2743)]

Thread 2 "Cuberite_debug" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff6d7e700 (LWP 2724)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
  Id   Target Id         Frame 
  1    Thread 0x7ffff7fe7740 (LWP 2720) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
* 2    Thread 0x7ffff6d7e700 (LWP 2724) "Cuberite_debug" __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:58
  3    Thread 0x7ffff4f0c700 (LWP 2725) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 0x7fffeffff700 (LWP 2726) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7fffef7fe700 (LWP 2727) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 0x7fffee7f8700 (LWP 2728) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7fffedff7700 (LWP 2729) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  8    Thread 0x7fffed7f6700 (LWP 2730) "Cuberite_debug" 0x00007ffff712d81d in nanosleep ()
    at ../sysdeps/unix/syscall-template.S:84
  9    Thread 0x7fffecff5700 (LWP 2731) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  10   Thread 0x7fffdffff700 (LWP 2732) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  11   Thread 0x7fffdeff9700 (LWP 2733) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  12   Thread 0x7fffde7f8700 (LWP 2734) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  13   Thread 0x7fffddff7700 (LWP 2735) "Cuberite_debug" 0x00007ffff712d81d in nanosleep ()
    at ../sysdeps/unix/syscall-template.S:84
  14   Thread 0x7fffdd7f6700 (LWP 2736) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  15   Thread 0x7fffdcff5700 (LWP 2737) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  16   Thread 0x7fffcf7fa700 (LWP 2738) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  17   Thread 0x7fffceff9700 (LWP 2739) "Cuberite_debug" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  18   Thread 0x7fffce7f8700 (LWP 2740) "Cuberite_debug" 0x00007ffff712d81d in nanosleep ()
    at ../sysdeps/unix/syscall-template.S:84
  19   Thread 0x7fffcdff7700 (LWP 2741) "Cuberite_debug" 0x00007ffff712d81d in nanosleep ()
    at ../sysdeps/unix/syscall-template.S:84
  20   Thread 0x7fffcd7f6700 (LWP 2742) "Cuberite_debug" 0x00007ffff712d81d in nanosleep ()
    at ../sysdeps/unix/syscall-template.S:84
  21   Thread 0x7fffccff5700 (LWP 2743) "Cuberite_debug" 0x00007ffff6e5a5dd in read ()
    at ../sysdeps/unix/syscall-template.S:84

Thread 21 (Thread 0x7fffccff5700 (LWP 2743)):
#0  0x00007ffff6e5a5dd in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff6df2a10 in _IO_new_file_underflow (fp=0x7ffff71178c0 <_IO_2_1_stdin_>) at fileops.c:600
#2  0x00007ffff6df3b12 in __GI__IO_default_uflow (fp=0x7ffff71178c0 <_IO_2_1_stdin_>) at genops.c:413
#3  0x00007ffff6dee4f0 in _IO_getc (fp=0x7ffff71178c0 <_IO_2_1_stdin_>) at getc.c:38
#4  0x00007ffff763a20d in __gnu_cxx::stdio_sync_filebuf<char, std::char_traits<char> >::underflow() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff75f9bd9 in std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000000000977306 in cRoot::InputThread (a_Params=...) at /home/lukas/cpp/cuberite/src/Root.cpp:89
#7  0x000000000097fa6a in std::_Bind_simple<void (*(std::reference_wrapper<cRoot>))(cRoot&)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x554c9e8)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#8  0x000000000097fa15 in std::_Bind_simple<void (*(std::reference_wrapper<cRoot>))(cRoot&)>::operator()() (
    this=0x554c9e8) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#9  0x000000000097f7d9 in std::thread::_State_impl<std::_Bind_simple<void (*(std::reference_wrapper<cRoot>))(cRoot&)> >::_M_run() (this=0x554c9e0) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#10 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff7124464 in start_thread (arg=0x7fffccff5700) at pthread_create.c:333
#12 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 20 (Thread 0x7fffcd7f6700 (LWP 2742)):
#0  0x00007ffff712d81d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x000000000098fa40 in std::this_thread::sleep_for<long, std::ratio<1l, 1000000000l> > (__rtime=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:322
#2  0x000000000098a9ac in cServer::cTickThread::Execute (this=0x149e4e0)
    at /home/lukas/cpp/cuberite/src/Server.cpp:120
#3  0x00000000009edb97 in cIsThread::DoExecute (this=0x149e4e0)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#4  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x2fd2490: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#5  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x2fd2490: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#6  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x2fd2490, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#7  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x2fd2488)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#8  0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x2fd2488) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#9  0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x2fd2480) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#10 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff7124464 in start_thread (arg=0x7fffcd7f6700) at pthread_create.c:333
#12 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 19 (Thread 0x7fffcdff7700 (LWP 2741)):
#0  0x00007ffff712d81d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x000000000091a950 in std::this_thread::sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:322
#2  0x0000000000919f41 in cDeadlockDetect::Execute (this=0x7fffffffdf18)
    at /home/lukas/cpp/cuberite/src/DeadlockDetect.cpp:138
#3  0x00000000009edb97 in cIsThread::DoExecute (this=0x7fffffffdf18)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#4  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x42dc130: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#5  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x42dc130: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#6  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x42dc130, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#7  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x42dc128)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#8  0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x42dc128) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#9  0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x42dc120) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#10 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff7124464 in start_thread (arg=0x7fffcdff7700) at pthread_create.c:333
#12 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 18 (Thread 0x7fffce7f8700 (LWP 2740)):
#0  0x00007ffff712d81d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x000000000091a950 in std::this_thread::sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:322
#2  0x00000000009abade in cWorld::cTickThread::Execute (this=0x7ffff5e02ac8)
    at /home/lukas/cpp/cuberite/src/World.cpp:118
#3  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff5e02ac8)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#4  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x43a6900: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#5  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x43a6900: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#6  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x43a6900, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#7  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x43a68f8)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#8  0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x43a68f8) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#9  0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x43a68f0) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#10 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff7124464 in start_thread (arg=0x7fffce7f8700) at pthread_create.c:333
#12 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 17 (Thread 0x7fffceff9700 (LWP 2739)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff56b1e48, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7ffff56b1e18) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x00000000008e5191 in cChunkSender::Execute (this=0x7ffff5689ce0)
    at /home/lukas/cpp/cuberite/src/ChunkSender.cpp:189
#5  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff5689ce0)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x435c910: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#7  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x435c910: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#8  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x435c910, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#9  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x435c908)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#10 0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x435c908) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#11 0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x435c900) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#12 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7124464 in start_thread (arg=0x7fffceff9700) at pthread_create.c:333
#14 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 16 (Thread 0x7fffcf7fa700 (LWP 2738)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff5689ad8, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7ffff5689aa8) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x0000000000bd1d8b in cChunkGenerator::Execute (this=0x7ffff56899b8)
    at /home/lukas/cpp/cuberite/src/Generating/ChunkGenerator.cpp:218
#5  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff56899b8)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x548cd40: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#7  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x548cd40: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#8  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x548cd40, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#9  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x548cd38)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#10 0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x548cd38) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#11 0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x548cd30) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#12 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7124464 in start_thread (arg=0x7fffcf7fa700) at pthread_create.c:333
#14 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 15 (Thread 0x7fffdcff5700 (LWP 2737)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff56898c0, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7ffff5689890) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x0000000000cdb735 in cWorldStorage::Execute (this=0x7ffff5689590)
    at /home/lukas/cpp/cuberite/src/WorldStorage/WorldStorage.cpp:209
#5  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff5689590)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x53fffa0: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#7  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x53fffa0: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#8  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x53fffa0, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#9  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x53fff98)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#10 0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x53fff98) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#11 0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x53fff90) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#12 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7124464 in start_thread (arg=0x7fffdcff5700) at pthread_create.c:333
#14 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 14 (Thread 0x7fffdd7f6700 (LWP 2736)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff56b2128, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7ffff56b20f8) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x000000000093bb2d in cLightingThread::Execute (this=0x7ffff56b1ff0)
    at /home/lukas/cpp/cuberite/src/LightingThread.cpp:203
#5  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff56b1ff0)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x53ffbd0: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#7  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x53ffbd0: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#8  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x53ffbd0, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#9  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x53ffbc8)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#10 0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x53ffbc8) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#11 0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x53ffbc0) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#12 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7124464 in start_thread (arg=0x7fffdd7f6700) at pthread_create.c:333
#14 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 13 (Thread 0x7fffddff7700 (LWP 2735)):
#0  0x00007ffff712d81d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x000000000091a950 in std::this_thread::sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:322
#2  0x00000000009abade in cWorld::cTickThread::Execute (this=0x7ffff5687ac8)
    at /home/lukas/cpp/cuberite/src/World.cpp:118
#3  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff5687ac8)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#4  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x41fb000: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#5  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x41fb000: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#6  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x41fb000, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#7  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x41faff8)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#8  0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x41faff8) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#9  0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x41faff0) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#10 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff7124464 in start_thread (arg=0x7fffddff7700) at pthread_create.c:333
#12 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 12 (Thread 0x7fffde7f8700 (LWP 2734)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff4f36e48, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7ffff4f36e18) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x00000000008e5191 in cChunkSender::Execute (this=0x7ffff4f0ece0)
    at /home/lukas/cpp/cuberite/src/ChunkSender.cpp:189
#5  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff4f0ece0)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x31c3520: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#7  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x31c3520: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#8  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x31c3520, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#9  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x31c3518)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#10 0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x31c3518) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#11 0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x31c3510) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#12 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7124464 in start_thread (arg=0x7fffde7f8700) at pthread_create.c:333
#14 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 11 (Thread 0x7fffdeff9700 (LWP 2733)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff4f0ead8, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7ffff4f0eaa8) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x0000000000bd1d8b in cChunkGenerator::Execute (this=0x7ffff4f0e9b8)
    at /home/lukas/cpp/cuberite/src/Generating/ChunkGenerator.cpp:218
#5  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff4f0e9b8)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x31c38c0: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#7  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x31c38c0: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#8  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x31c38c0, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#9  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x31c38b8)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#10 0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x31c38b8) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#11 0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x31c38b0) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#12 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7124464 in start_thread (arg=0x7fffdeff9700) at pthread_create.c:333
#14 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 10 (Thread 0x7fffdffff700 (LWP 2732)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff4f0e8c0, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7ffff4f0e890) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x0000000000cdb735 in cWorldStorage::Execute (this=0x7ffff4f0e590)
    at /home/lukas/cpp/cuberite/src/WorldStorage/WorldStorage.cpp:209
#5  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff4f0e590)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x31c34f0: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#7  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x31c34f0: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#8  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x31c34f0, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#9  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x31c34e8)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#10 0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x31c34e8) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#11 0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x31c34e0) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#12 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7124464 in start_thread (arg=0x7fffdffff700) at pthread_create.c:333
#14 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 9 (Thread 0x7fffecff5700 (LWP 2731)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff4f37128, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7ffff4f370f8) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x000000000093bb2d in cLightingThread::Execute (this=0x7ffff4f36ff0)
    at /home/lukas/cpp/cuberite/src/LightingThread.cpp:203
#5  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff4f36ff0)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x31c3120: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#7  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x31c3120: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#8  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x31c3120, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#9  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x31c3118)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#10 0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x31c3118) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#11 0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x31c3110) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#12 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7124464 in start_thread (arg=0x7fffecff5700) at pthread_create.c:333
#14 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 8 (Thread 0x7fffed7f6700 (LWP 2730)):
#0  0x00007ffff712d81d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x000000000091a950 in std::this_thread::sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:322
#2  0x00000000009abade in cWorld::cTickThread::Execute (this=0x7ffff657dac8)
    at /home/lukas/cpp/cuberite/src/World.cpp:118
#3  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff657dac8)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#4  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x302ef90: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#5  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x302ef90: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#6  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x302ef90, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#7  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x302ef88)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#8  0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x302ef88) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#9  0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x302ef80) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#10 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff7124464 in start_thread (arg=0x7fffed7f6700) at pthread_create.c:333
#12 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 7 (Thread 0x7fffedff7700 (LWP 2729)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff5e2ce48, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7ffff5e2ce18) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x00000000008e5191 in cChunkSender::Execute (this=0x7ffff5e04ce0)
    at /home/lukas/cpp/cuberite/src/ChunkSender.cpp:189
#5  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff5e04ce0)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x3076cc0: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#7  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x3076cc0: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#8  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x3076cc0, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#9  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x3076cb8)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#10 0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x3076cb8) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#11 0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x3076cb0) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#12 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7124464 in start_thread (arg=0x7fffedff7700) at pthread_create.c:333
#14 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 6 (Thread 0x7fffee7f8700 (LWP 2728)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff5e04ad8, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7ffff5e04aa8) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x0000000000bd1d8b in cChunkGenerator::Execute (this=0x7ffff5e049b8)
    at /home/lukas/cpp/cuberite/src/Generating/ChunkGenerator.cpp:218
#5  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff5e049b8)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x2f945a0: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#7  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x2f945a0: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#8  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x2f945a0, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#9  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x2f94598)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#10 0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x2f94598) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#11 0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x2f94590) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#12 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7124464 in start_thread (arg=0x7fffee7f8700) at pthread_create.c:333
#14 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 5 (Thread 0x7fffef7fe700 (LWP 2727)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff5e048c0, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7ffff5e04890) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x0000000000cdb735 in cWorldStorage::Execute (this=0x7ffff5e04590)
    at /home/lukas/cpp/cuberite/src/WorldStorage/WorldStorage.cpp:209
#5  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff5e04590)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x2cf9170: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#7  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x2cf9170: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#8  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x2cf9170, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#9  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x2cf9168)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#10 0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x2cf9168) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#11 0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x2cf9160) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#12 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7124464 in start_thread (arg=0x7fffef7fe700) at pthread_create.c:333
#14 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 4 (Thread 0x7fffeffff700 (LWP 2726)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7ffff5e2d128, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7ffff5e2d0f8) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x000000000093bb2d in cLightingThread::Execute (this=0x7ffff5e2cff0)
    at /home/lukas/cpp/cuberite/src/LightingThread.cpp:203
#5  0x00000000009edb97 in cIsThread::DoExecute (this=0x7ffff5e2cff0)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x2cf9030: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#7  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x2cf9030: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#8  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x2cf9030, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#9  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x2cf9028)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#10 0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x2cf9028) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#11 0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x2cf9020) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#12 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7124464 in start_thread (arg=0x7fffeffff700) at pthread_create.c:333
#14 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 3 (Thread 0x7ffff4f0c700 (LWP 2725)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7fffffffe370, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7fffffffe340) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x0000000000b84c84 in cAuthenticator::Execute (this=0x7fffffffe220)
    at /home/lukas/cpp/cuberite/src/Protocol/Authenticator.cpp:106
#5  0x00000000009edb97 in cIsThread::DoExecute (this=0x7fffffffe220)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#6  0x00000000009ee4f1 in std::__invoke_impl<void, void (cIsThread::* const&)(), cIsThread*>(std::__invoke_memfun_deref, void (cIsThread::* const&)(), cIsThread*&&) (
    __f=@0x1d42900: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __t=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48e322>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:235
#7  0x00000000009ee472 in std::__invoke<void (cIsThread::* const&)(), cIsThread*>(void (cIsThread::* const&)(), cIsThread*&&) (__fn=@0x1d42900: (void (cIsThread::*)(cIsThread * const)) 0x9edb60 <cIsThread::DoExecute()>, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x48b358>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:259
#8  0x00000000009ee3f0 in std::_Mem_fn_base<void (cIsThread::*)(), true>::operator()<cIsThread*> (this=0x1d42900, 
    __args=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x48b230, DIE 0x491966>)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:613
#9  0x00000000009ee392 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x1d428f8)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#10 0x00000000009ee345 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x1d428f8) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#11 0x00000000009ee109 in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x1d428f0) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#12 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7124464 in start_thread (arg=0x7ffff4f0c700) at pthread_create.c:333
#14 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 2 (Thread 0x7ffff6d7e700 (LWP 2724)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007ffff6db340a in __GI_abort () at abort.c:89
#2  0x00007ffff6daae47 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0xfec8b6 "0", 
    file=file@entry=0xfa02e7 "/home/lukas/cpp/cuberite/src/Bindings/LuaState.cpp", line=line@entry=2382, 
    function=function@entry=0xfa1525 "void cLuaState::cRef::RefStack(cLuaState &, int)") at assert.c:92
#3  0x00007ffff6daaef2 in __GI___assert_fail (assertion=0xfec8b6 "0", 
    file=0xfa02e7 "/home/lukas/cpp/cuberite/src/Bindings/LuaState.cpp", line=2382, 
    function=0xfa1525 "void cLuaState::cRef::RefStack(cLuaState &, int)") at assert.c:101
#4  0x0000000000a0bc72 in cLuaState::cRef::RefStack (this=0x7ffff6d7c050, a_LuaState=..., a_StackPos=2)
    at /home/lukas/cpp/cuberite/src/Bindings/LuaState.cpp:2382
#5  0x0000000000a137fc in cLuaState::cRef::cRef (this=0x7ffff6d7c050, a_LuaState=..., a_StackPos=2)
    at /home/lukas/cpp/cuberite/src/Bindings/LuaState.cpp:2344
#6  0x0000000000a3d0cb in cManualBindings::StaticForEach<cPluginManager, cPlugin, &cPluginManager::ForEachPlugin> (
    tolua_S=0x14a1ec0) at /home/lukas/cpp/cuberite/src/Bindings/./ManualBindings.h:534
#7  0x0000000000eefc54 in luaD_precall (L=0x14a1ec0, func=0x552c850, nresults=0)
    at /home/lukas/cpp/cuberite/lib/lua/src/ldo.c:319
#8  0x0000000000f0733e in luaV_execute (L=0x14a1ec0, nexeccalls=2) at /home/lukas/cpp/cuberite/lib/lua/src/lvm.c:587
#9  0x0000000000ef03f3 in luaD_call (L=0x14a1ec0, func=0x14a0b20, nResults=1)
    at /home/lukas/cpp/cuberite/lib/lua/src/ldo.c:377
#10 0x0000000000eea5df in f_call (L=0x14a1ec0, ud=0x7ffff6d7c928) at /home/lukas/cpp/cuberite/lib/lua/src/lapi.c:800
#11 0x0000000000eef385 in luaD_rawrunprotected (L=0x14a1ec0, f=0xeea5b0 <f_call>, ud=0x7ffff6d7c928)
    at /home/lukas/cpp/cuberite/lib/lua/src/ldo.c:116
#12 0x0000000000ef083a in luaD_pcall (L=0x14a1ec0, func=0xeea5b0 <f_call>, u=0x7ffff6d7c928, old_top=32, ef=16)
    at /home/lukas/cpp/cuberite/lib/lua/src/ldo.c:463
#13 0x0000000000eea568 in lua_pcall (L=0x14a1ec0, nargs=2, nresults=1, errfunc=-4)
    at /home/lukas/cpp/cuberite/lib/lua/src/lapi.c:821
#14 0x0000000000a1056a in cLuaState::CallFunction (this=0x14a0828, a_NumResults=1)
    at /home/lukas/cpp/cuberite/src/Bindings/LuaState.cpp:1538
#15 0x00000000009a8afc in cLuaState::PushCallPop<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&> (this=0x14a0828, args=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
) at /home/lukas/cpp/cuberite/src/./Bindings/LuaState.h:899
#16 0x00000000009a8abd in cLuaState::PushCallPop<HTTPTemplateRequest*, cLuaState::cRet const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(HTTPTemplateRequest*&&, cLuaState::cRet const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (this=0x14a0828, 
    a_Param=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x3aed04, DIE 0x3d57dc>, args=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, args=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
) at /home/lukas/cpp/cuberite/src/./Bindings/LuaState.h:888
#17 0x00000000009a88d6 in cLuaState::PushCallPop<cWebAdmin*, HTTPTemplateRequest*, cLuaState::cRet const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(cWebAdmin*&&, HTTPTemplateRequest*&&, cLuaState::cRet const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (this=0x14a0828, 
    a_Param=<unknown type in /home/lukas/minecraft/servers/Server_master/Cuberite_debug, CU 0x3aed04, DIE 0x3d571d>, args=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, args=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, args=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
) at /home/lukas/cpp/cuberite/src/./Bindings/LuaState.h:888
#18 0x00000000009a4a3b in cLuaState::Call<char [9], cWebAdmin*, HTTPTemplateRequest*, cLuaState::cRet const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(char const (&) [9], cWebAdmin*&&, HTTPTemplateRequest*&&, cLuaState::cRet const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (this=0x14a0828, a_Function=..., 
    args=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, args=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, args=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
, args=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
) at /home/lukas/cpp/cuberite/src/./Bindings/LuaState.h:720
#19 0x00000000009a105b in cWebAdmin::HandleWebadminRequest (this=0x14a07d0, a_Connection=..., a_Request=...)
    at /home/lukas/cpp/cuberite/src/WebAdmin.cpp:344
#20 0x00000000009a3830 in cWebAdmin::OnRequestFinished (this=0x14a07d0, a_Connection=..., a_Request=...)
    at /home/lukas/cpp/cuberite/src/WebAdmin.cpp:677
#21 0x0000000000a00436 in cHTTPServer::RequestFinished (this=0x14a09c0, a_Connection=..., a_Request=...)
    at /home/lukas/cpp/cuberite/src/HTTP/HTTPServer.cpp:221
#22 0x0000000000a045fe in cHTTPServerConnection::OnBodyFinished (this=0x7ffff00011b0)
    at /home/lukas/cpp/cuberite/src/HTTP/HTTPServerConnection.cpp:224
#23 0x0000000000a0836e in cHTTPMessageParser::OnBodyFinished (this=0x7ffff00011c8)
    at /home/lukas/cpp/cuberite/src/HTTP/HTTPMessageParser.cpp:217
#24 0x0000000000a0af40 in cIdentityTEParser::Parse (this=0x7ffff0001e00, a_Data=0x7ffff0002180 "", a_Size=0)
    at /home/lukas/cpp/cuberite/src/HTTP/TransferEncodingParser.cpp:346
#25 0x0000000000a0802a in cHTTPMessageParser::ParseBody (this=0x7ffff00011c8, a_Data=0x7ffff0002180 "", a_Size=0)
    at /home/lukas/cpp/cuberite/src/HTTP/HTTPMessageParser.cpp:150
#26 0x0000000000a07ad0 in cHTTPMessageParser::Parse (this=0x7ffff00011c8, 
    a_Data=0x7ffff6d7d760 "GET /webadmin/? HTTP/1.1\r\nHost: 192.168.2.38:8080\r\nConnection: keep-alive\r\nAuthorization: Basic YWRtaW46YWRtaW4=\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWe"..., a_Size=481) at /home/lukas/cpp/cuberite/src/HTTP/HTTPMessageParser.cpp:64
#27 0x0000000000a0408c in cHTTPServerConnection::OnReceivedData (this=0x7ffff00011b0, 
    a_Data=0x7ffff6d7d760 "GET /webadmin/? HTTP/1.1\r\nHost: 192.168.2.38:8080\r\nConnection: keep-alive\r\nAuthorization: Basic YWRtaW46YWRtaW4=\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWe"..., a_Size=481) at /home/lukas/cpp/cuberite/src/HTTP/HTTPServerConnection.cpp:126
#28 0x00000000009fb0cd in cTCPLinkImpl::ReceivedCleartextData (this=0x7ffff0001630, 
    a_Data=0x7ffff6d7d760 "GET /webadmin/? HTTP/1.1\r\nHost: 192.168.2.38:8080\r\nConnection: keep-alive\r\nAuthorization: Basic YWRtaW46YWRtaW4=\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWe"..., a_Length=481) at /home/lukas/cpp/cuberite/src/OSSupport/TCPLinkImpl.cpp:492
#29 0x00000000009f9bab in cTCPLinkImpl::ReadCallback (a_BufferEvent=0x7ffff0001770, a_Self=0x7ffff0001630)
    at /home/lukas/cpp/cuberite/src/OSSupport/TCPLinkImpl.cpp:294
#30 0x0000000000f1e6f0 in bufferevent_run_deferred_callbacks_unlocked (cb=0x7ffff0001910, arg=0x7ffff0001770)
    at /home/lukas/cpp/cuberite/lib/libevent/bufferevent.c:190
#31 0x0000000000f3143e in event_process_active_single_queue (base=0x149ce40, activeq=0x149a680, 
    max_to_process=2147483647, endtime=0x0) at /home/lukas/cpp/cuberite/lib/libevent/event.c:1648
#32 0x0000000000f2a94b in event_process_active (base=0x149ce40)
    at /home/lukas/cpp/cuberite/lib/libevent/event.c:1734
#33 0x0000000000f29776 in event_base_loop (base=0x149ce40, flags=4)
    at /home/lukas/cpp/cuberite/lib/libevent/event.c:1957
#34 0x00000000009eec9f in cNetworkSingleton::RunEventLoop (a_Self=0x147c808 <cNetworkSingleton::Get()::Instance>)
    at /home/lukas/cpp/cuberite/src/OSSupport/NetworkSingleton.cpp:174
#35 0x00000000009f17b2 in std::_Bind_simple<void (*(cNetworkSingleton*))(cNetworkSingleton*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x149a2c8)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1399
#36 0x00000000009f1765 in std::_Bind_simple<void (*(cNetworkSingleton*))(cNetworkSingleton*)>::operator()() (
    this=0x149a2c8) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/functional:1389
#37 0x00000000009f1529 in std::thread::_State_impl<std::_Bind_simple<void (*(cNetworkSingleton*))(cNetworkSingleton*)> >::_M_run() (this=0x149a2c0) at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/thread:196
#38 0x00007ffff760acdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#39 0x00007ffff7124464 in start_thread (arg=0x7ffff6d7e700) at pthread_create.c:333
#40 0x00007ffff6e679df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 1 (Thread 0x7ffff7fe7740 (LWP 2720)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff760539c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000009eb1c1 in std::condition_variable::wait<cEvent::Wait()::$_0>(std::unique_lock<std::mutex>&, cEvent::Wait()::$_0) (this=0x7fffffffe1b0, __lock=..., __p=...)
    at /usr/lib/gcc/x86_64-linux-gnu/6.2.1/../../../../include/c++/6.2.1/condition_variable:99
#3  0x00000000009eb13e in cEvent::Wait (this=0x7fffffffe180) at /home/lukas/cpp/cuberite/src/OSSupport/Event.cpp:28
#4  0x00000000009788c6 in cRoot::Start (this=0x7fffffffe0e8, 
    a_OverridesRepo=std::unique_ptr<cSettingsRepositoryInterface> containing 0x0)
    at /home/lukas/cpp/cuberite/src/Root.cpp:233
#5  0x00000000009dae4a in UniversalMain (
    a_OverridesRepo=std::unique_ptr<cSettingsRepositoryInterface> containing 0x0)
    at /home/lukas/cpp/cuberite/src/main.cpp:243
#6  0x00000000009d93c3 in main (argc=1, argv=0x7fffffffe5e8) at /home/lukas/cpp/cuberite/src/main.cpp:558
```

### PR DESCRIPTION
**Pull request by madmaxoft**
This fixes an assert when accessing the login-page and the plugin-failure pages in the webadmin.

Fixes #3547

### CODE REVIEW

File: src/WebAdmin.cpp [hunk 1]
```diff
@@ -341,6 +341,7 @@ void cWebAdmin::HandleWebadminRequest(cHTTPServerConnection & a_Connection, cHTT
 	if (ShouldWrapInTemplate)
 	{
 		cCSLock Lock(m_CS);
+		cLuaState::cLock lock(m_TemplateScript);
```
Comment (sphinxc0re) [inline src/WebAdmin.cpp]: I'm not too sure about the naming. It pretty easy to mix those two up @madmaxoft

Comment (Seadragon91) [inline src/WebAdmin.cpp]: I think it's okay, because they are destroyed at the end of the scope.

Comment (madmaxoft) [inline src/WebAdmin.cpp]: Oh, I didn't even notice. You're right, that's poor style, I'll rename them both.
