### PR TITLE
Fix explosion knockback issues and tweak knockback strength

### LINKED ISSUE #4575: Explosions send all players up in the sky
Client version: 1.12.2
Server OS: Ubuntu server 16.04 i386
Cuberite Commit id:  fce548139b8c4643cd28f636d5c497d2ca8cd230

### Expected behavior
An explosion shouldn't shoot the player in the sky, and should be only for players around the explosions

### Actual behavior
If a player is around and touch by an explosion, all players (at least in the same world) are sent in the sky with a very huge power, all players mean players that are far from the explosion

### Steps to reproduce the behavior
At least 2 players I believe, TNT, Ghasts or something else that can cause an explosion

### PR DESCRIPTION
**Pull request by peterbell10**
Closes #4588, closes #4575

This is #4588 plus a few tweaks. AFAICT, the main fix is always setting the entity's speed, even if they aren't within range of the explosion.

I also compared against vanilla and the knockback was way too strong for players a few blocks from the explosion. So, I've made it so you need to be within .2 blocks of the TNT to get the full knockback strength.

### CODE REVIEW

**Comment by mathiascode** [comment]
Non-player knockback is still too weak (tnt cannon), and https://github.com/cuberite/cuberite/issues/4575 still occurs. Spawn a bunch of ghasts, let them shoot you, and you should eventually blast away into the sky.

File: src/ChunkMap.cpp [hunk 1]
```diff
@@ -1313,21 +1313,19 @@ void cChunkMap::DoExplosionAt(double a_ExplosionSize, double a_BlockX, double a_
...
 
-				DistanceFromExplosion.Normalize();
-				DistanceFromExplosion *= Impact;
+			DistanceFromExplosion.Normalize();
+			DistanceFromExplosion *= Vector3d{Impact, 0.0, Impact};
+			DistanceFromExplosion.y += 0.3 * Impact;
 
-				a_Entity.SetSpeed(DistanceFromExplosion);
-			}
+			a_Entity.SetSpeed(DistanceFromExplosion);
```
Comment (bearbin) [inline src/ChunkMap.cpp]: This just seems wrong - how does setting the speed for all entities even those outside of the explosion radius _reduce_ the interference? This looks like it should set speed for all entities outside of the explosion radius to zero, which is not really a desired outcome.

**Comment by peterbell10** [comment]
>Non-player knockback is still too weak (tnt cannon)

That's #4527, not #4575

>#4575 still occurs. Spawn a bunch of ghasts, let them shoot you, and you should eventually blast away into the sky.

I don't see the connection to #4575. If you're shot at by a ghast then you should be knocked back because you're within range.

File: src/ChunkMap.cpp (hunk 1 above)
Comment (peterbell10) [reply src/ChunkMap.cpp]: Player speeds aren't really updated properly so sending 0 is preferable to sending junk.

Comment (peterbell10) [reply src/ChunkMap.cpp]: I could make this player only I suppose.

**Comment by mathiascode** [comment]
While it isn't exactly vanilla-like, my PR brought back some knockback for non-player entities, to make TNT cannons possible.

Obviously there should be some knockback from ghast blasts, but the issue is that one of them sometimes sends you hundreds of blocks into the sky. It seems to happen especially when multiple blasts are shot at once.

**Comment by mathiascode** [comment]
Seems to happen quite often when jumping right before the blast hits the ground.

**Comment by peterbell10** [comment]
>While it isn't exactly vanilla-like, my PR brought back some knockback for non-player entities, to make TNT cannons possible.

Okay, I restored your factor of 6.

>Obviously there should be some knockback from ghast blasts, but the issue is that one of them sometimes sends you hundreds of blocks into the sky. It seems to happen especially when multiple blasts are shot at once.

Well completely disabling knockback seems like an over reaction. I've reduced the knockback strength for players so it should be okay.

**Comment by mathiascode** [comment]
General throught/question: why do we have to send player motion in cClientHandle::SendExplosion? SetSpeed in the cChunkMap code should already take care of this for all entities in range, including players, and it means we would get proper knockback for everything (sharpnel, tnt etc).

**Comment by peterbell10** [comment]
>why do we have to send player motion in cClientHandle::SendExplosion? 

Because the client will take the most recent information i.e. what is sent in `SendExplosion`.

>it means we would get proper knockback for everything (sharpnel, tnt etc).

The speed is set for all entities either way.

File: src/World.cpp [hunk 2]
```diff
@@ -1417,17 +1417,20 @@ void cWorld::DoExplosionAt(double a_ExplosionSize, double a_BlockX, double a_Blo
 
 	BroadcastSoundEffect("entity.generic.explode", Vector3d(a_BlockX, a_BlockY, a_BlockZ), 4.0f, SoundPitchMultiplier * 0.7f);
 
+	Vector3d ExplosionPos(a_BlockX, a_BlockY, a_BlockZ);
 	{
 		cCSLock Lock(m_CSPlayers);
-		for (cPlayerList::iterator itr = m_Players.begin(); itr != m_Players.end(); ++itr)
+		for (auto Player : m_Players)
```
Comment (tigerw) [inline src/World.cpp]: is this a copy?

Comment (peterbell10) [reply src/World.cpp]: It's a pointer
