### PR TITLE
Below bedrock break crash

### LINKED ISSUE #5395: Server crashes when mining bedrock with hack client
Client version: **Every client/ Server side bug**
Server OS: **Linux, Debian 11 bullseye Openvz virt**
Cuberite Commit id: (from commit **de5b89dbea938db5a7ea58f59a9b1a91d0df4208** built at: Thu Feb 17 19:02:07 UTC 2022t)

https://user-images.githubusercontent.com/101947415/159139880-bb78e427-9115-4f79-9f20-43fec9d15ffc.mp4

### PR DESCRIPTION
**Pull request by KingCol13**
Fixes #5395.

### CODE REVIEW

File: src/Blocks/BlockPiston.cpp [hunk 1]
```diff
@@ -228,11 +234,6 @@ bool cBlockPistonHandler::CanPushBlock(
 	NIBBLETYPE currMeta;
 	a_World.GetBlockTypeMeta(a_BlockPos, currBlock, currMeta);
 
-	if (!cChunkDef::IsValidHeight(a_BlockPos.y))
-	{
-		return !a_RequirePushable;
```
Comment (KingCol13) [inline src/Blocks/BlockPiston.cpp:233]: I didn't really understand `a_RequirePushable`, to me `CanPushBlock` should just return whether the block can be pushed independent on whether we need it to be pushed or not. Maybe @tigerw can shed some light on this.

Comment (tigerw) [reply src/Blocks/BlockPiston.cpp:233]: `RequirePushable` should be named` IsPushing`! When retracting, `IsPushing == false` which changes the behaviour of `CanPush`, making it ignore a piston-breakable block instead of killing it. In this case I agree returning false is fine, this will stop extension and leave retraction unaffected.

Comment (tigerw) [reply src/Blocks/BlockPiston.cpp:233]: this file could do with some improvements to clarity, the logic is dense...

**Review by tigerw — APPROVED** [review]

**Comment by tigerw** [comment]
thanks and apologies!
