### PR TITLE
Fix armor protection

### LINKED ISSUE #4098: Armor
Client version:   1.12.2
Server OS:        Linux

### Expected behavior
When wearing armor expecting armor gauge

### Actual behavior
When wearing armor there is no armor gauge

### Steps to reproduce the behavior
When an armor is worn

### PR DESCRIPTION
**Pull request by mathiascode**
Precision was lost when returning GetArmorCoverAgainst's value as int. Since the Core plugin handles world difficulty, it reverted all FinalDamage changes from the armor checks. Armor calculation has been moved to Core. https://github.com/cuberite/Core/pull/218

### CODE REVIEW

File: src/Entities/Entity.cpp [hunk 1]
```diff
@@ -282,17 +282,12 @@ void cEntity::TakeDamage(cEntity & a_Attacker)
...
-	int EnchantmentCover = GetEnchantmentCoverAgainst(a_Attacker, a_DamageType, a_RawDamage);
-	int FinalDamage = a_RawDamage - ArmorCover - EnchantmentCover;
-	if ((FinalDamage == 0) && (a_RawDamage > 0))
-	{
-		// Nobody's invincible
-		FinalDamage = 1;
-	}
-	ApplyArmorDamage(ArmorCover);
+	float FinalDamage = a_RawDamage;
+	double ArmorCover = GetArmorCoverAgainst(a_Attacker, a_DamageType, a_RawDamage);
```
Comment (bearbin) [inline src/Entities/Entity.cpp]: Is there any reason for mixing floats and doubles here?

File: src/Entities/Entity.cpp [hunk 2]
```diff
@@ -282,17 +282,12 @@ void cEntity::TakeDamage(cEntity & a_Attacker)
...
+
+	ApplyArmorDamage(static_cast<int>(ArmorCover));
 
-	cEntity::TakeDamage(a_DamageType, a_Attacker, a_RawDamage, static_cast<float>(FinalDamage), a_KnockbackAmount);
+	cEntity::TakeDamage(a_DamageType, a_Attacker, a_RawDamage, FinalDamage, a_KnockbackAmount);
```
Comment (bearbin) [inline src/Entities/Entity.cpp]: FinalDamage hasn't actually been changed by this function - where are the enchantment and armour damage reductions now applied if not here?

**Comment by bearbin** [comment]
I'm also rather confused as to how this actually fixes #4098 - as far as I can tell the damage calculation logic is exactly the same and cast to int before damage is applied.

**Comment by mathiascode** [comment]
The code that still exists here only applies damage to the armor items. An integer is still used there, but I didn't look into how it works very extensively. The damage that affects the player's health is handled by Core now, and uses doubles.

File: src/Entities/Entity.cpp (hunk 1 above)
Comment (mathiascode) [reply src/Entities/Entity.cpp]: I suppose I should use float instead of double, since Minecraft uses float for health values.

**Comment by mathiascode** [comment]
Actually, now that I'm testing some mobs with larger attack damage, I think the calculations might be wrong. Will test further.

**Comment by mathiascode** [comment]
False alarm. Calculations are correct, but armor protection didn't apply for zombie attacks due to faulty logic in my Core plugin changes. I will fix it in my Core PR.

**Comment by mathiascode** [comment]
How so? The player is protected, and the armor wears out. What other functionality is missing?

**Comment by Greaper88** [comment]
I've had at least 3 complaints that armor doesn't work properly. Like iron/diamond gear has no more protection than leather if that much. I haven't been given any specific comparisons however.

**Comment by mathiascode** [comment]
Any armor protection damage changes were overwritten by the Core plugin before. It should work fine after this and https://github.com/cuberite/Core/pull/218 is merged.

**Comment by peterbell10** [comment]
#4098 is talking about the UI element above the hotbar that shows the armour cover. Presumably there is some protocol message that needs to be sent to the client.

**Comment by mathiascode** [comment]
Ah, I've completely forgotten about that thing. Should probably be a trivial fix.
