### PR TITLE
Fixed unloading of chunks that contain player entities

### LINKED ISSUE #4497: Assertion error in cEntity::IsTicking()
Client version: 1.12.2
Server OS: Windows/Linux/

### Actual behavior
Server crashes with assertion error on windows and with segfault on linux,

### Steps to reproduce the behavior
This plugin will teleport the player every 250ms and overloads the chunk generator.
After a few seconds (15s on my PC), the server crashes.
```
function Initialize(Plugin)
	Plugin:SetName("TestPlugin")
	Plugin:SetVersion(1) 
	
	cPluginManager.AddHook(cPluginManager.HOOK_PLAYER_SPAWNED, OnPlayerSpawn)

	return true
end

function OnPlayerSpawn(Player)
	g_PlayerName = Player:GetName()
	local x = math.random(-1000, 1000)
	local y = 70
	local z = math.random(-1000, 1000)
	Player:TeleportToCoords(x, y, z)
	Player:SetGameMode(gmCreative)
	Player:GetWorld():ScheduleTask(5, DoIt)
end
 
function DoIt(World)
	local x = math.random(-1000, 1000)
	local y = 70
	local z = math.random(-1000, 1000)
	World:DoWithPlayer(g_PlayerName,
		function(Player)
			Player:TeleportToCoords(x, y, z)
		end) 
	World:ScheduleTask(5, DoIt)
end
```

### Stacktraces

Assertion error on windows:
https://github.com/cuberite/cuberite/blob/5a2163d7e6ffa0c5c568be41257fb726d452b3b9/src/Entities/Entity.cpp#L86

Segfault on Linux:
```
#0  0x00007fffc0021dd0 in ?? ()
#1  0x0000000000d830f3 in cProtocol_1_9_0::HandlePacketPlayerPos (this=0x7fffc0000b20, a_ByteBuffer=...)
    at /home/lukas/cpp/cuberite/src/Protocol/Protocol_1_9.cpp:2702
#2  0x0000000000da7658 in cProtocol_1_12_1::HandlePacket (this=0x7fffc0000b20, a_ByteBuffer=..., a_PacketType=13)
    at /home/lukas/cpp/cuberite/src/Protocol/Protocol_1_12.cpp:1269
#3  0x0000000000d75466 in cProtocol_1_9_0::AddReceivedData (this=0x7fffc0000b20, a_Data=0x7ffff8015060 "\033",
    a_Size=28) at /home/lukas/cpp/cuberite/src/Protocol/Protocol_1_9.cpp:2048
#4  0x0000000000d746d7 in cProtocol_1_9_0::DataReceived (this=0x7fffc0000b20, a_Data=0x7ffff8015060 "\033",
    a_Size=28) at /home/lukas/cpp/cuberite/src/Protocol/Protocol_1_9.cpp:219
#5  0x0000000000d9149e in cProtocolRecognizer::DataReceived (this=0x7ffff80011c0, a_Data=0x7ffff8015060 "\033",
    a_Size=28) at /home/lukas/cpp/cuberite/src/Protocol/ProtocolRecognizer.cpp:68
#6  0x0000000000a4f7d1 in cClientHandle::ProcessProtocolInOut (this=0x7ffff8000d50)
    at /home/lukas/cpp/cuberite/src/ClientHandle.cpp:3340
#7  0x0000000000a4ef14 in cClientHandle::Tick (this=0x7ffff8000d50, a_Dt=51)
    at /home/lukas/cpp/cuberite/src/ClientHandle.cpp:2069
#8  0x0000000000b357c7 in cWorld::TickClients (this=0x7ffffdad0010, a_Dt=51)
    at /home/lukas/cpp/cuberite/src/World.cpp:1271
#9  0x0000000000b2909d in cWorld::Tick (this=0x7ffffdad0010, a_Dt=..., a_LastTickDurationMSec=...)
    at /home/lukas/cpp/cuberite/src/World.cpp:1040
#10 0x0000000000b289a5 in cWorld::cTickThread::Execute (this=0x7ffffe221818)
    at /home/lukas/cpp/cuberite/src/World.cpp:122
#11 0x0000000000b6fb22 in cIsThread::DoExecute (this=0x7ffffe221818)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:73
#12 0x0000000000b706e7 in std::__invoke_impl<void, void (cIsThread::*)(), cIsThread*> (
    __f=@0x673a0a0: (void (cIsThread::*)(cIsThread * const)) 0xb6faf0 <cIsThread::DoExecute()>,
    __t=@0x673a098: 0x7ffffe221818) at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:73
#13 0x0000000000b705f2 in std::__invoke<void (cIsThread::*)(), cIsThread*> (
    __fn=@0x673a0a0: (void (cIsThread::*)(cIsThread * const)) 0xb6faf0 <cIsThread::DoExecute()>,
    __args=@0x673a098: 0x7ffffe221818) at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:95
#14 0x0000000000b705b5 in std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> >::_M_invoke<0ul, 1ul>
    (this=0x673a098) at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/thread:244
#15 0x0000000000b70565 in std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> >::operator() (
    this=0x673a098) at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/thread:253
#16 0x0000000000b7032e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> > >::_M_run (this=0x673a090) at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/thread:196
#17 0x00007fffff53bb2f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#18 0x00007fffff446fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#19 0x00007fffff3694cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### PR DESCRIPTION
**Pull request by maxluchterhand1**
Fixes #4497

When chunks are loaded rapidly, cChunk::RemoveClient doesn't remove the corresponding entities fast enough.
This has lead to the unloading of chunks that still hold PlayerEntities, because their ClientHandlers were already removed, calling the Player objects destructor.

### CODE REVIEW

File: src/Chunk.cpp [hunk 1]
```diff
@@ -194,10 +194,28 @@ void cChunk::MarkRegenerating(void)
...
+{
+	bool hasPlayerEntities {false};
+	for (auto & Entity: m_Entities)
+	{
+		if (Entity->IsPlayer())
+		{
+			hasPlayerEntities = true;
+		}
+	}
+	return hasPlayerEntities;
```
Comment (peterbell10) [inline src/Chunk.cpp]:
```suggestion
	return std::any_of(m_Entities.begin(), m_Entities.end(),
		[](cEntitiy * Entity) {
			return Entity->IsPlayer();
		}
	);

```

File: src/Chunk.cpp [hunk 2]
```diff
@@ -194,10 +194,28 @@ void cChunk::MarkRegenerating(void)
...
+
+
+
+
+
 bool cChunk::CanUnload(void)
 {
 	return
 		m_LoadedByClient.empty() &&  // The chunk is not used by any client
+		!HasPlayerEntities() &&      // Ensure not only the absence of ClientHandlers, but also of cPlayer objects
```
Comment (peterbell10) [inline src/Chunk.cpp]: This should be added to `CanUnloadAfterSaving` as well.

Comment (maxluchterhand1) [reply src/Chunk.cpp]: Youre right!
