### PR TITLE
Hopefully fixed food drain bugs

### LINKED ISSUE #2044: Food drains too quickly.
Food appears to be mostly working, but it drains much more quickly than in the vanilla server.

### PR DESCRIPTION
**Pull request by tigerw**
Tada! Fixes #2044, #2414.

### CODE REVIEW

**Comment by tigerw** [comment]
Fancy new integration status is fancy.

**Comment by tigerw** [comment]
mergey mergey?

File: src/ClientHandle.cpp [hunk 1]
```diff
@@ -760,40 +759,31 @@ void cClientHandle::HandlePlayerPos(double a_PosX, double a_PosY, double a_PosZ,
 		return;
 	}
 
-	/*
-	// TODO: Invalid stance check
-	if ((a_PosY >= a_Stance) || (a_Stance > a_PosY + 1.65))
+	Vector3d NewPosition(a_PosX, a_PosY, a_PosZ);
+	Vector3d OldPosition = GetPlayer()->GetPosition();
+	auto PreviousIsOnGround = GetPlayer()->IsOnGround();
```
Comment (SphinxC0re) [inline src/ClientHandle.cpp]: isn't this supposed to be a bool? Also do generics get evaluated at compile time?

Comment (madmaxoft) [inline src/ClientHandle.cpp]: `auto` is better, we should use it whenever possible. Among others it makes maintenance easier, in case you're refactoring, changing the return type of a function, `auto` allows you to not care about the exact type.

File: src/Color.h [hunk 2]
```diff
@@ -15,7 +15,7 @@ class cColor
 {
 public:
 
-	enum
+	enum : unsigned int
```
Comment (madmaxoft) [inline src/Color.h]: Yeah, because it wouldn't be @tigerw if he didn't touch something unrelated :)

File: src/Entities/Player.cpp [hunk 3]
```diff
@@ -474,61 +451,87 @@ void cPlayer::SetTouchGround(bool a_bTouchGround)
...
+				(
+					cBlockSlabHandler::IsAnySlabType(GetWorld()->GetBlock((GetPosition() + Vector3d(0, 0, 0)).Floor())) ||
+					cBlockSlabHandler::IsAnySlabType(GetWorld()->GetBlock((GetPosition() + Vector3d(HalfWidth, 0, 0)).Floor())) ||
+					cBlockSlabHandler::IsAnySlabType(GetWorld()->GetBlock((GetPosition() + Vector3d(-HalfWidth, 0, 0)).Floor())) ||
+					cBlockSlabHandler::IsAnySlabType(GetWorld()->GetBlock((GetPosition() + Vector3d(0, 0, HalfWidth)).Floor())) ||
+					cBlockSlabHandler::IsAnySlabType(GetWorld()->GetBlock((GetPosition() + Vector3d(0, 0, -HalfWidth)).Floor()))
+				)
+			) ||
+			(
+				(fmod(GetPosY(), 0.125) <= std::numeric_limits<double>::epsilon()) &&
```
Comment (madmaxoft) [inline src/Entities/Player.cpp]: I think you're using `epsilon` for something it wasn't meant to be used for.
A hard-coded constant, `0.0001` or such, would have been better.

File: src/Entities/Player.cpp [hunk 4]
```diff
@@ -474,61 +451,87 @@ void cPlayer::SetTouchGround(bool a_bTouchGround)
...
+		m_bTouchGround = false;
+	}
+
+	if (IsFlying() || IsSwimming() || IsClimbing())
+	{
+		m_LastGroundHeight = GetPosY();
 	}
+
+	UNUSED(a_bTouchGround);
+	/* Unfortunately whatever the reason, there are still desyncs in on-ground status between the client and server. Por ejemplo:
```
Comment (madmaxoft) [inline src/Entities/Player.cpp]: Please use English only.

File: src/Entities/Player.cpp (hunk 3 above)
Comment (SphinxC0re) [inline src/Entities/Player.cpp]: But that's a *magic number*. We should at least define it somewhere.

Comment (madmaxoft) [inline src/Entities/Player.cpp]: That's why I said "named" - name it whatever, `EPS`, I don't care, but make the value reasonable, it's definitely not a `std::numeric_limits::epsilon`

File: src/Color.h (hunk 2 above)
Comment (tigerw) [inline src/Color.h]: Tee hee

**Comment by tigerw** [comment]
Now?

**Comment by SphinxC0re** [comment]
Try to leave out the *Hopefully* from the CM

**Comment by tigerw** [comment]
But then I shall be held responsible and burnt at the stake if it doesn't work! :P

**Comment by SphinxC0re** [comment]
Yeah, that's the thing

**Comment by SamJBarney** [comment]
@tigerw I'll provide the stake if it doesn't work, steak if it was properly tested and does :P

**Comment by SphinxC0re** [comment]
:clap:

**Comment by tigerw** [comment]
Let's see then:
