### PR TITLE
Changed big flowers so they can only be placed on dirt

### LINKED ISSUE #3559: Big flowers can be placed on anything
Client version:   1.10.2
Server OS:        Linux
Commit id:        97980d11038e57faa905a27977545fb77ff2c5bd

### Expected behavior
Big flowers should only be able to be placed on dirt.

### Actual behavior
Big flowers can be placed on any block.

### Steps to reproduce the behavior
Place a big flower (e.g. tall grass or a peony) on anything.

### PR DESCRIPTION
**Pull request by Altenius**
Fixes #3559

### CODE REVIEW

**Comment by Altenius** [comment]
Looks like Travis CI failed because apt-get install couldn't find a package.

File: src/Blocks/BlockBigFlower.h [hunk 1]
```diff
@@ -77,7 +77,10 @@ class cBlockBigFlowerHandler :
 
 	virtual bool CanBeAt(cChunkInterface & a_ChunkInterface, int a_RelX, int a_RelY, int a_RelZ, const cChunk & a_Chunk) override
 	{
-		return ((a_RelY > 0) && (a_Chunk.GetBlock(a_RelX, a_RelY - 1, a_RelZ) != E_BLOCK_AIR) && (a_RelY < cChunkDef::Height - 1) && ((a_Chunk.GetBlock(a_RelX, a_RelY + 1, a_RelZ) == E_BLOCK_AIR) || (a_Chunk.GetBlock(a_RelX, a_RelY + 1, a_RelZ) == E_BLOCK_BIG_FLOWER)));
+		BLOCKTYPE BlockType;
+		NIBBLETYPE BlockMeta;
+		a_Chunk.GetBlockTypeMeta(a_RelX, a_RelY - 1, a_RelZ, BlockType, BlockMeta);
```
Comment (madmaxoft) [inline src/Blocks/BlockBigFlower.h]: This will fail if `a_RelY` < 1

Overall, the condition below is really complicated, refactor it using standalone `if` statements to make it more readable.

Comment (Altenius) [inline src/Blocks/BlockBigFlower.h]: What do you mean by standalone if statements? Why not break it into multiple lines?

**Comment by Altenius** [comment]
I fixed the `a_RelY == 0` code and fixed another problem where tall flowers can only be placed if there's air above them, which isn't the case in vanilla.

File: src/Blocks/BlockBigFlower.h [hunk 2]
```diff
@@ -77,7 +77,15 @@ class cBlockBigFlowerHandler :
...
-		return ((a_RelY > 0) && (a_Chunk.GetBlock(a_RelX, a_RelY - 1, a_RelZ) != E_BLOCK_AIR) && (a_RelY < cChunkDef::Height - 1) && ((a_Chunk.GetBlock(a_RelX, a_RelY + 1, a_RelZ) == E_BLOCK_AIR) || (a_Chunk.GetBlock(a_RelX, a_RelY + 1, a_RelZ) == E_BLOCK_BIG_FLOWER)));
+		if (a_RelY <= 0)
+		{
+			return false;
+		}
+		BLOCKTYPE BlockType;
+		NIBBLETYPE BlockMeta;
+		a_Chunk.GetBlockTypeMeta(a_RelX, a_RelY - 1, a_RelZ, BlockType, BlockMeta);
+
+		return IsBlockTypeOfDirt(BlockType) || ((BlockType == E_BLOCK_BIG_FLOWER) && !(BlockMeta & 0x08));
```
Comment (madmaxoft) [inline src/Blocks/BlockBigFlower.h]: Style: Replace `!(BlockMeta & 0x08)` with an explicit comparison - we only allow bool values in conditions, the result of that expression is NOT a bool value.

Perhaps even better, replace it with a call to new function `IsMetaTopPart` - adds proper meaning and is much more maintainable.

**Comment by madmaxoft** [comment]
Wait, does this mean that a tall flower can drill through any block above it? So it would be possible to break above the Nether in vanilla?

**Comment by QuImUfu** [comment]
No, in vanilla you can't place duble plants, if there is something else than air in the upper block.

**Comment by Altenius** [comment]
What I meant was flowers can be placed if there's air above the top part.
