### PR TITLE
Tentative fix for player-limit race condition

### LINKED ISSUE #2257: Race condition in max player count
If more than one player attempts to join the server, in a short enough space of time, when the server is nearly at its max slot count, it can cause the server to allow more players on than the maximum.

### PR DESCRIPTION
**Pull request by tigerw**
* Attempts to fix #2257

Derived from d233e9843148313c71fbaba96ccff660e47b07b1

Tycho commented about DOS attacks if the kick logic was done during handshake, so I moved it to after authentication. I hope that this does not merely shift the problem from an artificially unresponsive server (limited by kicks during handshake due to too many handshakes) to an actual unresponsive server (limited by all those evil clients getting to the authenticate stage and loading down the auth. thread). But in the second case at least genuine clients can connect if the server can handle it :)

I also hope that the threading logic is sound.

### CODE REVIEW

**Comment by madmaxoft** [comment]
[Does not ~compute~ compile](https://www.youtube.com/watch?v=ZBAijg5Betw)

**Comment by tigerw** [comment]
ey xoft, I wanted to change the type of NumPlayers and MaxPlayers to size_t considering they aren't expected to go negative. However, this means that the OnServerPing hook needs a signedness change. Is this OK?

**Comment by madmaxoft** [comment]
That's okay.

File: src/ClientHandle.cpp [hunk 1]
```diff
@@ -1860,17 +1867,14 @@ bool cClientHandle::HandleHandshake(const AString & a_Username)
 {
 	if (a_Username.length() > 16)
 	{
-		Kick("Your username is too long(>16 characters)");
+		Kick("Your username is too long (>16 characters)");
 		return false;
 	}
 
-	if (!cRoot::Get()->GetPluginManager()->CallHookHandshake(*this, a_Username))
```
Comment (worktycho) [inline src/ClientHandle.cpp]: The removal of this `!`seems like it would cause a subtle change in behavior.

File: src/Server.cpp [hunk 2]
```diff
@@ -656,6 +626,12 @@ void cServer::KickUser(int a_ClientID, const AString & a_Reason)
 
 void cServer::AuthenticateUser(int a_ClientID, const AString & a_Name, const AString & a_UUID, const Json::Value & a_Properties)
 {
+	if (GetNumPlayers() >= GetMaxPlayers())
```
Comment (worktycho) [inline src/Server.cpp]: This still leaves potential for a race condition if multiple threads can execute AuthenticateUser. Is this function tied to a single thread? If not you can fix it by moving this condition to after taking the m_CSClients lock, so that only one thread can be between checking the condition and incrementing, but you should put a comment in here documenting that if you do so.

Comment (tigerw) [inline src/Server.cpp]: Yup. I seem to have made a fatal incorrect assumption about concurrency (again :P)

File: src/ClientHandle.cpp (hunk 1 above)
Comment (tigerw) [inline src/ClientHandle.cpp]: The [API document on the hook](https://api.cuberite.org/OnHandshake.html) says that plugins should return true to deny entry. Is this correct?

Comment (worktycho) [inline src/ClientHandle.cpp]: In which case the old code is buggy and needs to be fixed.

**Comment by madmaxoft** [comment]
Still does not compile.

File: src/Server.cpp (hunk 2 above)
Comment (peterbell10) [inline src/Server.cpp]: Another option would be to increment `m_PlayerCount` first and then check if they're allowed in.  That way accessing `m_PlayerCount` is still wait free.

Comment (tigerw) [inline src/Server.cpp]: Indeed, I may have tried something similar in d233e9843148313c71fbaba96ccff660e47b07b1. However, would this method have the potential to cause two clients vying for one remaining slot to both get kicked, with no one being let in?

**Comment by tigerw** [comment]
Is this acceptable?

File: src/Server.cpp (hunk 2 above)
Comment (peterbell10) [inline src/Server.cpp]: As long the comparison is done on the result of the `fetch_add` then It shouldn't be possible.

Comment (tigerw) [inline src/Server.cpp]: I was thinking if two threads incremented the count simultaneously and then proceeded to check the condition if would fail for both, but in fact, surely this function only ever is called by one thread per server run, since either authentication is on (and the single auth. thread calls it) or authentication is off, in which the server thread calls it.

Then if this is right, synchronisation is not needed...?

**Comment by tigerw** [comment]
Even if the check is only done by one thread, I will leave it as-is (guarded by mutex) since in any case it seems like a good idea, less prone to break in the future as a side-effect of say, dynamically updating the ShouldAuthenticate variable when a config. file is changed, if that gets implemented.
