### PR TITLE
Fix cChunkMap issues below with coords below y=0

### LINKED ISSUE #5395: Server crashes when mining bedrock with hack client
Client version: **Every client/ Server side bug**
Server OS: **Linux, Debian 11 bullseye Openvz virt**
Cuberite Commit id: (from commit **de5b89dbea938db5a7ea58f59a9b1a91d0df4208** built at: Thu Feb 17 19:02:07 UTC 2022t)

https://user-images.githubusercontent.com/101947415/159139880-bb78e427-9115-4f79-9f20-43fec9d15ffc.mp4

### PR DESCRIPTION
**Pull request by hle0**
Should fix #5395 and some other issues. See discussion in #5220. I noticed that lighting the void on fire (using a flint and steel on the side of bedrock at y=0) crashed the server before this PR, but not after. This should fix most other similar issues.

### CODE REVIEW

**Comment by bearbin** [comment]
Sorry for the delay in reviewing, I was a bit busy - I'll get round to it tomorrow.

File: src/ChunkMap.cpp [hunk 1]
```diff
@@ -585,6 +595,11 @@ void cChunkMap::SetBlock(Vector3i a_BlockPos, BLOCKTYPE a_BlockType, NIBBLETYPE
 
 bool cChunkMap::GetBlockTypeMeta(Vector3i a_BlockPos, BLOCKTYPE & a_BlockType, NIBBLETYPE & a_BlockMeta) const
 {
+	if (!cChunkDef::IsValidHeight(a_BlockPos.y))
+	{
+		return false;
```
Comment (bearbin) [inline src/ChunkMap.cpp:600]: I have a slight concern here that we might end up with use of uninitialised memory as a consequence of this return - idiomatic use of GBTM does not initialise the arguments, and with an early return they are not initialised here either. 

I think we should zero them here for safety.

**Review by bearbin — COMMENTED** [review]
This looks good generally. I think it might be slightly better though if we created new functions that do this checking, cWorld.SafeBlockTypeMeta or something - otherwise the behaviour of chunks' GBTM and worlds' GTBM functions will be different which could lead to confusion.

File: src/ChunkMap.cpp (hunk 1 above)
Comment (hle0) [reply src/ChunkMap.cpp:600]: I could be wrong, but I think there are other cases where early return does not initialize the arguments; for example, if `!Chunk->IsValid()`. I don't entirely understand when a Chunk would be invalid, but that's another case where the arguments will be left uninitialized. Also, most (all?) C++ compilers should zero the values anyway afaik, since they're enums, although I'm not totally sure.

Comment (bearbin) [reply src/ChunkMap.cpp:600]: You're right, we need to add an initialisation to the invalid chunk case as well. Most C++ compilers do zero-initialise variables, but that is non-standard undefined behaviour which we should not rely on.

Comment (madmaxoft) [reply src/ChunkMap.cpp:600]: I think the modus operandi "If the return value is `false`, then the out params are uninitialized" is valid. It should just probably be mentioned in the doxy-comment. All the callsites should be doing `if (!GetBlockTypeMeta(...)) { return ...; }` so the uninitialized values don't matter.

Comment (madmaxoft) [reply src/ChunkMap.cpp:600]: Perhaps, is there some marker that would tell the compilers that ignoring the return value of this function is a bad thing?

**Review by bearbin — APPROVED** [review]
Reviewing this so we can close out some stale PRs. 

I still think that this is a slightly flawed idea; we also need to do the same for the SetBlock functions. 

But better to fix the immediate issue and let us refactor later.

File: tests/CompositeChat/CompositeChatTest.cpp [hunk 2]
```diff
@@ -109,6 +109,7 @@ static void TestParser5(void)
 
 
 
+
```
Comment (bearbin) [inline tests/CompositeChat/CompositeChatTest.cpp:112]: This was a style violation caught by my pre-commit hook during the merge; easier just to fix it.
