### PR TITLE
Player death crashfix

### LINKED ISSUE #3112: Player deaths crash server
A recent commit created this month (March) causes the server to crash whenever a player dies.

This is the output in console:
```
[21:29:27]   D:    | Cuberite has encountered an error and needs to close
[21:29:27] Details | SIGABRT: Server self-terminated due to an internal fault
[21:29:27] Cuberite Jenkins clang x64 Release (master) build id: #439
[21:29:27] from commit id: 6d1d223d044d2237cc9b5e0c0656bcf2ab07ae77 built at: Wed 30 Mar 12:40:12 CEST 2016
./Cuberite(_Z15PrintStackTracev+0x19)[0x5eb289]
./Cuberite[0x5d5255]
/lib/x86_64-linux-gnu/libc.so.6(+0x355a0)[0x7f95285b45a0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f95285b4518]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f95285b60ea]
./Cuberite[0x5d525a]
/lib/x86_64-linux-gnu/libc.so.6(+0x355a0)[0x7f95285b45a0]
./Cuberite(_ZN4Json5ValueC2ERKSs+0x25)[0x84a675]
./Cuberite(_ZN7cPlayer10SaveToDiskEv+0x87e)[0x805bee]
./Cuberite(_ZN7cPlayer8KilledByER14TakeDamageInfo+0x223)[0x807f23]
./Cuberite(_ZN7cEntity12DoTakeDamageER14TakeDamageInfo+0x8f5)[0x7f5f25]
./Cuberite(_ZN7cPlayer12DoTakeDamageER14TakeDamageInfo+0xab)[0x807b9b]
./Cuberite(_ZN7cEntity10TakeDamageE11eDamageTypePS_iid+0x333)[0x7f4fe3]
./Cuberite[0x68949b]
./Cuberite[0x9ad649]
./Cuberite[0x9a748a]
./Cuberite[0x9ae07a]
./Cuberite[0x9ad16f]
./Cuberite[0x9ae36f]
./Cuberite(lua_pcall+0x10d)[0x9a2cbd]
./Cuberite(_ZN9cLuaState12CallFunctionEi+0x5e)[0x5f7d8e]
./Cuberite(_ZN10cPluginLua13HandleCommandERKSt6vectorISsSaISsEER7cPlayerRKSs+0x97)[0x623ae7]
./Cuberite(_ZN14cPluginManager13HandleCommandER7cPlayerRKSsb+0x174)[0x62a1f4]
./Cuberite(_ZN14cPluginManager12CallHookChatER7cPlayerRSs+0x21)[0x629b31]
./Cuberite(_ZN13cClientHandle10HandleChatERKSs+0x33)[0x54e093]
./Cuberite(_ZN12cProtocol18023HandlePacketChatMessageER11cByteBuffer+0x30)[0x6fc650]
./Cuberite(_ZN12cProtocol18012HandlePacketER11cByteBufferj+0x18b)[0x6fae6b]
./Cuberite(_ZN12cProtocol18015AddReceivedDataEPKcm+0x7cb)[0x6e87cb]
./Cuberite(_ZN12cProtocol18012DataReceivedEPKcm+0x72)[0x6e7fc2]
./Cuberite(_ZN13cClientHandle4TickEf+0x64)[0x54f6f4]
```

### PR DESCRIPTION
**Pull request by LogicParrot**
Closes #3112.

### CODE REVIEW

File: src/Entities/Player.cpp [hunk 1]
```diff
@@ -108,7 +108,7 @@ cPlayer::cPlayer(cClientHandlePtr a_Client, const AString & a_PlayerName) :
 		SetPosX(World->GetSpawnX());
 		SetPosY(World->GetSpawnY());
 		SetPosZ(World->GetSpawnZ());
-		SetBedPos(Vector3i(static_cast<int>(World->GetSpawnX()), static_cast<int>(World->GetSpawnY()), static_cast<int>(World->GetSpawnZ())));
+		SetBedPos(Vector3i(static_cast<int>(World->GetSpawnX()), static_cast<int>(World->GetSpawnY()), static_cast<int>(World->GetSpawnZ())), World);
```
Comment (LogicParrot) [inline src/Entities/Player.cpp]: That was very subtle.

**Comment by LogicParrot** [comment]
Merge if compiles
