### PR TITLE
Fixed DropSpenser sound

### LINKED ISSUE #2333: No dropper/dispensers sound
when droppers/dispensers are activated they don't make any sound

### PR DESCRIPTION
**Pull request by mmdk95**
Fixed #2333

### CODE REVIEW

File: src/BlockEntities/DropSpenserEntity.cpp [hunk 1]
```diff
@@ -75,7 +75,10 @@ void cDropSpenserEntity::DropSpense(cChunk & a_Chunk)
 	if (SlotsCnt == 0)
 	{
 		// Nothing in the dropspenser, play the click sound
-		m_World->BroadcastSoundEffect("random.click", m_PosX * 8, m_PosY * 8, m_PosZ * 8, 1.0f, 1.2f);
+		m_World->BroadcastSoundEffect("random.click", static_cast<double>(m_PosX),
+		                                              static_cast<double>(m_PosY),
+		                                              static_cast<double>(m_PosZ),
+													   1.0f, 1.2f);
```
Comment (NiLSPACE) [inline src/BlockEntities/DropSpenserEntity.cpp]: Does our current style rules allow this?

Comment (mmdk95) [inline src/BlockEntities/DropSpenserEntity.cpp]: @NiLSPACE I thought I added spaces instead of tabs, I'll fix that right now.
I think that is what you meant?
"Please use tabs for indentation and spaces for alignment. This means that if it's at line start, it's a tab; if it's in the middle of a line, it's a space"

Comment (NiLSPACE) [inline src/BlockEntities/DropSpenserEntity.cpp]: No, you did the tabs properly, but the way the function is spread over multiple lines might not be accepted by our style checker.

Comment (tigerw) [inline src/BlockEntities/DropSpenserEntity.cpp]: May I suggest the following layout:

```cpp
m_World->BroadcastSoundEffect(
	"random.click",
	static_cast<double>(m_PosX),
	static_cast<double>(m_PosY),
	static_cast<double>(m_PosZ),
	1.0f,
	1.0f
);
```

Though really, I personally wouldn't mind
```cpp
m_World->BroadcastSoundEffect("random.click", static_cast<double>(m_PosX), static_cast<double>(m_PosY), static_cast<double>(m_PosZ), 1.0f, 1.0f);
```

Comment (NiLSPACE) [inline src/BlockEntities/DropSpenserEntity.cpp]: I prefer everything over one line.

Comment (mmdk95) [inline src/BlockEntities/DropSpenserEntity.cpp]: Oh okay, well have to fix it again then

**Comment by NiLSPACE** [comment]
Great, could you squash everything in a single commit? Otherwise the history will be cluttered up with 3 commits for just 2 lines ;)

**Comment by SphinxC0re** [comment]
Also rebase onto current master

**Comment by mmdk95** [comment]
@NiLSPACE Eh... yeah, if I knew how xD
@SphinxC0re Sure

**Comment by tigerw** [comment]
#### For squashing:
In your master branch in git shell, type:
```
git rebase -i HEAD~3
```
In the text editor that comes up, change the tag of everything but the first line to `squash`:
```
pick 2a90402 Fixed DropSpenser sound
squash 8c1dd48 Oops... I blame VS
squash 991ae20 This was my fault
...
```
Save the file and close the editor. Another editor will appear and ask you to give the squashed commit a name. Change to something like "Fixed DropSpenser sound", save and close, and then do a `git push -f`.

That should do it.

**Comment by mmdk95** [comment]
@tigerw Thank you

**Comment by SphinxC0re** [comment]
@mmdk95 you can just rebase like this:
```git rebase master -i```

**Comment by mmdk95** [comment]
@SphinxC0re I got "noop"

**Comment by SphinxC0re** [comment]
You have to do it when you are on your branch. And - oh I see - you have to rebase onto the origin master. Not on you upstream
so usually your master follows upstream/master or so because it is your fork.
Your branch should be rebased like this:
```git rebase origin/master -i```

**Comment by mmdk95** [comment]
@SphinxC0re I've got the same result

**Comment by SphinxC0re** [comment]
Show me the output of ```git remote show```

**Comment by mmdk95** [comment]
@SphinxC0re 
```
D:\Projects\c++\cuberite [master]> git status
On branch master
Your branch is up-to-date with 'origin/master'
```

**Comment by SphinxC0re** [comment]
```git remote show``` ? :smile:

**Comment by mmdk95** [comment]
@SphinxC0re Yeah, sorry I thought I had copied it, I updated last one

**Comment by SphinxC0re** [comment]
Okay then,
```git rebase cuberite/master -i```

**Comment by mmdk95** [comment]
@SphinxC0re Nothing seems to have happened, but I saw the commit at least

**Comment by SphinxC0re** [comment]
After that you force-push on the current branch
```git push origin master -f```

**Comment by mmdk95** [comment]
@SphinxC0re 
```D:\Projects\c++\cuberite [master]> git push origin master -f
Everything up-to-date
```

**Comment by SphinxC0re** [comment]
It's okay :+1:

**Comment by mmdk95** [comment]
Okay :)
