### PR TITLE
Fixed cFastRandom Test.

### LINKED ISSUE #3290: FastRandom self-test does not compile.
```
/home/bearbin/github/cuberite/cuberite/src/FastRandom.cpp:71:16: error: use
      of old-style cast [-Werror,-Wold-style-cast]
                double avg = (double)sum / ITER;
                             ^       ~~~
/home/bearbin/github/cuberite/cuberite/src/FastRandom.cpp:94:12: error: use
      of old-style cast [-Werror,-Wold-style-cast]
                        Counts[((int)v) % BUCKETS]++;
                                ^    ~
/home/bearbin/github/cuberite/cuberite/src/FastRandom.cpp:104:3: error: no
      previous extern declaration for non-static variable 'g_Test'
      [-Werror,-Wmissing-variable-declarations]
} g_Test;
  ^
/home/bearbin/github/cuberite/cuberite/src/FastRandom.cpp:104:3: error: 
      declaration requires a global constructor
      [-Werror,-Wglobal-constructors]
} g_Test;
```

### PR DESCRIPTION
**Pull request by bearbin**
This resolves #3290 

@madmaxoft Have I done this right?

### CODE REVIEW

File: tests/FastRandom/FastRandomTest.cpp [hunk 1]
```diff
@@ -0,0 +1,71 @@
+
+// FastRandom.cpp
```
Comment (madmaxoft) [inline tests/FastRandom/FastRandomTest.cpp]: Wrong filename

**Comment by bearbin** [comment]
@madmaxoft Done.
