### PR TITLE
fixed generator for mega taiga

### LINKED ISSUE #243: Add Mega Taiga Biome
This is a very rare biome
- [x] Contains 2x2 Spruce trees
- [x] Has a dirt block variant known as Podzol.
Currently obtained only by the silk touch enchantment.
- [x] Contains dirt blocks that do not allow grass to grow.
They have a data value of 1.
- [x] Moss Stone "boulders" are scattered around in this biome.
- [x] Dead Bushes
- [x] Mushrooms
- [x] Ferns

### PR DESCRIPTION
**Pull request by 12xx12**
This is a very rare biome
- [x] Contains 2x2 Spruce trees
- [x] Has a dirt block variant known as Podzol.
Currently obtained only by the silk touch enchantment.
- [x] Contains dirt blocks that do not allow grass to grow.
They have a data value of 1.
- [x] Moss Stone "boulders" are scattered around in this biome.
- [x] Dead Bushes, Mushrooms, and Ferns spawn in this biome.

Most of the stuff has already been done. There are some small details missing

fixes #243 

Looks like this right now:

### CODE REVIEW

**Comment by 12xx12** [comment]
Updated screenshot with mossy cobble stone

**Comment by Titaniumtown** [comment]
Anything preventing this being merged?

**Comment by 12xx12** [comment]
Me not being able to merge my own PR 😀

File: src/Generating/FinishGen.cpp [hunk 1]
```diff
@@ -2185,3 +2213,82 @@ void cFinishGenOrePockets::imprintSphere(
...
+
+
+
+void cFinishGenForestRocks::GenFinish(cChunkDesc & a_ChunkDesc)
+{
+	auto Biome = a_ChunkDesc.GetBiome(cChunkDef::Width / 2, cChunkDef::Width / 2);
+	if ((Biome != biMegaTaiga) && (Biome != biMegaTaigaHills))
+	{
+		return;
+	}
```
Comment (tigerw) [inline src/Generating/FinishGen.cpp:2230]: Should this come after we've picked an X, Z or is this intended?

File: src/Generating/FinishGen.cpp [hunk 2]
```diff
@@ -2185,3 +2213,82 @@ void cFinishGenOrePockets::imprintSphere(
...
+
+	// Choose random position in chunk and place boulder around it
+	auto Pos = Vector3i(
+		m_Noise.IntNoise2DInt(a_ChunkDesc.GetChunkX(), a_ChunkDesc.GetChunkZ()) % cChunkDef::Width,
+		0,
+		m_Noise.IntNoise2DInt(a_ChunkDesc.GetChunkX(), a_ChunkDesc.GetChunkZ()) % cChunkDef::Width
+		);
+	Pos.y = a_ChunkDesc.GetHeight(Pos.x, Pos.z) % cChunkDef::Height;
+
+	if (!cChunkDef::IsValidRelPos(Pos))
```
Comment (tigerw) [inline src/Generating/FinishGen.cpp:2240]: Why wouldn't Pos be valid here?

File: src/Generating/FinishGen.cpp [hunk 3]
```diff
@@ -2185,3 +2213,82 @@ void cFinishGenOrePockets::imprintSphere(
...
+	{
+		Radius = 2;
+	}
+	else if (RadiusChance > ThreeLimit)
+	{
+		Radius = 3;
+	}
+
+	Pos.x = Clamp(Pos.x, 0 + Radius, cChunkDef::Width - Radius - 1);
+	Pos.z = Clamp(Pos.z, 0 + Radius, cChunkDef::Width - Radius - 1);
```
Comment (tigerw) [inline src/Generating/FinishGen.cpp:2261]: `// Maintain distance from edge of chunk to avoid getting clipped:`

Also an extra `0 +`, or is that intended?

File: src/Generating/FinishGen.cpp [hunk 4]
```diff
@@ -2185,3 +2213,82 @@ void cFinishGenOrePockets::imprintSphere(
...
+	auto StartBlock = a_ChunkDesc.GetBlockType(Pos.x, Pos.y + Radius, Pos.z);
+	while (!((StartBlock == E_BLOCK_DIRT) || (StartBlock == E_BLOCK_GRASS)))
+	{
+		Pos.y -= 1;
+		if (!cChunkDef::IsValidRelPos(Pos.addedY(-Radius)))
+		{
+			return;
+		}
+		StartBlock = a_ChunkDesc.GetBlockType(Pos.x, Pos.y + Radius, Pos.z);
+	}
```
Comment (tigerw) [inline src/Generating/FinishGen.cpp:2272]: GetBlockType at the start might be called with out of bounds Y if Pos.y is high enough.

If I understand correctly, this always sinks the tip of the boulder flush with the ground. What do you think about placing the boulder's centre at the first valid StartBlock, then randomly moving down by [0, -Radius], and finally clamping Pos.y?,

File: src/Generating/FinishGen.cpp [hunk 5]
```diff
@@ -2185,3 +2213,82 @@ void cFinishGenOrePockets::imprintSphere(
...
+		for (int y = -Radius; y <= Radius; y++)
+		{
+			for (int z = -Radius; z <= Radius; z++)
+			{
+				if (!cChunkDef::IsValidRelPos({ Pos.x + x, Pos.y + y, Pos.z + z }))
+				{
+					continue;
+				}
+
+				if (Vector3d(x, y, z).Length() - 0.25 > Radius)
```
Comment (tigerw) [inline src/Generating/FinishGen.cpp:2285]: Vector3f and SqrLength > (Radius^2 + 0.5 * Radius) would be a small optimisation, sqrt is apparently expensive

File: src/Generating/FinishGen.cpp (hunk 1 above)
Comment (12xx12) [reply src/Generating/FinishGen.cpp:2230]: actually we could use the position x,z to check if that block is valid - you are right

File: src/Generating/FinishGen.cpp (hunk 2 above)
Comment (12xx12) [reply src/Generating/FinishGen.cpp:2240]: Good Question

File: src/Generating/FinishGen.cpp (hunk 3 above)
Comment (12xx12) [reply src/Generating/FinishGen.cpp:2261]: This is just left over from experimenting

File: src/Generating/FinishGen.cpp (hunk 5 above)
Comment (12xx12) [reply src/Generating/FinishGen.cpp:2285]: calculating sqrt sux on any  cpu - yeah

File: src/Generating/FinishGen.cpp (hunk 4 above)
Comment (12xx12) [reply src/Generating/FinishGen.cpp:2272]: The thing is that the position might be on top of a tree (the same reason why we don't get grass generation beneath trees) so we would need to move this down to the ground first and then randomize

**Comment by 12xx12** [comment]
Updated generation

**Comment by 12xx12** [comment]
I like the new stones better
