### PR TITLE
Basic elytra flight 

### LINKED ISSUE #4311: Implement Elytra
Client version:   1.8 -> 1.12
Server OS:        Raspbian OS & Ubuntu
Commit id:        6c3dd41717664c75bf77392dd4a4df3b35678fa5

### Expected behavior
Elytra should glide

### Actual behavior
Elytra doesnt glide

### Steps to reproduce the behavior
try to glide with elytra

### PR DESCRIPTION
**Pull request by dImrich**
Basic elytra flight with some changes in player size, stance / eye pos code.

I recorded a quick preview

[](https://www.youtube.com/watch?v=jQ8Da53MwcQ)
[](https://www.youtube.com/watch?v=KoAAzW-uMjs)

Fixes #4311

### CODE REVIEW

File: src/Entities/Player.cpp [hunk 1]
```diff
@@ -426,12 +428,75 @@ void cPlayer::Tick(std::chrono::milliseconds a_Dt, cChunk & a_Chunk)
...
+			EyeHeight = 0.2F;
+		}
+		else if (IsCrouched())
+		{
+			EyeHeight -= 0.08F;
+		}
+		else if (IsElytraFlying())
+		{
+			EyeHeight = 0.4F;
+		}
```
Comment (bearbin) [inline src/Entities/Player.cpp:470]: I don't like that the logic here is different from the logic above, could the two be combined so EyeHeight and Width/Height is guaranteed to be consistent. (the slight inefficiency from declaring the variable in advance is minor, and the compiler will probably optimise it out anyway)

File: src/Entities/Player.cpp [hunk 2]
```diff
@@ -426,12 +428,75 @@ void cPlayer::Tick(std::chrono::milliseconds a_Dt, cChunk & a_Chunk)
...
+
+		m_TicksElytraFlying++;
+	}
+	else if (m_IsElytraFlying)
+	{
+		m_TicksElytraFlying = 0;
+		m_IsElytraFlying = false;
+		m_World->BroadcastEntityMetadata(*this);
+	}
```
Comment (bearbin) [inline src/Entities/Player.cpp:498]: Use IsElytraFlying() rather than m_IsElytraFlying to be consistent. Also is there a reason SetElytraFlight is not used here?

File: src/Items/ItemArmor.h [hunk 3]
```diff
@@ -114,6 +114,7 @@ class cItemArmorHandler:
 			case E_ITEM_LEATHER_CAP:
 			case E_ITEM_LEATHER_PANTS:
 			case E_ITEM_LEATHER_TUNIC:
+			case E_ITEM_ELYTRA:
```
Comment (bearbin) [inline src/Items/ItemArmor.h:117]: No phantom membrane? This at least needs a TODO.

**Review by bearbin — COMMENTED** [review]
Generally good, a few small bits that need changing though :)

File: src/Items/ItemArmor.h (hunk 3 above)
Comment (dImrich) [reply src/Items/ItemArmor.h]: I thought adding it but we don't even have membrane in item lists. I added todo with some basic info.

**Comment by 12xx12** [comment]
I like the flight ingame

**Review by 12xx12 — APPROVED** [review]

**Comment by Titaniumtown** [comment]
Anything blocking this being merged?

**Comment by tigerw** [comment]
Need to check the RelativeEyeHeight, stance, and bounding box changes
