### PR TITLE
Fix use after move in cItemBowHandler::OnItemShoot

### LINKED ISSUE #3938: Bow with flame enchantment crashes server
Client version:   1.12.1
Server OS:        Linux
Commit id:        ad3192d6962536e21233710febca9f128b8e0b80


### Expected behavior
A bow with flame enchantment (id 50) doesn't crash the server when using it.

### Actual behavior
Server crashes. Started happening in a recent build of Cuberite.

```
[20:21:15]   D:    | Cuberite has encountered an error and needs to close                                                                                                                                                                     
[20:21:15] Details | SIGSEGV: Segmentation fault                                                                                                                                                                                              
[20:21:15] Cuberite local build build id: Unknown                                                                                                                                                                                             
[20:21:15] from commit id: approx: ad3192d6962536e21233710febca9f128b8e0b80 built at: approx: 2017-08-21 16:00:49 +0200                                                                                                                       
./Cuberite(_Z15PrintStackTracev+0x15)[0x563c0f7fd435]                                                                                                                                                                                         
./Cuberite(+0x2a6424)[0x563c0f7eb424]                                                                                                                                                                                                         
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7f914700e030]
./Cuberite(_ZN7cEntity12StartBurningEi+0x0)[0x563c0fa4d510]                                                                                                                                                                                   
./Cuberite(_ZN15cItemBowHandler11OnItemShootEP7cPlayeriii10eBlockFace+0x3db)[0x563c0f8e851b]                                                                                                                                                  
./Cuberite(_ZN13cClientHandle15HandleLeftClickEiii10eBlockFaceh+0x11e)[0x563c0f743d2e]                                                                                                                                                        
./Cuberite(_ZN15cProtocol_1_9_020HandlePacketBlockDigER11cByteBuffer+0x8c)[0x563c0f938bfc]                                                                                                                                                    
./Cuberite(_ZN16cProtocol_1_12_112HandlePacketER11cByteBufferj+0x196)[0x563c0f958d46]                                                                                                                                                         
./Cuberite(_ZN15cProtocol_1_9_015AddReceivedDataEPKcm+0x30e)[0x563c0f9448de]                                                                                                                                                                                                                                                                                                                
[20:21:15] Kicking player Wither_Skeleton for "Server is restarting. Please wait..."                                                                                                                                                                                                                                                                                                              
./Cuberite(_ZN15cProtocol_1_9_012DataReceivedEPKcm+0x6a)[0x563c0f94513a]                                                                                                                                                                      
./Cuberite(_ZN19cProtocolRecognizer12DataReceivedEPKcm+0x23)[0x563c0f94ded3]                                                                                                                                                                  
./Cuberite(_ZN13cClientHandle20ProcessProtocolInOutEv+0x71)[0x563c0f748151]                                                                                                                                                                   
./Cuberite(_ZN13cClientHandle4TickEf+0x24)[0x563c0f74a974]                                                                                                                                                                                    
./Cuberite(_ZN6cWorld11TickClientsEf+0x193)[0x563c0f7dbe13]                                                                                                                                                                                   
./Cuberite(_ZN6cWorld4TickENSt6chrono8durationIlSt5ratioILl1ELl1000EEEES4_+0x2a8)[0x563c0f7e0518]                                                                                                                                             
./Cuberite(_ZN6cWorld11cTickThread7ExecuteEv+0x84)[0x563c0f7e08f4]                                                                                                                                                                            
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb9e6f)[0x7f9147b6be6f]                                                                                                                                                                            
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x7f9147381494]                                                                                                                                                                                
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f91470c3aff]                                                                                                                                                                                   
[20:21:15]   D:    | Cuberite has encountered an error and needs to close                                                                                                                                                                     
[20:21:15] Details | SIGABRT: Server self-terminated due to an internal fault                                                                                                                                                                 
[20:21:15] Cuberite local build build id: Unknown                                                                                                                                                                                             
[20:21:15] from commit id: approx: ad3192d6962536e21233710febca9f128b8e0b80 built at: approx: 2017-08-21 16:00:49 +0200                                                                                                                       
./Cuberite(_Z15PrintStackTracev+0x15)[0x563c0f7fd435]                                                                                                                                                                                         
./Cuberite(+0x2a6424)[0x563c0f7eb424]                                                                                                                                                                                                         
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7f914700e030]                                                                                                                                                                                     
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf)[0x7f914700dfcf]                                                                                                                                                                                 
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f914700f3fa]                                                                                                                                                                                  
./Cuberite(+0x2a6429)[0x563c0f7eb429]                                                                                                                                                                                                         
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7f914700e030]                                                                                                                                                                                     
./Cuberite(_ZN7cEntity12StartBurningEi+0x0)[0x563c0fa4d510]                                                                                                                                                                                   
./Cuberite(_ZN15cItemBowHandler11OnItemShootEP7cPlayeriii10eBlockFace+0x3db)[0x563c0f8e851b]                                                                                                                                                  
./Cuberite(_ZN13cClientHandle15HandleLeftClickEiii10eBlockFaceh+0x11e)[0x563c0f743d2e]                                                                                                                                                        
./Cuberite(_ZN15cProtocol_1_9_020HandlePacketBlockDigER11cByteBuffer+0x8c)[0x563c0f938bfc]                                                                                                                                                    
./Cuberite(_ZN16cProtocol_1_12_112HandlePacketER11cByteBufferj+0x196)[0x563c0f958d46]                                                                                                                                                         
./Cuberite(_ZN15cProtocol_1_9_015AddReceivedDataEPKcm+0x30e)[0x563c0f9448de]                                                                                                                                                                  
./Cuberite(_ZN15cProtocol_1_9_012DataReceivedEPKcm+0x6a)[0x563c0f94513a]                                                                                                                                                                      
./Cuberite(_ZN19cProtocolRecognizer12DataReceivedEPKcm+0x23)[0x563c0f94ded3]                                                                                                                                                                  
./Cuberite(_ZN13cClientHandle20ProcessProtocolInOutEv+0x71)[0x563c0f748151]                                                                                                                                                                   
./Cuberite(_ZN13cClientHandle4TickEf+0x24)[0x563c0f74a974]
./Cuberite(_ZN6cWorld11TickClientsEf+0x193)[0x563c0f7dbe13]
./Cuberite(_ZN6cWorld4TickENSt6chrono8durationIlSt5ratioILl1ELl1000EEEES4_+0x2a8)[0x563c0f7e0518]
./Cuberite(_ZN6cWorld11cTickThread7ExecuteEv+0x84)[0x563c0f7e08f4]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb9e6f)[0x7f9147b6be6f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x7f9147381494]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f91470c3aff]
```

### Steps to reproduce the behavior
Run the command "/ienchant 50 1" in the chat when holding a bow, and shoot it.

### PR DESCRIPTION
**Pull request by peterbell10**
Fixes #3938

### CODE REVIEW

File: src/Items/ItemBow.h [hunk 1]
```diff
@@ -91,16 +91,15 @@ class cItemBowHandler :
 			}
 			else
 			{
-				Arrow->SetPickupState(cArrowEntity::psNoPickup);
+				ArrowPtr->SetPickupState(cArrowEntity::psNoPickup);
```
Comment (madmaxoft) [inline src/Items/ItemBow.h]: I'd have expected the compiler to complain about use-after-move

Comment (Seadragon91) [inline src/Items/ItemBow.h]: I checked this and no compiler wouldn't warn of this. There is a tool named `clang-tidy` that has a check named `misc-use-after-move`, but it's in llvm 6..

Comment (Seadragon91) [inline src/Items/ItemBow.h]: I tested clang-tidy and found out that it's only checks the code in the source files, not in the header files. After creating `ItemBow.cpp` I got the use-after-move warning.
